version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.24.0
    hostname: azurite
    restart: unless-stopped
    command: 'azurite --silent --location /workspace --debug /workspace/debug.log --tableHost 0.0.0.0 --tablePort 10002'
    ports:
      - '10002:10002'
    volumes:
      - audit-azurite-data:/workspace
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==

volumes:
  audit-azurite-data:
    driver: local

networks:
  default:
    name: audit-test-network
