version: '3.9'

services:
  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: klicker
      MONGO_INITDB_ROOT_PASSWORD: klicker
    ports:
      - 27017:27017
    networks:
      - klicker-dev
    volumes:
      - /data/db

networks:
  klicker-dev:
    driver: bridge