cache:
  port: 32705

s3:
  endpoint: tc-klicker-prod.s3.amazonaws.com
  bucket: images
  region: eu-central-1

email:
  from: klicker.support@uzh.ch
  host: smtp.uzh.ch
  user: klicker.support@uzh.ch

security:
  domain: klicker.uzh.ch

analytics:
  sentry:
    frontend:
      environment: prod

frontend:
  replicaCount: 1

  displayAAI: true

  hostname: app.klicker.uzh.ch

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: app.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-tls
        hosts:
          - app.klicker.uzh.ch
      - secretName: klicker-prod-frontend-tls
        hosts:
          - app.klicker.uzh.ch

backend:
  replicaCount: 1

  hostname: api.klicker.uzh.ch

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: api.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-tls
        hosts:
          - api.klicker.uzh.ch
      - secretName: klicker-prod-backend-tls
        hosts:
          - api.klicker.uzh.ch
