imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

redis:
  # architecture: standalone
  auth:
    enabled: false

  master:
    persistence:
      enabled: false

  replica:
    replicaCount: 1

    persistence:
      enabled: false

security:
  https:
    enabled: true
  csp:
    enabled: false
    reportUri: https://sentry.ibf-devops.ch/api/2/security/?sentry_key=d07ee657684f46498c264c01a3fc7226
  expectCt:
    enabled: false
    frontend: https://sentry.ibf-devops.ch/api/2/security/?sentry_key=d07ee657684f46498c264c01a3fc7226
    backend: https://sentry.ibf-devops.ch/api/3/security/?sentry_key=670985cada43448bae071dc933747c27
  frameguard:
    enabled: false
  hsts:
    enabled: false
  cors:
    frontend: https://www.klicker.uzh.ch,http://www.klicker.uzh.ch,http://localhost:3000
    backend: https://www.klicker.uzh.ch,http://localhost:3000

analytics:
  sentry:
    frontend:
      enabled: true
      dsn: https://289e41bc625b4b9eb10e1e5d347768f8@o86798.ingest.sentry.io/5431862
      org: uzh-bf
      project: klicker-react
    backend:
      enabled: false
  logrocket:
    enabled: false
    appId: vqm2qj/klicker
  google:
    enabled: false
    trackingId: UA-33258666-18

frontend:
  replicaCount: 1

  displayAAI: false

  image:
    repository: ghcr.io/uzh-bf/klicker-uzh/frontend
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      cert-manager.io/cluster-issuer: letsencrypt

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 7
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

backend:
  replicaCount: 1

  redis: {}

  image:
    repository: ghcr.io/uzh-bf/klicker-uzh/backend
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 4000

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      cert-manager.io/cluster-issuer: letsencrypt

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 7
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
