import { createCompetenceTreeSchema } from '@klicker-uzh/adaptive-server/schema/competenceTree'
import builder from '../builder.js'
import { ElementType } from './elementData.js'

export const {
  AdaptiveLevelMappingRule,
  AdaptiveNodeKind,
  CompetenceTreeCatalogOwnership,
  CompetenceTreeLevelInputRef,
  CompetenceTreeLevelInput,
  CompetenceTreeNodeInputRef,
  CompetenceTreeNodeInput,
  CompetenceTreeCoverageInputRef,
  CompetenceTreeCoverageInput,
  CompetenceTreeAssignmentInputRef,
  CompetenceTreeAssignmentInput,
  CompetenceTreeElementAssignmentUpdateInputRef,
  CompetenceTreeElementAssignmentUpdateInput,
  CompetenceTreeElementAssignmentCreateInputRef,
  CompetenceTreeElementAssignmentCreateInput,
  CompetenceTreeInputRef,
  CompetenceTreeInput,
  CompetenceTreeMetadataInputRef,
  CompetenceTreeMetadataInput,
  DuplicateCompetenceTreeInputRef,
  DuplicateCompetenceTreeInput,
  CompetenceTreeValidationIssueType,
  NormalizedCompetenceWeightType,
  CompetenceTreeValidationResultRef,
  CompetenceTreeValidationResultType,
  CompetenceTreeCourse,
  CompetenceTreeLevel,
  CompetenceTreeNode,
  CompetenceTreeCoverage,
  CompetenceTreeAssignment,
  CompetenceTreeSummaryRef,
  CompetenceTreeSummaryType,
  CompetenceTreeCatalogPageType,
  CompetenceTreeRef,
  CompetenceTree,
} = createCompetenceTreeSchema(builder, { ElementType })
