[tool.poetry]
name = "@klicker-uzh/qti"
version = "0.0.1"
description = ""
authors = ["Roland Schlaefli <roland.schlaefli@df.uzh.ch>"]
readme = "README.md"
packages = [{include = "@klicker_uzh"}]

[tool.poetry.dependencies]
python = "^3.12"
eq-quizgen = "^0.2.8"
json2xml = "^5.0.4"
lxml = "^5.3.0"
jinja2 = "^3.1.4"
markdown = "^3.6"


[tool.poetry.group.dev.dependencies]
poethepoet = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
