# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/backend-sls"
    target-branch: v2
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/frontend-learning"
    target-branch: v2
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/frontend-manage"
    target-branch: v2
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/frontend-pwa"
    target-branch: v2
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/graphql"
    target-branch: v2
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/prisma"
    target-branch: v2
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/lti"
    target-branch: v2
    schedule:
      interval: "daily"
