import { describe, expect, it } from 'vitest'
import { isValidSubmissionId } from '../src/submissionId.js'

describe('isValidSubmissionId', () => {
  it('accepts the identifiers generated by the PWA', () => {
    expect(
      isValidSubmissionId(
        '002707c5-950a-491a-a881-069f0f04f64f:lq-35aad5d9-285d-4dda-9e19-7507ee16e9e1-ex-0-i-13'
      )
    ).toBe(true)
    expect(isValidSubmissionId('a:b_c-d')).toBe(true)
  })

  it('rejects non-string and empty values', () => {
    for (const value of [undefined, null, 42, {}, '', true]) {
      expect(isValidSubmissionId(value)).toBe(false)
    }
  })

  it('rejects identifiers outside the bounded character set', () => {
    for (const value of [
      'has space',
      'unicode-ümlaut',
      'line\nbreak',
      'quot"e',
      'sla\\sh',
    ]) {
      expect(isValidSubmissionId(value)).toBe(false)
    }
  })

  it('rejects identifiers beyond the length bound', () => {
    expect(isValidSubmissionId('a'.repeat(256))).toBe(true)
    expect(isValidSubmissionId('a'.repeat(257))).toBe(false)
  })
})
