services:
  reverse_proxy_docker:
    build:
      context: ./util/traefik
      dockerfile: Dockerfile
    command:
      # Rules
      - --providers.file=true
      - --providers.file.filename=/etc/traefik/rules.yaml
      - --providers.file.watch=true

      # API and dashboard
      - '--api.insecure=true'
      - '--api.dashboard=true'

      # Entry points configuration
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'

      # HTTP/2 configuration (critical for subscriptions)
      - '--entrypoints.websecure.http.tls=true'
      - '--entrypoints.websecure.http2.maxConcurrentStreams=250'

      # HTTP to HTTPS redirect
      # - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      # - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - 80:80
      - 443:443
      - 8090:8080
    volumes:
      - './util/traefik/rules_docker.yaml:/etc/traefik/rules.yaml'
      - './util/traefik/ssl:/etc/certs:ro'
    networks:
      - klicker
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  reverse_proxy_macos:
    build:
      context: ./util/traefik
      dockerfile: Dockerfile
    command:
      # Rules
      - --providers.file=true
      - --providers.file.filename=/etc/traefik/rules.yaml
      - --providers.file.watch=true

      # API and dashboard
      - '--api.insecure=true'
      - '--api.dashboard=true'

      # Entry points configuration
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'

      # HTTP/2 configuration (critical for subscriptions)
      - '--entrypoints.websecure.http.tls=true'
      - '--entrypoints.websecure.http2.maxConcurrentStreams=250'

      # HTTP to HTTPS redirect
      # - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      # - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - 80:80
      - 443:443
      - 8090:8080
    volumes:
      - './util/traefik/rules_docker.yaml:/etc/traefik/rules.yaml'
      - './util/traefik/ssl:/etc/certs:ro'
    networks:
      - klicker

  reverse_proxy_wsl:
    build:
      context: ./util/traefik
      dockerfile: Dockerfile.wsl
    command:
      # Rules
      - --providers.file=true
      - --providers.file.filename=/etc/traefik/rules.yaml
      - --providers.file.watch=true

      # API and dashboard
      - '--api.insecure=true'
      - '--api.dashboard=true'

      # Entry points configuration
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'

      # HTTP/2 configuration (critical for subscriptions)
      - '--entrypoints.websecure.http.tls=true'
      - '--entrypoints.websecure.http2.maxConcurrentStreams=250'

      # HTTP to HTTPS redirect
      # - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      # - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - 80:80
      - 443:443
      - 8090:8080
    volumes:
      - './util/traefik/rules_wsl.yaml:/etc/traefik/rules.yaml'
      - './util/traefik/ssl:/etc/certs:ro'
    networks:
      - klicker

  auth:
    profiles:
      - full
    image: ghcr.io/uzh-bf/klicker-uzh/auth:v3
    environment:
      APP_SECRET: abcd
      DATABASE_URL: 'postgres://klicker-prod:klicker@postgres:5432/klicker-prod'
      # EDUID_CLIENT_SECRET: ''
      # TEAMS_WEBHOOK_URL: ''
    ports:
      - 3010:3000
    networks:
      - klicker

  frontend_pwa:
    profiles:
      - full
    image: ghcr.io/uzh-bf/klicker-uzh/frontend-pwa:v3
    environment:
      APP_SECRET: abcd
    ports:
      - 3001:3000
    networks:
      - klicker

  frontend_manage:
    profiles:
      - full
    image: ghcr.io/uzh-bf/klicker-uzh/frontend-manage:v3
    ports:
      - 3002:3000
    networks:
      - klicker

  frontend_control:
    profiles:
      - full
    image: ghcr.io/uzh-bf/klicker-uzh/frontend-control:v3
    ports:
      - 3003:3000
    networks:
      - klicker

  backend:
    profiles:
      - full
    image: ghcr.io/uzh-bf/klicker-uzh/backend-docker:v3
    environment:
      APP_SECRET: 'abcd'
      COOKIE_DOMAIN: .klicker.com
      CRON_TOKEN: 'abcd'
      DATABASE_URL: 'postgres://klicker-prod:klicker@postgres:5432/klicker-prod'
      NOTIFICATION_SUPPORT_MAIL: 'noone@klicker.com'
      NOTIFICATION_URL: 'noone@klicker.com'
      REDIS_CACHE_HOST: 'redis_cache'
      REDIS_CACHE_PASS: ''
      REDIS_CACHE_PORT: 6379
      REDIS_HOST: 'redis_exec'
      REDIS_PASS: ''
      REDIS_PORT: 6379
      # BLOB_STORAGE_ACCESS_KEY: ''
      # BLOB_STORAGE_ACCOUNT_NAME: ''
      # NOTIFICATION_SECRET: ''
      # REDIS_CACHE_TLS: 'true'
      # REDIS_TLS: 'true'
      # TEAMS_WEBHOOK_URL: ''
      # VAPID_PRIVATE_KEY: ''
      # VAPID_PUBLIC_KEY: ''
    ports:
      - 3000:3000
    networks:
      - klicker

  # main database
  postgres:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_USER: klicker-prod
      POSTGRES_PASSWORD: klicker
      POSTGRES_DB: klicker-prod
    ports:
      - 5432:5432
    networks:
      - klicker
    volumes:
      - klicker_data:/var/lib/postgresql/data
      - ./util/init.sql:/docker-entrypoint-initdb.d/init.sql

  # diff database
  postgres_diff:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_USER: klicker-prod
      POSTGRES_PASSWORD: klicker
      POSTGRES_DB: klicker-prod
    ports:
      - 5433:5432
    networks:
      - klicker
    volumes:
      - klicker_data_diff:/var/lib/postgresql/data
      - ./util/init.sql:/docker-entrypoint-initdb.d/init.sql

  # lti database
  postgres_lti:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_USER: klicker-prod
      POSTGRES_PASSWORD: klicker
      POSTGRES_DB: klicker-prod-lti
    ports:
      - 5434:5432
    networks:
      - klicker
    volumes:
      - klicker_data_lti:/var/lib/postgresql/data

  # hatchet services and services
  hatchet_postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=1000'
    restart: always
    hostname: 'postgres'
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=hatchet
      - POSTGRES_DB=hatchet
    ports:
      - '5435:5432'
    volumes:
      - hatchet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d hatchet -U hatchet']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - klicker

  hatchet_rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '5673:5672' # RabbitMQ
      - '15673:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    volumes:
      - 'hatchet_rabbitmq_data:/var/lib/rabbitmq'
      - 'hatchet_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf' # Configuration file mount
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - klicker

  hatchet_migration:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:latest
    command: /hatchet/hatchet-migrate
    environment:
      DATABASE_URL: 'postgres://hatchet:hatchet@hatchet_postgres:5432/hatchet'
    depends_on:
      hatchet_postgres:
        condition: service_healthy
    networks:
      - klicker

  hatchet_setup_config:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-admin:latest
    command: /hatchet/hatchet-admin quickstart --skip certs --generated-config-dir /hatchet/config --overwrite=false
    environment:
      DATABASE_URL: 'postgres://hatchet:hatchet@hatchet_postgres:5432/hatchet'
      SERVER_TASKQUEUE_RABBITMQ_URL: amqp://user:password@hatchet_rabbitmq:5672/
      SERVER_AUTH_COOKIE_DOMAIN: localhost:8080
      SERVER_AUTH_COOKIE_INSECURE: 't'
      SERVER_GRPC_BIND_ADDRESS: '0.0.0.0'
      SERVER_GRPC_INSECURE: 't'
      SERVER_GRPC_BROADCAST_ADDRESS: localhost:7077
      SERVER_DEFAULT_ENGINE_VERSION: 'V1'
      SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS: hatchet_engine:7077
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
    depends_on:
      hatchet_migration:
        condition: service_completed_successfully
      hatchet_rabbitmq:
        condition: service_healthy
      hatchet_postgres:
        condition: service_healthy
    networks:
      - klicker

  hatchet_engine:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-engine:latest
    command: /hatchet/hatchet-engine --config /hatchet/config
    restart: on-failure
    depends_on:
      hatchet_setup_config:
        condition: service_completed_successfully
      hatchet_migration:
        condition: service_completed_successfully
    ports:
      - '7077:7070'
    environment:
      DATABASE_URL: 'postgres://hatchet:hatchet@hatchet_postgres:5432/hatchet'
      SERVER_GRPC_BIND_ADDRESS: '0.0.0.0'
      SERVER_GRPC_INSECURE: 't'
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
    networks:
      - klicker

  hatchet_dashboard:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:latest
    command: sh ./entrypoint.sh --config /hatchet/config
    ports:
      - 8080:80
    restart: on-failure
    depends_on:
      hatchet_setup_config:
        condition: service_completed_successfully
      hatchet_migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: 'postgres://hatchet:hatchet@hatchet_postgres:5432/hatchet'
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
    networks:
      - klicker

  # redis instance to support live quiz execution
  redis_exec:
    image: docker.io/library/redis:7
    ports:
      - 6379:6379
    networks:
      - klicker
    volumes:
      - redis_data:/data

  # redis instance for page caching and rate limiting
  redis_cache:
    image: docker.io/library/redis:7
    ports:
      - 6380:6379
    networks:
      - klicker

  # fake smtp server for catching email during development
  mailhog:
    image: docker.io/mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - klicker

networks:
  klicker:
    driver: bridge

volumes:
  klicker_data:
  klicker_data_diff:
  klicker_data_lti:
  hatchet_postgres_data:
  hatchet_rabbitmq_data:
  hatchet_rabbitmq.conf:
  hatchet_config:
  hatchet_certs:
  redis_data:
