version: '3'

services:
  react-prod:
    build:
      context: .
      args:
        API_URL: http://localhost:4000/graphql
        APP_FINGERPRINTING: 'true'
        VERSION: docker-compose
    environment:
      API_URL: http://localhost:4000/graphql
      APP_FINGERPRINTING: 'true'
      CACHE_REDIS_HOST: redis
      STATIC_PATH: /
    volumes:
      - './.env:/app/.env:ro'
    ports:
      - 3000:3000
    networks:
      - klicker-prod

networks:
  klicker-prod:
    external:
      name: klicker-api_klicker-prod
