services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: klicker-prod
      POSTGRES_PASSWORD: klicker
      POSTGRES_DB: klicker-prod
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'klicker-prod']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_hatchet:
    image: postgres:15
    environment:
      POSTGRES_USER: hatchet
      POSTGRES_PASSWORD: hatchet
      POSTGRES_DB: hatchet
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'hatchet']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_hatchet_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:7
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_cache_data:/data

  redis_exec:
    image: redis:7
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_exec_data:/data

  hatchet:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-lite:latest
    ports:
      - '8888:8888'
      - '7077:7077'
    environment:
      DATABASE_URL: 'postgresql://hatchet:hatchet@postgres_hatchet:5432/hatchet?sslmode=disable'
      SERVER_AUTH_COOKIE_DOMAIN: 127.0.0.1
      SERVER_AUTH_COOKIE_INSECURE: 't'
      SERVER_GRPC_BIND_ADDRESS: '0.0.0.0'
      SERVER_GRPC_INSECURE: 't'
      SERVER_GRPC_BROADCAST_ADDRESS: 127.0.0.1:7077
      SERVER_GRPC_PORT: '7077'
      SERVER_URL: http://127.0.0.1:8888
      SERVER_AUTH_SET_EMAIL_VERIFIED: 't'
      SERVER_DEFAULT_ENGINE_VERSION: 'V1'
    depends_on:
      postgres_hatchet:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8888/healthz']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  postgres_hatchet_data:
  redis_cache_data:
  redis_exec_data:
