# extend the node alpine base
FROM node:15-alpine

# root application directory
ENV APP_DIR="/app"
ENV NODE_ENV="development"

# install tini
RUN set -x && apk add --no-cache tini

# inject the application dependencies
COPY --chown=1000:0 package.json package-lock.json $APP_DIR/
WORKDIR $APP_DIR

# install packages for the specified environment
RUN set -x \
  && apk add --no-cache --virtual .build-deps alpine-sdk python \
  && npm ci \
  && apk del .build-deps

# switch to the node user (uid 1000)
# non-root as provided by the base image
USER 1000

# run the application in development mode
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npm", "run", "dev", "-L"]

# expose the main application port
EXPOSE 3000

# setup a HEALTHCHECK
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:3000/ || exit 1
