-- AlterTable
ALTER TABLE "Achievement" ADD COLUMN     "descriptionDE" TEXT NOT NULL,
ADD COLUMN     "descriptionEN" TEXT NOT NULL,
ADD COLUMN     "nameDE" TEXT NOT NULL,
ADD COLUMN     "nameEN" TEXT NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL;
