version: "2"
services:
 traefik:
  image: traefik:v2.5
  command:
   #- "--api.insecure=true"
#   - "--log.level=DEBUG"
   - "--providers.docker.exposedbydefault=false"
   - "--entrypoints.websecure.address=:443"
   - "--certificatesresolvers.my-letsencrypt.acme.tlschallenge=true"
   - "--certificatesresolvers.my-letsencrypt.acme.email=acme-admin@your-domain.example"
   - "--certificatesresolvers.my-letsencrypt.acme.storage=/acme.json"
  ports:
   - "443:443"
#   - "8078:8080" # web dashboard, use with api.insecure=true
  volumes:
   - "/data/traefik/acme.json:/acme.json"
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  networks:
   - proxy
  restart: "unless-stopped"

networks:
 proxy:
  driver: bridge
