// Generated by grafana-k6 on 2026-08-22T13:56:22Z
// Chatbot authenticated API smoke/load test.
// Supports an existing participant_token or a normal participant login.
//
// Usage:
//   KLICKER_BASE_URL=https://chat.klicker.stg.df-app.ch \
//     KLICKER_PARTICIPANT_TOKEN=<token> KLICKER_CHATBOT_IDS=<uuid>[,...] \
//     k6 run -e PROFILE=smoke util/load-test/chatbot-auth.js
//   Normal login (credentials should come from the runtime secret store):
//     KLICKER_BASE_URL=https://chat.klicker.stg.df-app.ch \
//       KLICKER_API_URL=https://api.klicker.stg.df-app.ch \
//       KLICKER_PARTICIPANT_USERNAME_OR_EMAIL=<account> \
//       KLICKER_PARTICIPANT_PASSWORD=<password> KLICKER_ALLOW_LOGIN=true \
//       KLICKER_CHATBOT_IDS=<uuid>[,...] \
//       k6 run -e PROFILE=smoke util/load-test/chatbot-auth.js
//   Production also requires KLICKER_ALLOW_PRODUCTION=true.

import { check, sleep } from 'k6'
import http from 'k6/http'
import {
  acquireParticipantToken,
  resolveParticipantAuth,
} from './chatbot-login.js'

const uuidPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

const rawBaseUrl = (__ENV.KLICKER_BASE_URL || '').trim()
const baseUrlMatch = rawBaseUrl.match(/^(https?):\/\/([^/?#]+)\/?$/i)
if (!baseUrlMatch) {
  throw new Error('KLICKER_BASE_URL must be an explicit http(s) URL')
}
const protocol = baseUrlMatch[1].toLowerCase()
const authority = baseUrlMatch[2]
if (authority.includes('@')) {
  throw new Error(
    'KLICKER_BASE_URL must be an origin without path or credentials'
  )
}
if (authority.includes('%')) {
  throw new Error(
    'KLICKER_BASE_URL must not use percent-encoded host characters'
  )
}
const hostPortMatch = authority.startsWith('[')
  ? authority.match(/^(\[[0-9a-f:.]+\])(?::([0-9]+))?$/i)
  : authority.match(/^([^:]+)(?::([0-9]+))?$/)
if (!hostPortMatch) {
  throw new Error(
    'KLICKER_BASE_URL must be an origin without path or credentials'
  )
}
const hasNonAsciiHostnameCharacter = hostPortMatch[1]
  .split('')
  .some((character) => character.charCodeAt(0) > 127)
if (!hostPortMatch[1].startsWith('[') && hasNonAsciiHostnameCharacter) {
  throw new Error('KLICKER_BASE_URL must use an ASCII hostname')
}
const normalizedHostname = hostPortMatch[1].toLowerCase().replace(/\.$/, '')
const port = hostPortMatch[2] || ''
const defaultPort = protocol === 'https' ? '443' : '80'
const baseUrl = `${protocol}://${normalizedHostname}${
  port && port !== defaultPort ? `:${port}` : ''
}`
if (protocol !== 'https') {
  throw new Error('KLICKER_BASE_URL must use https for authenticated requests')
}
if (
  normalizedHostname === 'chat.klicker.uzh.ch' &&
  __ENV.KLICKER_ALLOW_PRODUCTION !== 'true'
) {
  throw new Error(
    'Set KLICKER_ALLOW_PRODUCTION=true for the production chat target'
  )
}
const chatbotIds = (__ENV.KLICKER_CHATBOT_IDS || '')
  .split(',')
  .map((id) => id.trim())
  .filter(Boolean)
if (chatbotIds.length === 0) {
  throw new Error('Set KLICKER_CHATBOT_IDS as comma-separated UUIDs')
}
if (chatbotIds.some((id) => !uuidPattern.test(id))) {
  throw new Error('KLICKER_CHATBOT_IDS must contain UUIDs')
}

const profile = __ENV.PROFILE || 'smoke'
const profiles = {
  smoke: { vus: 1, iterations: chatbotIds.length * 2 },
  light: { vus: 2, duration: '15s' },
  steady: { vus: 3, duration: '30s' },
}

const scenarioConfig = profiles[profile]
if (!scenarioConfig) {
  throw new Error(`Unknown PROFILE '${profile}'. Use smoke|light|steady.`)
}

export const options = {
  discardResponseBodies: true,
  scenarios: {
    auth: Object.assign(
      {
        executor: scenarioConfig.duration
          ? 'constant-vus'
          : 'shared-iterations',
      },
      scenarioConfig
    ),
  },
  thresholds: {
    checks: ['rate==1'],
    http_req_failed: ['rate<0.01'],
    http_req_duration: ['p(95)<1000', 'p(99)<2000'],
  },
}

const endpoints = chatbotIds.flatMap((id) => [
  {
    name: id.slice(0, 8),
    path: `/api/chatbots/${id}/disclaimer`,
    expected: 200,
  },
  { name: id.slice(0, 8), path: `/api/chatbots/${id}/credits`, expected: 200 },
])

const participantAuth = resolveParticipantAuth(rawBaseUrl, __ENV)

export function setup() {
  return { participantToken: acquireParticipantToken(participantAuth) }
}

export default function (setupData) {
  const token = setupData?.participantToken || ''
  if (token.length === 0) {
    throw new Error('Participant login did not provide a session token')
  }

  const ep = endpoints[__ITER % endpoints.length]
  const res = http.get(`${baseUrl}${ep.path}`, {
    cookies: { participant_token: token },
    redirects: 0,
  })
  check(res, {
    [`${ep.name} ${ep.path} authenticated -> ${ep.expected}`]: (r) =>
      r.status === ep.expected,
  })
  if (scenarioConfig.duration) sleep(1)
}
