// Generated by grafana-k6 on 2026-08-22T13:56:22Z
// Chat turn load tester with hard cost cap. Sends real POST requests to
// /api/chatbots/[chatbotId]/chat, which triggers MCP retrieval + provider
// streaming + message persistence. Each iteration consumes credits and
// creates thread/message records.
//
// Safety: MAX_TURNS defaults to 2 and must be an integer from 1 through 10.
// Every iteration is a real side effect and requires explicit acknowledgement.
//
// Usage:
//   KLICKER_BASE_URL=https://chat.klicker.stg.df-app.ch \
//     KLICKER_PARTICIPANT_TOKEN=<token> KLICKER_CHATBOT_ID=<uuid> \
//     KLICKER_SELECTED_MODEL=<model-id> MAX_TURNS=2 \
//     KLICKER_ALLOW_SIDE_EFFECTS=true k6 run util/load-test/chatbot-turn.js
//   Normal login (credentials should come from the runtime secret store):
//     KLICKER_API_URL=https://api.klicker.stg.df-app.ch \
//       KLICKER_PARTICIPANT_USERNAME_OR_EMAIL=<account> \
//       KLICKER_PARTICIPANT_PASSWORD=<password> KLICKER_ALLOW_LOGIN=true \
//       KLICKER_ALLOW_SIDE_EFFECTS=true KLICKER_CHATBOT_ID=<uuid> \
//       KLICKER_SELECTED_MODEL=<model-id> k6 run util/load-test/chatbot-turn.js

import { check } from 'k6'
import exec from 'k6/execution'
import http from 'k6/http'
import {
  acquireParticipantToken,
  resolveParticipantAuth,
} from './chatbot-login.js'

const uuidPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

const rawBaseUrl = (__ENV.KLICKER_BASE_URL || '').trim()
const baseUrlMatch = rawBaseUrl.match(/^(https?):\/\/([^/?#]+)\/?$/i)
if (!baseUrlMatch) {
  throw new Error('KLICKER_BASE_URL must be an explicit http(s) URL')
}
const protocol = baseUrlMatch[1].toLowerCase()
const authority = baseUrlMatch[2]
if (authority.includes('@')) {
  throw new Error(
    'KLICKER_BASE_URL must be an origin without path or credentials'
  )
}
if (authority.includes('%')) {
  throw new Error(
    'KLICKER_BASE_URL must not use percent-encoded host characters'
  )
}
const hostPortMatch = authority.startsWith('[')
  ? authority.match(/^(\[[0-9a-f:.]+\])(?::([0-9]+))?$/i)
  : authority.match(/^([^:]+)(?::([0-9]+))?$/)
if (!hostPortMatch) {
  throw new Error(
    'KLICKER_BASE_URL must be an origin without path or credentials'
  )
}
const hasNonAsciiHostnameCharacter = hostPortMatch[1]
  .split('')
  .some((character) => character.charCodeAt(0) > 127)
if (!hostPortMatch[1].startsWith('[') && hasNonAsciiHostnameCharacter) {
  throw new Error('KLICKER_BASE_URL must use an ASCII hostname')
}
const normalizedHostname = hostPortMatch[1].toLowerCase().replace(/\.$/, '')
const port = hostPortMatch[2] || ''
const defaultPort = protocol === 'https' ? '443' : '80'
const baseUrl = `${protocol}://${normalizedHostname}${
  port && port !== defaultPort ? `:${port}` : ''
}`
if (protocol !== 'https') {
  throw new Error('KLICKER_BASE_URL must use https for authenticated requests')
}
if (
  normalizedHostname === 'chat.klicker.uzh.ch' &&
  __ENV.KLICKER_ALLOW_PRODUCTION !== 'true'
) {
  throw new Error(
    'Set KLICKER_ALLOW_PRODUCTION=true for the production chat target'
  )
}
if (__ENV.KLICKER_ALLOW_SIDE_EFFECTS !== 'true') {
  throw new Error(
    'Set KLICKER_ALLOW_SIDE_EFFECTS=true to acknowledge chat-turn writes and provider cost'
  )
}
const chatbotId = (__ENV.KLICKER_CHATBOT_ID || '').trim()
if (!uuidPattern.test(chatbotId)) {
  throw new Error('KLICKER_CHATBOT_ID must be a UUID')
}

const selectedModel = (__ENV.KLICKER_SELECTED_MODEL || '').trim()
if (!selectedModel) {
  throw new Error(
    'KLICKER_SELECTED_MODEL is required (e.g. gpt-4o-mini or the model ID from credits)'
  )
}

const maxTurnsInput = __ENV.MAX_TURNS || '2'
const maxTurns = Number(maxTurnsInput)
if (!Number.isInteger(maxTurns) || maxTurns < 1 || maxTurns > 10) {
  throw new Error('MAX_TURNS must be an integer from 1 through 10')
}
const question = __ENV.QUESTION || 'What topics are covered?'
const participantAuth = resolveParticipantAuth(rawBaseUrl, __ENV)

export const options = {
  scenarios: {
    turns: {
      executor: 'per-vu-iterations',
      vus: 1,
      iterations: maxTurns,
      maxDuration: '5m',
    },
  },
  thresholds: {
    checks: ['rate>=0.9'],
    'http_req_duration{name:chat-turn}': ['p(95)<30000'],
  },
}

export function setup() {
  return { participantToken: acquireParticipantToken(participantAuth) }
}

export default function (setupData) {
  if (
    !Number.isInteger(exec.scenario.iterationInTest) ||
    exec.scenario.iterationInTest >= maxTurns
  ) {
    return
  }

  const token = setupData?.participantToken || ''
  if (token.length === 0) {
    throw new Error('Participant login did not provide a session token')
  }

  const assistantMessageId = crypto.randomUUID()
  const payload = JSON.stringify({
    messages: [{ id: crypto.randomUUID(), role: 'user', content: question }],
    threadId: null,
    selectedModel,
    selectedMode: 'tutor',
    reasoningEffort: 'none',
    parentId: null,
    assistantMessageId,
    images: [],
  })

  const res = http.post(`${baseUrl}/api/chatbots/${chatbotId}/chat`, payload, {
    cookies: { participant_token: token },
    headers: { 'Content-Type': 'application/json' },
    tags: { name: 'chat-turn' },
    timeout: '90s',
    redirects: 0,
  })

  // The endpoint answers with an AI SDK SSE stream, not JSON. Validate the
  // protocol shape only: a finish event must arrive and no error event may
  // appear. Message content is never read or persisted by this script.
  const rawBody = res.body || ''
  let sawFinishEvent = false
  let sawStreamErrorEvent = false
  for (const line of rawBody.split('\n')) {
    if (!line.startsWith('data: ')) continue
    const eventPayload = line.substring(6).trim()
    if (eventPayload === '[DONE]' || eventPayload.length === 0) continue
    try {
      const event = JSON.parse(eventPayload)
      if (event && event.type === 'finish') sawFinishEvent = true
      if (event && event.type === 'error') sawStreamErrorEvent = true
    } catch {
      // ignore non-JSON keepalive lines
    }
  }

  check(res, {
    'chat turn returned success': (r) => r.status >= 200 && r.status < 300,
    'chat turn streamed finish event': () => sawFinishEvent,
    'chat turn stream had no error event': () => !sawStreamErrorEvent,
  })
}
