// Generated by grafana-k6 on 2026-08-22T20:20:47Z
// Shared participant authentication for the chatbot k6 scripts.

import http from 'k6/http'

const LOGIN_OPERATION_HASH =
  '8e3ea39b64b0408ac5e307fc0778e8ad583268eec5569d98873ddec90598c384'

const expectedApiHostByChatHost = {
  'chat.klicker.stg.df-app.ch': 'api.klicker.stg.df-app.ch',
  'chat.klicker.uzh.ch': 'backend-sls.klicker.uzh.ch',
}

function parseOrigin(rawUrl, variableName) {
  const value = (rawUrl || '').trim()
  const match = value.match(/^(https?):\/\/([^/?#]+)\/?$/i)
  if (!match) {
    throw new Error(`${variableName} must be an explicit http(s) origin`)
  }

  const protocol = match[1].toLowerCase()
  const authority = match[2]
  if (authority.includes('@') || authority.includes('%')) {
    throw new Error(
      `${variableName} must be an origin without credentials or encoded host characters`
    )
  }

  const hostPortMatch = authority.startsWith('[')
    ? authority.match(/^(\[[0-9a-f:.]+\])(?::([0-9]+))?$/i)
    : authority.match(/^([^:]+)(?::([0-9]+))?$/)
  if (!hostPortMatch) {
    throw new Error(`${variableName} must be an origin without a path`)
  }

  const hostname = hostPortMatch[1]
  const hasNonAsciiHostnameCharacter = hostname
    .split('')
    .some((character) => character.charCodeAt(0) > 127)
  if (!hostname.startsWith('[') && hasNonAsciiHostnameCharacter) {
    throw new Error(`${variableName} must use an ASCII hostname`)
  }

  const normalizedHostname = hostname.toLowerCase().replace(/\.$/, '')
  const port = hostPortMatch[2] || ''
  const defaultPort = protocol === 'https' ? '443' : '80'
  const origin = `${protocol}://${normalizedHostname}${
    port && port !== defaultPort ? `:${port}` : ''
  }`

  return { protocol, hostname: normalizedHostname, port, origin }
}

function isProductionHostname(hostname) {
  return hostname === 'klicker.uzh.ch' || hostname.endsWith('.klicker.uzh.ch')
}

export function resolveParticipantAuth(rawBaseUrl, env) {
  const token = (env.KLICKER_PARTICIPANT_TOKEN || '').trim()
  const usernameOrEmail = (
    env.KLICKER_PARTICIPANT_USERNAME_OR_EMAIL || ''
  ).trim()
  const password = env.KLICKER_PARTICIPANT_PASSWORD || ''
  const apiUrl = (env.KLICKER_API_URL || '').trim()
  const hasLoginAcknowledgement = env.KLICKER_ALLOW_LOGIN !== undefined

  const hasToken = token.length > 0
  const hasLoginInput =
    usernameOrEmail.length > 0 ||
    password.length > 0 ||
    apiUrl.length > 0 ||
    hasLoginAcknowledgement

  if (hasToken && hasLoginInput) {
    throw new Error(
      'Use either KLICKER_PARTICIPANT_TOKEN or the normal-login variables, not both'
    )
  }

  if (hasToken) {
    const chatOrigin = parseOrigin(rawBaseUrl, 'KLICKER_BASE_URL')
    if (chatOrigin.protocol !== 'https') {
      throw new Error('Participant-token mode requires HTTPS chat origins')
    }
    if (chatOrigin.port && chatOrigin.port !== '443') {
      throw new Error(
        'Participant-token mode requires a canonical HTTPS chat origin'
      )
    }
    if (!Object.hasOwn(expectedApiHostByChatHost, chatOrigin.hostname)) {
      throw new Error(
        'Participant-token mode is limited to the known STG or PRD chat origins'
      )
    }
    if (
      isProductionHostname(chatOrigin.hostname) &&
      env.KLICKER_ALLOW_PRODUCTION !== 'true'
    ) {
      throw new Error(
        'Set KLICKER_ALLOW_PRODUCTION=true for token mode against the production target'
      )
    }
    return { mode: 'token', token }
  }

  if (
    usernameOrEmail.length === 0 ||
    password.length === 0 ||
    apiUrl.length === 0
  ) {
    throw new Error(
      'Set KLICKER_PARTICIPANT_TOKEN, or set KLICKER_PARTICIPANT_USERNAME_OR_EMAIL, KLICKER_PARTICIPANT_PASSWORD, and KLICKER_API_URL'
    )
  }

  if (env.KLICKER_ALLOW_LOGIN !== 'true') {
    throw new Error(
      'Set KLICKER_ALLOW_LOGIN=true to acknowledge the normal-login lastLoginAt write'
    )
  }

  const chatOrigin = parseOrigin(rawBaseUrl, 'KLICKER_BASE_URL')
  const apiOrigin = parseOrigin(apiUrl, 'KLICKER_API_URL')
  if (chatOrigin.protocol !== 'https' || apiOrigin.protocol !== 'https') {
    throw new Error('Normal login requires HTTPS chat and API origins')
  }
  if (
    (chatOrigin.port && chatOrigin.port !== '443') ||
    (apiOrigin.port && apiOrigin.port !== '443')
  ) {
    throw new Error('Normal login requires canonical HTTPS origins')
  }

  const expectedApiHostname = expectedApiHostByChatHost[chatOrigin.hostname]
  if (!expectedApiHostname || apiOrigin.hostname !== expectedApiHostname) {
    throw new Error(
      'Normal login is limited to the known STG or PRD chat/API origin pair'
    )
  }

  if (
    (isProductionHostname(chatOrigin.hostname) ||
      isProductionHostname(apiOrigin.hostname)) &&
    env.KLICKER_ALLOW_PRODUCTION !== 'true'
  ) {
    throw new Error(
      'Set KLICKER_ALLOW_PRODUCTION=true for normal login against the production target'
    )
  }

  return {
    mode: 'login',
    usernameOrEmail,
    password,
    apiOrigin: apiOrigin.origin,
  }
}

export function acquireParticipantToken(auth) {
  if (auth.mode === 'token') return auth.token

  const response = http.post(
    `${auth.apiOrigin}/api/graphql`,
    JSON.stringify({
      operationName: 'LoginParticipant',
      variables: {
        usernameOrEmail: auth.usernameOrEmail,
        password: auth.password,
      },
      extensions: {
        persistedQuery: {
          version: 1,
          sha256Hash: LOGIN_OPERATION_HASH,
        },
      },
    }),
    {
      headers: {
        'Content-Type': 'application/json',
        'x-graphql-yoga-csrf': 'true',
      },
      redirects: 0,
      tags: { name: 'participant-login' },
    }
  )

  const cookies = response.cookies?.participant_token || []
  const participantToken = cookies[0]?.value || ''
  if (response.status !== 200 || participantToken.trim().length === 0) {
    throw new Error(
      'Normal participant login failed: expected HTTP 200 and a participant_token cookie'
    )
  }

  return participantToken
}
