// Generated by grafana-k6 on 2026-08-22T13:56:22Z
// Chatbot anonymous HTTP load/performance test for KlickerUZH.
// Tests public model GET, native deep-link redirect, disclaimer 401, credits 401.
//
// Usage:
//   KLICKER_BASE_URL=https://chat.klicker.stg.df-app.ch \
//     KLICKER_CHATBOT_IDS=<uuid>[,<uuid>...] k6 run util/load-test/chatbot-http.js
//   Production also requires KLICKER_ALLOW_PRODUCTION=true.
//   Profile override: k6 run --vus=5 --duration=30s util/load-test/chatbot-http.js

import { check, sleep } from 'k6'
import exec from 'k6/execution'
import http from 'k6/http'

export const options = {
  discardResponseBodies: true,
  scenarios: {
    smoke: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 8,
      startTime: '0s',
      maxDuration: '15s',
    },
    steady: {
      executor: 'constant-vus',
      vus: 2,
      duration: '30s',
      startTime: '20s',
    },
    burst: {
      executor: 'constant-vus',
      vus: 3,
      duration: '10s',
      startTime: '55s',
    },
  },
  thresholds: {
    checks: ['rate==1'],
    dropped_iterations: ['count==0'],
    http_req_duration: ['p(99)<2000'],
  },
}

const rawBaseUrl = (__ENV.KLICKER_BASE_URL || '').trim()
const baseUrlMatch = rawBaseUrl.match(/^(https?):\/\/([^/?#]+)\/?$/i)
if (!baseUrlMatch) {
  throw new Error('KLICKER_BASE_URL must be an explicit http(s) URL')
}
const protocol = baseUrlMatch[1].toLowerCase()
const authority = baseUrlMatch[2]
if (authority.includes('@')) {
  throw new Error(
    'KLICKER_BASE_URL must be an origin without path or credentials'
  )
}
const hostPortMatch = authority.startsWith('[')
  ? authority.match(/^(\[[0-9a-f:.]+\])(?::([0-9]+))?$/i)
  : authority.match(/^([^:]+)(?::([0-9]+))?$/)
if (!hostPortMatch) {
  throw new Error(
    'KLICKER_BASE_URL must be an origin without path or credentials'
  )
}
const normalizedHostname = hostPortMatch[1].toLowerCase().replace(/\.$/, '')
const port = hostPortMatch[2] || ''
const defaultPort = protocol === 'https' ? '443' : '80'
const normalizedPort = port || defaultPort
const baseUrl = `${protocol}://${normalizedHostname}${
  port && port !== defaultPort ? `:${port}` : ''
}`
if (
  protocol === 'https' &&
  normalizedHostname === 'chat.klicker.uzh.ch' &&
  normalizedPort === '443' &&
  __ENV.KLICKER_ALLOW_PRODUCTION !== 'true'
) {
  throw new Error(
    'Set KLICKER_ALLOW_PRODUCTION=true for the production chat target'
  )
}
const chatbotIds = (__ENV.KLICKER_CHATBOT_IDS || '')
  .split(',')
  .map((id) => id.trim())
  .filter(Boolean)
if (chatbotIds.length === 0) {
  throw new Error('Set KLICKER_CHATBOT_IDS as comma-separated UUIDs')
}

const endpoints = chatbotIds.flatMap((id) => [
  {
    name: id.slice(0, 8),
    path: `/api/chatbots/${id}`,
    expected: 200,
    tag: 'model',
  },
  { name: id.slice(0, 8), path: `/${id}`, expected: 307, tag: 'deep-link' },
  {
    name: id.slice(0, 8),
    path: `/api/chatbots/${id}/disclaimer`,
    expected: 401,
    tag: 'disclaimer',
  },
  {
    name: id.slice(0, 8),
    path: `/api/chatbots/${id}/credits`,
    expected: 401,
    tag: 'credits',
  },
])

// Tag per-endpoint latency thresholds dynamically
for (let i = 0; i < endpoints.length; i++) {
  const key = endpoints[i].tag
  options.thresholds[`http_req_duration{endpoint:${key}}`] = ['p(95)<1500']
}

export default function () {
  const ep = endpoints[exec.scenario.iterationInTest % endpoints.length]
  const res = http.get(`${baseUrl}${ep.path}`, {
    redirects: 0,
    tags: { endpoint: ep.tag, chatbot: ep.name },
  })
  check(res, {
    [`${ep.name} ${ep.path} -> ${ep.expected}`]: (r) =>
      r.status === ep.expected,
  })
  if (exec.scenario.name !== 'smoke') sleep(1)
}
