apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-frontend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  SENTRY_AUTH_TOKEN: {{ .Values.analytics.sentry.authToken | quote }}
