// flow-typed signature: 75870be90bd1c3b22e3325aebc63b32f
// flow-typed version: <<STUB>>/accepts_v1.3.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'accepts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'accepts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'accepts/index' {
  declare module.exports: $Exports<'accepts'>;
}
declare module 'accepts/index.js' {
  declare module.exports: $Exports<'accepts'>;
}
