// flow-typed signature: b96d1cad8d602a9f517650b24b848b6f
// flow-typed version: <<STUB>>/logrocket_v0.5.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logrocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logrocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logrocket/dist/build.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logrocket/dist/build.umd.js' {
  declare module.exports: $Exports<'logrocket/dist/build.umd'>;
}
