// flow-typed signature: ca0fc00aa63da9a9c64378b44e8698d1
// flow-typed version: <<STUB>>/prosemirror-view_v0.24.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prosemirror-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prosemirror-view/dist/index' {
  declare module.exports: any;
}

declare module 'prosemirror-view/rollup.config' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/browser' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/capturekeys' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/clipboard' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/decoration' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/dom' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/domchange' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/domcoords' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/domobserver' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/index' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/input' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/selection' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/trackmappings' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/viewdesc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prosemirror-view/dist/index.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/index'>;
}
declare module 'prosemirror-view/rollup.config.js' {
  declare module.exports: $Exports<'prosemirror-view/rollup.config'>;
}
declare module 'prosemirror-view/src/browser.js' {
  declare module.exports: $Exports<'prosemirror-view/src/browser'>;
}
declare module 'prosemirror-view/src/capturekeys.js' {
  declare module.exports: $Exports<'prosemirror-view/src/capturekeys'>;
}
declare module 'prosemirror-view/src/clipboard.js' {
  declare module.exports: $Exports<'prosemirror-view/src/clipboard'>;
}
declare module 'prosemirror-view/src/decoration.js' {
  declare module.exports: $Exports<'prosemirror-view/src/decoration'>;
}
declare module 'prosemirror-view/src/dom.js' {
  declare module.exports: $Exports<'prosemirror-view/src/dom'>;
}
declare module 'prosemirror-view/src/domchange.js' {
  declare module.exports: $Exports<'prosemirror-view/src/domchange'>;
}
declare module 'prosemirror-view/src/domcoords.js' {
  declare module.exports: $Exports<'prosemirror-view/src/domcoords'>;
}
declare module 'prosemirror-view/src/domobserver.js' {
  declare module.exports: $Exports<'prosemirror-view/src/domobserver'>;
}
declare module 'prosemirror-view/src/index.js' {
  declare module.exports: $Exports<'prosemirror-view/src/index'>;
}
declare module 'prosemirror-view/src/input.js' {
  declare module.exports: $Exports<'prosemirror-view/src/input'>;
}
declare module 'prosemirror-view/src/selection.js' {
  declare module.exports: $Exports<'prosemirror-view/src/selection'>;
}
declare module 'prosemirror-view/src/trackmappings.js' {
  declare module.exports: $Exports<'prosemirror-view/src/trackmappings'>;
}
declare module 'prosemirror-view/src/viewdesc.js' {
  declare module.exports: $Exports<'prosemirror-view/src/viewdesc'>;
}
