// flow-typed signature: 6a4d0ce4f8d50811f08496688ba16686
// flow-typed version: <<STUB>>/prosemirror-schema-basic_v0.22.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-schema-basic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prosemirror-schema-basic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prosemirror-schema-basic/dist/schema-basic' {
  declare module.exports: any;
}

declare module 'prosemirror-schema-basic/src/schema-basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prosemirror-schema-basic/dist/schema-basic.js' {
  declare module.exports: $Exports<'prosemirror-schema-basic/dist/schema-basic'>;
}
declare module 'prosemirror-schema-basic/src/schema-basic.js' {
  declare module.exports: $Exports<'prosemirror-schema-basic/src/schema-basic'>;
}
