// flow-typed signature: 1db06252b6c1fdb1a04b9261e0671375
// flow-typed version: <<STUB>>/react-apollo_v^1.4.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/examples/ssr/client/main' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/ssr/imports/app' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/ssr/imports/schema' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/ssr/imports/tests/chromedriver' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/ssr/server/main' {
  declare module.exports: any;
}

declare module 'react-apollo/examples/ssr/tests/ssr' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/invariant_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.pick_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/object-assign_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/redux_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/browser' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/index' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/queryRecycler' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/react-apollo.browser.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/react-apollo.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/server' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/test-utils' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/types' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/withApollo' {
  declare module.exports: any;
}

declare module 'react-apollo/preprocessor' {
  declare module.exports: any;
}

declare module 'react-apollo/rollup.browser.config' {
  declare module.exports: any;
}

declare module 'react-apollo/rollup.config' {
  declare module.exports: any;
}

declare module 'react-apollo/rollup.test-utils.config' {
  declare module.exports: any;
}

declare module 'react-apollo/scripts/filesize' {
  declare module.exports: any;
}

declare module 'react-apollo/scripts/gzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/examples/ssr/client/main.js' {
  declare module.exports: $Exports<'react-apollo/examples/ssr/client/main'>;
}
declare module 'react-apollo/examples/ssr/imports/app.js' {
  declare module.exports: $Exports<'react-apollo/examples/ssr/imports/app'>;
}
declare module 'react-apollo/examples/ssr/imports/schema.js' {
  declare module.exports: $Exports<'react-apollo/examples/ssr/imports/schema'>;
}
declare module 'react-apollo/examples/ssr/imports/tests/chromedriver.js' {
  declare module.exports: $Exports<'react-apollo/examples/ssr/imports/tests/chromedriver'>;
}
declare module 'react-apollo/examples/ssr/server/main.js' {
  declare module.exports: $Exports<'react-apollo/examples/ssr/server/main'>;
}
declare module 'react-apollo/examples/ssr/tests/ssr.js' {
  declare module.exports: $Exports<'react-apollo/examples/ssr/tests/ssr'>;
}
declare module 'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/invariant_v2.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/invariant_v2.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.pick_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.pick_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/object-assign_v4.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/object-assign_v4.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/redux_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/redux_vx.x.x'>;
}
declare module 'react-apollo/lib/ApolloProvider.js' {
  declare module.exports: $Exports<'react-apollo/lib/ApolloProvider'>;
}
declare module 'react-apollo/lib/browser.js' {
  declare module.exports: $Exports<'react-apollo/lib/browser'>;
}
declare module 'react-apollo/lib/graphql.js' {
  declare module.exports: $Exports<'react-apollo/lib/graphql'>;
}
declare module 'react-apollo/lib/index.js' {
  declare module.exports: $Exports<'react-apollo/lib/index'>;
}
declare module 'react-apollo/lib/parser.js' {
  declare module.exports: $Exports<'react-apollo/lib/parser'>;
}
declare module 'react-apollo/lib/queryRecycler.js' {
  declare module.exports: $Exports<'react-apollo/lib/queryRecycler'>;
}
declare module 'react-apollo/lib/react-apollo.browser.umd.js' {
  declare module.exports: $Exports<'react-apollo/lib/react-apollo.browser.umd'>;
}
declare module 'react-apollo/lib/react-apollo.umd.js' {
  declare module.exports: $Exports<'react-apollo/lib/react-apollo.umd'>;
}
declare module 'react-apollo/lib/server.js' {
  declare module.exports: $Exports<'react-apollo/lib/server'>;
}
declare module 'react-apollo/lib/shallowEqual.js' {
  declare module.exports: $Exports<'react-apollo/lib/shallowEqual'>;
}
declare module 'react-apollo/lib/test-utils.js' {
  declare module.exports: $Exports<'react-apollo/lib/test-utils'>;
}
declare module 'react-apollo/lib/types.js' {
  declare module.exports: $Exports<'react-apollo/lib/types'>;
}
declare module 'react-apollo/lib/withApollo.js' {
  declare module.exports: $Exports<'react-apollo/lib/withApollo'>;
}
declare module 'react-apollo/preprocessor.js' {
  declare module.exports: $Exports<'react-apollo/preprocessor'>;
}
declare module 'react-apollo/rollup.browser.config.js' {
  declare module.exports: $Exports<'react-apollo/rollup.browser.config'>;
}
declare module 'react-apollo/rollup.config.js' {
  declare module.exports: $Exports<'react-apollo/rollup.config'>;
}
declare module 'react-apollo/rollup.test-utils.config.js' {
  declare module.exports: $Exports<'react-apollo/rollup.test-utils.config'>;
}
declare module 'react-apollo/scripts/filesize.js' {
  declare module.exports: $Exports<'react-apollo/scripts/filesize'>;
}
declare module 'react-apollo/scripts/gzip.js' {
  declare module.exports: $Exports<'react-apollo/scripts/gzip'>;
}
