// flow-typed signature: 72cee840c33a46cbba333ff2cc332ac2
// flow-typed version: <<STUB>>/storybook-addon-intl_v2.1.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-intl/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/manager/components/LocaleButton/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/manager/components/LocaleButton/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/manager/containers/LocalePanel/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/manager/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/preview/containers/WithIntl/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/preview/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/shared/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/dist/utils' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/scripts/build' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/scripts/installPeerDependencies' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/__tests__/utils' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/components/LocaleButton/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/components/LocaleButton/__tests__/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/components/LocaleButton/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/components/LocaleButton/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/containers/LocalePanel/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/containers/LocalePanel/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/manager/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/preview/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/preview/containers/WithIntl/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/preview/containers/WithIntl/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/preview/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/shared/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-intl/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-intl/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/index'>;
}
declare module 'storybook-addon-intl/dist/manager/components/LocaleButton/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/manager/components/LocaleButton/index'>;
}
declare module 'storybook-addon-intl/dist/manager/components/LocaleButton/style.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/manager/components/LocaleButton/style'>;
}
declare module 'storybook-addon-intl/dist/manager/containers/LocalePanel/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/manager/containers/LocalePanel/index'>;
}
declare module 'storybook-addon-intl/dist/manager/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/manager/index'>;
}
declare module 'storybook-addon-intl/dist/preview/containers/WithIntl/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/preview/containers/WithIntl/index'>;
}
declare module 'storybook-addon-intl/dist/preview/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/preview/index'>;
}
declare module 'storybook-addon-intl/dist/shared/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/shared/index'>;
}
declare module 'storybook-addon-intl/dist/utils.js' {
  declare module.exports: $Exports<'storybook-addon-intl/dist/utils'>;
}
declare module 'storybook-addon-intl/register.js' {
  declare module.exports: $Exports<'storybook-addon-intl/register'>;
}
declare module 'storybook-addon-intl/scripts/build.js' {
  declare module.exports: $Exports<'storybook-addon-intl/scripts/build'>;
}
declare module 'storybook-addon-intl/scripts/installPeerDependencies.js' {
  declare module.exports: $Exports<'storybook-addon-intl/scripts/installPeerDependencies'>;
}
declare module 'storybook-addon-intl/src/__tests__/utils.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/__tests__/utils'>;
}
declare module 'storybook-addon-intl/src/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/index'>;
}
declare module 'storybook-addon-intl/src/manager/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/__tests__/index'>;
}
declare module 'storybook-addon-intl/src/manager/components/LocaleButton/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/components/LocaleButton/__tests__/index'>;
}
declare module 'storybook-addon-intl/src/manager/components/LocaleButton/__tests__/style.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/components/LocaleButton/__tests__/style'>;
}
declare module 'storybook-addon-intl/src/manager/components/LocaleButton/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/components/LocaleButton/index'>;
}
declare module 'storybook-addon-intl/src/manager/components/LocaleButton/style.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/components/LocaleButton/style'>;
}
declare module 'storybook-addon-intl/src/manager/containers/LocalePanel/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/containers/LocalePanel/__tests__/index'>;
}
declare module 'storybook-addon-intl/src/manager/containers/LocalePanel/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/containers/LocalePanel/index'>;
}
declare module 'storybook-addon-intl/src/manager/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/manager/index'>;
}
declare module 'storybook-addon-intl/src/preview/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/preview/__tests__/index'>;
}
declare module 'storybook-addon-intl/src/preview/containers/WithIntl/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/preview/containers/WithIntl/__tests__/index'>;
}
declare module 'storybook-addon-intl/src/preview/containers/WithIntl/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/preview/containers/WithIntl/index'>;
}
declare module 'storybook-addon-intl/src/preview/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/preview/index'>;
}
declare module 'storybook-addon-intl/src/shared/index.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/shared/index'>;
}
declare module 'storybook-addon-intl/src/utils.js' {
  declare module.exports: $Exports<'storybook-addon-intl/src/utils'>;
}
