repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: klicker-v2-prod
    namespace: klicker-v2-prod
    createNamespace: true
    chart: ../charts/klicker-uzh-v2
    version: '{{ env "CHART_VERSION" | default "0.1.0" }}'
    installed: true
    kubeContext: klicker-k8scbfdbd7c
    values:
      - values.yaml
      - .values-SECRET.yaml
  - name: hatchet-prod
    namespace: klicker-v2-prod
    createNamespace: true
    chart: hatchet/hatchet-ha
    version: '{{ env "HATCHET_CHART_VERSION" | default "0.9.2" }}'
    installed: false
    kubeContext: klicker-k8scbfdbd7c
    values:
      - values-hatchet.yaml
      - .values-hatchet-SECRET.yaml
