repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: klicker-v2-prod
    namespace: klicker-v2-prod
    createNamespace: true
    chart: ../charts/klicker-uzh-v2
    version: '{{ env "CHART_VERSION" | default "0.1.0" }}'
    installed: true
    kubeContext: klicker-k8scbfdbd7c
    values:
      - values.yaml
      - teamsWebhookUrl: '{{ requiredEnv "TEAMS_WEBHOOK_URL" }}'

        appSecret: '{{ requiredEnv "APP_SECRET" }}'

        blobStorage:
          accountName: '{{ requiredEnv "BLOB_STORAGE_ACCOUNT_NAME" }}'
          accessKey: '{{ requiredEnv "BLOB_STORAGE_ACCESS_KEY" }}'

        migration:
          secret: '{{ requiredEnv "MIGRATION_SECRET" }}'
          mongo:
            connectionString: '{{ requiredEnv "MIGRATION_MONGO_CONNECTION_STRING" }}'
          serviceBus:
            connectionString: '{{ requiredEnv "MIGRATION_SERVICE_BUS_CONNECTION_STRING" }}'
            queueName: '{{ requiredEnv "MIGRATION_SERVICE_BUS_QUEUE_NAME" }}'

        listmonk:
          url: '{{ requiredEnv "LISTMONK_URL" }}'
          username: '{{ requiredEnv "LISTMONK_USER" }}'
          password: '{{ requiredEnv "LISTMONK_PASS" }}'
          templates:
            emailNotFound: '{{ requiredEnv "LISTMONK_TEMPLATE_EMAIL_NOT_FOUND" }}'
            migrationRequest: '{{ requiredEnv "LISTMONK_TEMPLATE_MIGRATION_REQUEST" }}'

        cron:
          token: '{{ requiredEnv "CRON_TOKEN" }}'

        eduId:
          clientSecret: '{{ requiredEnv "EDUID_CLIENT_SECRET" }}'

        auth:
          replicaCount: 1
          image:
            tag: '{{ requiredEnv "APP_VERSION" }}'

        frontendPWA:
          image:
            tag: '{{ requiredEnv "APP_VERSION" }}'

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN_PWA" }}'

        frontendManage:
          image:
            tag: '{{ requiredEnv "APP_VERSION" }}'

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN_MANAGE" }}'

        frontendControl:
          image:
            tag: '{{ requiredEnv "APP_VERSION" }}'

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN_CONTROL" }}'


        backendGraphql:
          image:
            tag: '{{ requiredEnv "APP_VERSION" }}'

          apiDomain: '{{ requiredEnv "API_DOMAIN" }}'
          cookieDomain: '{{ requiredEnv "COOKIE_DOMAIN" }}'
          databaseUrl: '{{ requiredEnv "DATABASE_URL" }}'

          notifications:
            url: '{{ requiredEnv "NOTIFICATION_URL" }}'
            secret: '{{ requiredEnv "NOTIFICATION_SECRET" }}'
            supportEmail: '{{ requiredEnv "NOTIFICATION_SUPPORT_EMAIL" }}'

          vapid:
            publicKey: '{{ requiredEnv "VAPID_PUBLIC_KEY" }}'
            privateKey: '{{ requiredEnv "VAPID_PRIVATE_KEY" }}'

          redisCache:
            host: klicker-v2-prod-redis-master
            port: 6379
            tls: false
            pass: ''

          redisExec:
            host: '{{ requiredEnv "REDIS_HOST" }}'
            port: '{{ requiredEnv "REDIS_PORT" }}'
            tls: '{{ requiredEnv "REDIS_TLS" }}'
            pass: '{{ requiredEnv "REDIS_PASS" }}'

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN" }}'

        lti:
          clientId: '{{ requiredEnv "LTI_CLIENT_ID" }}'
          redirectURL: '{{ requiredEnv "LTI_REDIRECT_URL" }}'
          cookieDomain: '{{ requiredEnv "COOKIE_DOMAIN" }}'
          encryptionKey: '{{ requiredEnv "APP_SECRET" }}'

          db:
            type: postgres
            host: '{{ requiredEnv "LTI_DB_HOST" }}'
            port: '{{ requiredEnv "LTI_DB_PORT" }}'
            name: '{{ requiredEnv "LTI_DB_NAME" }}'
            username: '{{ requiredEnv "LTI_DB_USER" }}'
            password: '{{ requiredEnv "LTI_DB_PASS" }}'
