heartbeats:
  dailyGroupScores: https://betteruptime.com/api/v1/heartbeat/gmMi315s2532oozauJa18ckx

global:
  appOrigins:
    api: 'https://backend-sls.klicker.uzh.ch'
    auth: 'https://auth.klicker.uzh.ch'
    lti: 'https://lti.klicker.uzh.ch'
    pwa: 'https://pwa.klicker.uzh.ch'
    manage: 'https://manage.klicker.uzh.ch'
    control: 'https://control.klicker.uzh.ch'
    assessmentApi: 'https://assessment-api.klicker.uzh.ch'
    assessmentPwa: 'https://assessment.klicker.uzh.ch'

hatchet:
  client:
    tlsStrategy: 'none'
    apiUrl: 'hatchet-prod-api:8080'
    hostPort: 'hatchet-grpc:7070'
  workers:
    general:
      replicaCount: 2
      priorityClassName: production-workload
      image:
        repository: ghcr.io/uzh-bf/klicker-uzh/hatchet-worker-general
        pullPolicy: Always
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 500Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - hatchet-worker-general
                topologyKey: kubernetes.io/hostname

    responseProcessor:
      replicaCount: 3
      priorityClassName: production-workload
      image:
        repository: ghcr.io/uzh-bf/klicker-uzh/hatchet-worker-response-processor
        pullPolicy: Always
      resources:
        requests:
          cpu: 300m
          memory: 300Mi
        limits:
          cpu: 800m
          memory: 800Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - hatchet-worker-response-processor
                topologyKey: kubernetes.io/hostname

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: hatchet-worker-response-processor
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: hatchet-worker-response-processor

auth:
  replicaCount: 2

  autoscaling:
    enabled: false

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - auth
            topologyKey: kubernetes.io/hostname

  ingress:
    hosts:
      - host: auth.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: auth.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-auth-tls-uzh
        hosts:
          - auth.klicker.uzh.ch
      - secretName: klicker-prod-frontend-auth-tls
        hosts:
          - auth.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 1000m
      memory: 1000Mi

frontendPWA:
  replicaCount: 3

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - frontend-pwa
            topologyKey: kubernetes.io/hostname

  ingress:
    hosts:
      - host: pwa.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: pwa.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-pwa-tls-uzh
        hosts:
          - pwa.klicker.uzh.ch
      - secretName: klicker-prod-frontend-pwa-tls
        hosts:
          - pwa.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 1000m
      memory: 1000Mi

frontendManage:
  replicaCount: 3

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - frontend-manage
            topologyKey: kubernetes.io/hostname

  ingress:
    hosts:
      - host: manage.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: manage.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-manage-tls-uzh
        hosts:
          - manage.klicker.uzh.ch
      - secretName: klicker-prod-frontend-manage-tls
        hosts:
          - manage.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 1000m
      memory: 1000Mi

frontendControl:
  replicaCount: 2

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - frontend-control
            topologyKey: kubernetes.io/hostname

  ingress:
    hosts:
      - host: control.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: control.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-control-tls-uzh
        hosts:
          - control.klicker.uzh.ch
      - secretName: klicker-prod-frontend-control-tls
        hosts:
          - control.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 500m
      memory: 500Mi

backendGraphql:
  replicaCount: 3

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - backend-graphql
            topologyKey: kubernetes.io/hostname

  ingress:
    hosts:
      - host: backend-sls.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: backend-sls.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-backend-graphql-tls-uzh
        hosts:
          - backend-sls.klicker.uzh.ch
      - secretName: klicker-prod-backend-graphql-tls
        hosts:
          - backend-sls.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 1000m
      memory: 1000Mi

olatApi:
  replicaCount: 1

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: olat-api.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: olat-api.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-olat-api-tls-uzh
        hosts:
          - olat-api.klicker.uzh.ch
      - secretName: klicker-prod-olat-api-tls
        hosts:
          - olat-api.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 500m
      memory: 500Mi

lti:
  replicaCount: 2

  ingress:
    hosts:
      - host: lti.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: lti.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-lti-tls-uzh
        hosts:
          - lti.klicker.uzh.ch
      - secretName: klicker-prod-lti-tls
        hosts:
          - lti.klicker-prod.bf-app.ch

responseApi:
  replicaCount: 3

  corsAllowedOrigins: 'https://pwa.klicker.uzh.ch'

  priorityClassName: production-workload

  image:
    repository: ghcr.io/uzh-bf/klicker-uzh/response-api
    pullPolicy: Always

  autoscaling:
    enabled: false

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - response-api
            topologyKey: kubernetes.io/hostname

  ingress:
    hosts:
      - host: response-api.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-response-api-tls
        hosts:
          - response-api.klicker.uzh.ch

  strategy:
    type: Recreate

  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 400m
      memory: 400Mi

redis:
  auth:
    enabled: false

assessment:
  frontendPWA:
    replicaCount: 3

    priorityClassName: production-workload

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

    image:
      repository: ghcr.io/uzh-bf/klicker-uzh/frontend-assessment
      pullPolicy: Always

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - frontend-assessment
              topologyKey: kubernetes.io/hostname

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: frontend-assessment
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: frontend-assessment

    ingress:
      hosts:
        - host: assessment.klicker.uzh.ch
          paths:
            - path: /
              pathType: ImplementationSpecific
        - host: assessment.klicker-prod.bf-app.ch
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: klicker-prod-frontend-assessment-tls-uzh
          hosts:
            - assessment.klicker.uzh.ch
        - secretName: klicker-prod-frontend-assessment-tls
          hosts:
            - assessment.klicker-prod.bf-app.ch

    strategy:
      type: RollingUpdate

    resources:
      requests:
        cpu: 150m
        memory: 150Mi
      limits:
        cpu: 1000m
        memory: 1000Mi

  backendGraphql:
    replicaCount: 3

    priorityClassName: production-workload

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

    appManageSubdomain: manage
    appStudentSubdomain: assessment
    appControlSubdomain: control

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - backend-assessment
              topologyKey: kubernetes.io/hostname

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: backend-assessment
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: backend-assessment

    ingress:
      hosts:
        - host: chat.klicker.uzh.ch
          paths:
            - path: /
              pathType: ImplementationSpecific
        - host: assessment-api.klicker-prod.bf-app.ch
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: klicker-prod-backend-assessment-tls-uzh
          hosts:
            - chat.klicker.uzh.ch
        - secretName: klicker-prod-backend-assessment-tls
          hosts:
            - assessment-api.klicker-prod.bf-app.ch

    strategy:
      type: RollingUpdate

    resources:
      requests:
        cpu: 150m
        memory: 150Mi
      limits:
        cpu: 1000m
        memory: 1000Mi

  responseApi:
    replicaCount: 3

    corsAllowedOrigins: 'https://assessment.klicker.uzh.ch'

    priorityClassName: production-workload

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - response-api-assessment
              topologyKey: kubernetes.io/hostname

    ingress:
      hosts:
        - host: assessment-response-api.klicker.uzh.ch
          paths:
            - path: /
              pathType: ImplementationSpecific
        - host: response-api-assessment.klicker-prod.bf-app.ch
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: klicker-prod-response-api-assessment-tls-uzh
          hosts:
            - assessment-response-api.klicker.uzh.ch
        - secretName: klicker-prod-response-api-assessment-tls
          hosts:
            - response-api-assessment.klicker-prod.bf-app.ch

    strategy:
      type: RollingUpdate

    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 400m
        memory: 400Mi
