dfDomain: prd.example.df-app.ch

email:
  type: SMTP
  from: '"Team KlickerUZH" <noreply-klicker@df.uzh.ch>'
  port: '1025'
  username: username
  secure: 'false'
  requireTLS: 'false'

blobStorage:
  accountName: klickeruzhdevimages

cron:
  token: abcd

auth:
  replicaCount: 1
  image:
    tag: argocd
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

frontendPWA:
  image:
    tag: argocd
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

frontendManage:
  image:
    tag: argocd
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

frontendControl:
  image:
    tag: argocd
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

backendGraphql:
  image:
    tag: argocd
  apiDomain: api.klicker-prod.prd.example.df-app.ch
  cookieDomain: .klicker-prod.prd.example.df-app.ch
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

  appManageSubdomain: manage
  appManageDomain: manage.klicker-prod.prd.example.df-app.ch
  appStudentSubdomain: pwa
  appStudentDomain: pwa.klicker-prod.prd.example.df-app.ch
  appControlSubdomain: control
  appControlDomain: control.klicker-prod.prd.example.df-app.ch

  notifications:
    supportEmail: klicker.support@uzh.ch

  redisCache:
    port: 6379
    tls: false

  redisExec:
    port: 6379
    tls: true

  sentryEnv: production

olatApi:
  image:
    tag: argocd
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

lti:
  replicaCount: 4
  image:
    tag: argocd
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-stg-apps-default

  redirectURL: https://lti.klicker-prod.prd.example.df-app.ch
  cookieDomain: .klicker-prod.prd.example.df-app.ch
  name: OLAT UZH
  url: https://lms.uzh.ch
  authEndpoint: https://lms.uzh.ch/lti/auth
  tokenEndpoint: https://lms.uzh.ch/lti/token
  keysEndpoint: https://lms.uzh.ch/lti/keys

  db:
    type: poprdres
    port: 5432
    name: klicker-prod-lti-prd
    username: fa2f28bacccb3302
