import { Redis } from 'ioredis'

const CHATBOT_GRAPH_PREFIX = 'klickeruzh:chatbot:'

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export type FalkorDBConfig = {
  host: string
  port: number
  username: string
  password: string
}

export type FalkorDBEnv = Record<string, string | undefined>

type FalkorDBEnvKey =
  | 'FALKORDB_HOST'
  | 'FALKORDB_PORT'
  | 'FALKORDB_USERNAME'
  | 'FALKORDB_PASSWORD'

export type FalkorDBClient = {
  call(command: string, ...args: Array<number | string>): Promise<unknown>
  quit?(): Promise<unknown>
}

export type ChatbotGraphArgs = {
  chatbotId: string
  client?: FalkorDBClient
}

export type ChatbotGraphQueryArgs = ChatbotGraphArgs & {
  query: string
}

export type ChatbotGraphSnapshotArgs = ChatbotGraphArgs & {
  nodeLimit?: number
  edgeLimit?: number
}

export type ChatbotGraphPropertyValue = boolean | null | number | string

export type ChatbotGraphSnapshotNode = {
  id: string
  label: string
  labels: string[]
  properties: Record<string, ChatbotGraphPropertyValue>
  depth?: number
  formula?: string
  kind?: string
  summary?: string
}

export type ChatbotGraphSnapshotEdge = {
  id: string
  label: string
  source: string
  target: string
  type: string
  properties: Record<string, ChatbotGraphPropertyValue>
}

export type ChatbotGraphSnapshot = {
  nodes: ChatbotGraphSnapshotNode[]
  edges: ChatbotGraphSnapshotEdge[]
  truncated: boolean
  limits: {
    nodeLimit: number
    edgeLimit: number
  }
}

export type PrototypeFinanceSeedArgs = {
  chatbotId?: string
  client?: FalkorDBClient
  reset?: boolean
}

export type PrototypeFinanceSeedResult = {
  chatbotId: string
  graphName: string
  nodeCount: number
  relationshipCount: number
}

type PrototypeFinanceNode = {
  id: string
  label: string
  kind: string
  summary: string
  depth: number
  formula?: string
}

type PrototypeFinanceRelationship = {
  source: string
  target: string
  type:
    | 'CONFLICTS_WITH'
    | 'DEPENDS_ON'
    | 'EXAMPLE_OF'
    | 'EXPLAINS'
    | 'HAS_CONCEPT'
    | 'HAS_FORMULA'
    | 'HAS_TOPIC'
    | 'MEASURES'
    | 'USES'
  label: string
}

export const BENIBOT_CHATBOT_ID = '8f9c2e1d-4b7a-4c3e-9f5d-1a2b3c4d5e6f'

const DEFAULT_NODE_LIMIT = 100
const DEFAULT_EDGE_LIMIT = 150
const MAX_SNAPSHOT_LIMIT = 500

const PROTOTYPE_FINANCE_NODES: PrototypeFinanceNode[] = [
  {
    id: 'finance',
    label: 'Finance',
    kind: 'domain',
    summary: 'Synthetic root of the finance knowledge graph prototype.',
    depth: 0,
  },
  {
    id: 'corporate-finance',
    label: 'Corporate Finance',
    kind: 'topic',
    summary: 'How firms fund investments and evaluate value creation.',
    depth: 1,
  },
  {
    id: 'asset-pricing',
    label: 'Asset Pricing',
    kind: 'topic',
    summary: 'How expected returns compensate investors for systematic risk.',
    depth: 1,
  },
  {
    id: 'risk-management',
    label: 'Risk Management',
    kind: 'topic',
    summary: 'Identification, measurement, and mitigation of financial risks.',
    depth: 1,
  },
  {
    id: 'financial-markets',
    label: 'Financial Markets',
    kind: 'topic',
    summary: 'Markets and instruments that allocate capital and transfer risk.',
    depth: 1,
  },
  {
    id: 'accounting',
    label: 'Accounting',
    kind: 'topic',
    summary: 'Financial statements and measurement systems used by firms.',
    depth: 1,
  },
  {
    id: 'wacc',
    label: 'WACC',
    kind: 'concept',
    summary:
      'Weighted average cost of capital used as a discount rate for firm cash flows.',
    depth: 2,
  },
  {
    id: 'capital-structure',
    label: 'Capital Structure',
    kind: 'concept',
    summary: 'The mix of debt and equity used to finance a company.',
    depth: 2,
  },
  {
    id: 'free-cash-flow',
    label: 'Free Cash Flow',
    kind: 'concept',
    summary:
      'Cash generated by operations after investments required to maintain growth.',
    depth: 2,
  },
  {
    id: 'npv',
    label: 'NPV',
    kind: 'concept',
    summary:
      'Net present value compares discounted future cash flows with an initial investment.',
    depth: 2,
  },
  {
    id: 'profitability',
    label: 'Profitability',
    kind: 'concept',
    summary: 'The capacity of a project or firm to generate returns.',
    depth: 2,
  },
  {
    id: 'capm',
    label: 'CAPM',
    kind: 'concept',
    summary:
      'Capital Asset Pricing Model links expected return to systematic market risk.',
    depth: 2,
  },
  {
    id: 'beta',
    label: 'Beta',
    kind: 'concept',
    summary: 'Sensitivity of an asset return to market return movements.',
    depth: 2,
  },
  {
    id: 'risk-free-rate',
    label: 'Risk-Free Rate',
    kind: 'concept',
    summary:
      'The return proxy for investing without default or reinvestment risk.',
    depth: 2,
  },
  {
    id: 'market-risk-premium',
    label: 'Market Risk Premium',
    kind: 'concept',
    summary:
      'Expected excess return of the market portfolio over the risk-free rate.',
    depth: 2,
  },
  {
    id: 'liquidity-risk',
    label: 'Liquidity Risk',
    kind: 'concept',
    summary:
      'Risk that an asset cannot be sold quickly without a material price concession.',
    depth: 2,
  },
  {
    id: 'credit-risk',
    label: 'Credit Risk',
    kind: 'concept',
    summary: 'Risk that a borrower or counterparty fails to meet obligations.',
    depth: 2,
  },
  {
    id: 'market-risk',
    label: 'Market Risk',
    kind: 'concept',
    summary:
      'Risk of losses from movements in market prices, rates, or volatility.',
    depth: 2,
  },
  {
    id: 'diversification',
    label: 'Diversification',
    kind: 'concept',
    summary:
      'Combining imperfectly correlated assets to reduce idiosyncratic risk.',
    depth: 2,
  },
  {
    id: 'bonds',
    label: 'Bonds',
    kind: 'concept',
    summary:
      'Debt instruments with cash flows determined by coupons and principal.',
    depth: 2,
  },
  {
    id: 'equities',
    label: 'Equities',
    kind: 'concept',
    summary: 'Ownership claims on residual corporate cash flows.',
    depth: 2,
  },
  {
    id: 'yield-curve',
    label: 'Yield Curve',
    kind: 'concept',
    summary:
      'Relationship between yields and maturities for comparable fixed-income instruments.',
    depth: 2,
  },
  {
    id: 'derivatives',
    label: 'Derivatives',
    kind: 'concept',
    summary:
      'Contracts whose values depend on underlying assets, rates, or indexes.',
    depth: 2,
  },
  {
    id: 'balance-sheet',
    label: 'Balance Sheet',
    kind: 'concept',
    summary:
      'Statement of assets, liabilities, and equity at a specific reporting date.',
    depth: 2,
  },
  {
    id: 'income-statement',
    label: 'Income Statement',
    kind: 'concept',
    summary:
      'Statement of revenues, expenses, and earnings over a reporting period.',
    depth: 2,
  },
  {
    id: 'cash-flow-statement',
    label: 'Cash Flow Statement',
    kind: 'concept',
    summary:
      'Statement separating operating, investing, and financing cash flows.',
    depth: 2,
  },
  {
    id: 'wacc-formula',
    label: 'WACC Formula',
    kind: 'formula',
    summary: 'Standard weighted cost of capital expression.',
    depth: 3,
    formula: 'WACC = E/(D+E) * r_E + D/(D+E) * r_D * (1 - T)',
  },
  {
    id: 'wacc-example',
    label: 'WACC Example',
    kind: 'example',
    summary:
      'A firm with more debt may lower taxes but increase financial distress risk.',
    depth: 3,
  },
  {
    id: 'wacc-assumption',
    label: 'WACC Assumption',
    kind: 'assumption',
    summary:
      'Use WACC only when project risk and financing policy match the firm average.',
    depth: 3,
  },
  {
    id: 'capm-formula',
    label: 'CAPM Formula',
    kind: 'formula',
    summary: 'Expected return as compensation for systematic risk.',
    depth: 3,
    formula: 'E(R_i) = R_f + beta_i * (E(R_m) - R_f)',
  },
  {
    id: 'capm-example',
    label: 'CAPM Example',
    kind: 'example',
    summary:
      'An asset with beta above one should have an expected return above the market premium baseline.',
    depth: 3,
  },
  {
    id: 'capm-assumption',
    label: 'CAPM Assumption',
    kind: 'assumption',
    summary:
      'Investors are assumed to hold diversified portfolios and care about systematic risk.',
    depth: 3,
  },
  {
    id: 'npv-formula',
    label: 'NPV Formula',
    kind: 'formula',
    summary:
      'Discount expected cash flows and subtract the initial investment.',
    depth: 3,
    formula: 'NPV = sum(CF_t / (1 + r)^t) - I_0',
  },
  {
    id: 'npv-example',
    label: 'NPV Example',
    kind: 'example',
    summary:
      'A project with positive NPV is expected to add value after accounting for risk and time.',
    depth: 3,
  },
  {
    id: 'beta-explanation',
    label: 'Beta Explanation',
    kind: 'explanation',
    summary:
      'Beta compares covariance with the market to the variance of the market portfolio.',
    depth: 3,
  },
  {
    id: 'beta-example',
    label: 'Beta Example',
    kind: 'example',
    summary:
      'A beta of 1.4 suggests the asset tends to move more strongly than the market.',
    depth: 3,
  },
  {
    id: 'yield-curve-explanation',
    label: 'Yield Curve Explanation',
    kind: 'explanation',
    summary:
      'An upward-sloping curve often reflects term premia and expected future rate increases.',
    depth: 3,
  },
  {
    id: 'yield-curve-example',
    label: 'Yield Curve Example',
    kind: 'example',
    summary:
      'A steepening curve can affect bond prices and refinancing decisions.',
    depth: 3,
  },
  {
    id: 'yield-curve-assumption',
    label: 'Yield Curve Assumption',
    kind: 'assumption',
    summary:
      'Yield comparisons should use instruments with similar credit risk and liquidity.',
    depth: 3,
  },
  {
    id: 'capital-structure-explanation',
    label: 'Capital Structure Tradeoff',
    kind: 'explanation',
    summary:
      'Debt tax shields can create value, but excessive debt raises distress costs.',
    depth: 3,
  },
  {
    id: 'free-cash-flow-formula',
    label: 'Free Cash Flow Formula',
    kind: 'formula',
    summary: 'A compact operating free cash flow approximation.',
    depth: 3,
    formula: 'FCF = NOPAT + Depreciation - CapEx - Delta NWC',
  },
]

const PROTOTYPE_FINANCE_RELATIONSHIPS: PrototypeFinanceRelationship[] = [
  {
    source: 'finance',
    target: 'corporate-finance',
    type: 'HAS_TOPIC',
    label: 'has topic',
  },
  {
    source: 'finance',
    target: 'asset-pricing',
    type: 'HAS_TOPIC',
    label: 'has topic',
  },
  {
    source: 'finance',
    target: 'risk-management',
    type: 'HAS_TOPIC',
    label: 'has topic',
  },
  {
    source: 'finance',
    target: 'financial-markets',
    type: 'HAS_TOPIC',
    label: 'has topic',
  },
  {
    source: 'finance',
    target: 'accounting',
    type: 'HAS_TOPIC',
    label: 'has topic',
  },
  {
    source: 'corporate-finance',
    target: 'wacc',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'corporate-finance',
    target: 'capital-structure',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'corporate-finance',
    target: 'free-cash-flow',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'corporate-finance',
    target: 'npv',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'corporate-finance',
    target: 'profitability',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'asset-pricing',
    target: 'capm',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'asset-pricing',
    target: 'beta',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'asset-pricing',
    target: 'risk-free-rate',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'asset-pricing',
    target: 'market-risk-premium',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'risk-management',
    target: 'liquidity-risk',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'risk-management',
    target: 'credit-risk',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'risk-management',
    target: 'market-risk',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'risk-management',
    target: 'diversification',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'financial-markets',
    target: 'bonds',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'financial-markets',
    target: 'equities',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'financial-markets',
    target: 'yield-curve',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'financial-markets',
    target: 'derivatives',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'accounting',
    target: 'balance-sheet',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'accounting',
    target: 'income-statement',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'accounting',
    target: 'cash-flow-statement',
    type: 'HAS_CONCEPT',
    label: 'has concept',
  },
  {
    source: 'wacc',
    target: 'wacc-formula',
    type: 'HAS_FORMULA',
    label: 'has formula',
  },
  {
    source: 'wacc-example',
    target: 'wacc',
    type: 'EXAMPLE_OF',
    label: 'example of',
  },
  {
    source: 'wacc',
    target: 'wacc-assumption',
    type: 'DEPENDS_ON',
    label: 'depends on',
  },
  {
    source: 'wacc',
    target: 'capital-structure',
    type: 'DEPENDS_ON',
    label: 'depends on',
  },
  { source: 'wacc', target: 'free-cash-flow', type: 'USES', label: 'uses' },
  {
    source: 'capm',
    target: 'capm-formula',
    type: 'HAS_FORMULA',
    label: 'has formula',
  },
  {
    source: 'capm-example',
    target: 'capm',
    type: 'EXAMPLE_OF',
    label: 'example of',
  },
  {
    source: 'capm',
    target: 'capm-assumption',
    type: 'DEPENDS_ON',
    label: 'depends on',
  },
  { source: 'capm', target: 'beta', type: 'USES', label: 'uses' },
  { source: 'capm', target: 'risk-free-rate', type: 'USES', label: 'uses' },
  {
    source: 'capm',
    target: 'market-risk-premium',
    type: 'USES',
    label: 'uses',
  },
  {
    source: 'beta',
    target: 'market-risk',
    type: 'MEASURES',
    label: 'measures exposure to',
  },
  {
    source: 'beta-explanation',
    target: 'beta',
    type: 'EXPLAINS',
    label: 'explains',
  },
  {
    source: 'beta-example',
    target: 'beta',
    type: 'EXAMPLE_OF',
    label: 'example of',
  },
  {
    source: 'npv',
    target: 'npv-formula',
    type: 'HAS_FORMULA',
    label: 'has formula',
  },
  {
    source: 'npv-example',
    target: 'npv',
    type: 'EXAMPLE_OF',
    label: 'example of',
  },
  { source: 'npv', target: 'free-cash-flow', type: 'USES', label: 'uses' },
  { source: 'npv', target: 'wacc', type: 'DEPENDS_ON', label: 'depends on' },
  {
    source: 'liquidity-risk',
    target: 'profitability',
    type: 'CONFLICTS_WITH',
    label: 'can reduce',
  },
  {
    source: 'diversification',
    target: 'market-risk',
    type: 'CONFLICTS_WITH',
    label: 'does not remove',
  },
  {
    source: 'bonds',
    target: 'yield-curve',
    type: 'DEPENDS_ON',
    label: 'depends on',
  },
  {
    source: 'yield-curve-explanation',
    target: 'yield-curve',
    type: 'EXPLAINS',
    label: 'explains',
  },
  {
    source: 'yield-curve-example',
    target: 'yield-curve',
    type: 'EXAMPLE_OF',
    label: 'example of',
  },
  {
    source: 'yield-curve',
    target: 'yield-curve-assumption',
    type: 'DEPENDS_ON',
    label: 'depends on',
  },
  {
    source: 'capital-structure-explanation',
    target: 'capital-structure',
    type: 'EXPLAINS',
    label: 'explains',
  },
  {
    source: 'free-cash-flow',
    target: 'free-cash-flow-formula',
    type: 'HAS_FORMULA',
    label: 'has formula',
  },
  {
    source: 'balance-sheet',
    target: 'capital-structure',
    type: 'EXPLAINS',
    label: 'explains',
  },
  {
    source: 'income-statement',
    target: 'free-cash-flow',
    type: 'EXPLAINS',
    label: 'explains',
  },
  {
    source: 'cash-flow-statement',
    target: 'free-cash-flow',
    type: 'EXPLAINS',
    label: 'explains',
  },
  { source: 'derivatives', target: 'market-risk', type: 'USES', label: 'uses' },
  {
    source: 'bonds',
    target: 'credit-risk',
    type: 'DEPENDS_ON',
    label: 'depends on credit quality',
  },
  {
    source: 'corporate-finance',
    target: 'balance-sheet',
    type: 'USES',
    label: 'uses accounting statement',
  },
  {
    source: 'corporate-finance',
    target: 'income-statement',
    type: 'USES',
    label: 'uses accounting statement',
  },
  {
    source: 'corporate-finance',
    target: 'cash-flow-statement',
    type: 'USES',
    label: 'uses accounting statement',
  },
  {
    source: 'asset-pricing',
    target: 'market-risk',
    type: 'DEPENDS_ON',
    label: 'depends on risk concept',
  },
  {
    source: 'risk-management',
    target: 'beta',
    type: 'USES',
    label: 'uses risk metric',
  },
  {
    source: 'yield-curve-example',
    target: 'financial-markets',
    type: 'EXAMPLE_OF',
    label: 'market example',
  },
  {
    source: 'accounting',
    target: 'free-cash-flow-formula',
    type: 'EXPLAINS',
    label: 'supports formula',
  },
  {
    source: 'asset-pricing',
    target: 'capm-assumption',
    type: 'DEPENDS_ON',
    label: 'depends on modeling assumptions',
  },
]

export function getChatbotGraphName(chatbotId: string): string {
  if (!UUID_PATTERN.test(chatbotId)) {
    throw new Error('chatbotId must be a valid UUID')
  }

  return `${CHATBOT_GRAPH_PREFIX}${chatbotId}`
}

export function loadFalkorDBConfig(
  env: FalkorDBEnv = process.env
): FalkorDBConfig {
  const host = requireEnvValue(env, 'FALKORDB_HOST')
  const username = requireEnvValue(env, 'FALKORDB_USERNAME')
  const password = requireEnvValue(env, 'FALKORDB_PASSWORD')
  const rawPort = requireEnvValue(env, 'FALKORDB_PORT')
  const port = Number(rawPort)

  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('FALKORDB_PORT must be an integer between 1 and 65535')
  }

  return {
    host,
    port,
    username,
    password,
  }
}

export function createFalkorDBClient(
  config: FalkorDBConfig = loadFalkorDBConfig()
): FalkorDBClient {
  return new Redis({
    family: 4,
    host: config.host,
    password: config.password,
    port: config.port,
    username: config.username,
  })
}

export async function createChatbotGraph(
  args: ChatbotGraphArgs
): Promise<void> {
  const graphName = getChatbotGraphName(args.chatbotId)
  const query = createGraphMetadataQuery(args.chatbotId)

  await withFalkorDBClient(args.client, async (client) => {
    await client.call('GRAPH.QUERY', graphName, query)
  })
}

export async function deleteChatbotGraph(
  args: ChatbotGraphArgs
): Promise<void> {
  const graphName = getChatbotGraphName(args.chatbotId)

  await withFalkorDBClient(args.client, async (client) => {
    await client.call('GRAPH.DELETE', graphName)
  })
}

export async function readChatbotGraph(
  args: ChatbotGraphQueryArgs
): Promise<unknown> {
  const graphName = getChatbotGraphName(args.chatbotId)
  const query = requireQuery(args.query)

  return await withFalkorDBClient(args.client, async (client) => {
    return await client.call('GRAPH.RO_QUERY', graphName, query)
  })
}

export async function writeChatbotGraph(
  args: ChatbotGraphQueryArgs
): Promise<unknown> {
  const graphName = getChatbotGraphName(args.chatbotId)
  const query = requireQuery(args.query)

  return await withFalkorDBClient(args.client, async (client) => {
    return await client.call('GRAPH.QUERY', graphName, query)
  })
}

export async function getChatbotGraphSnapshot(
  args: ChatbotGraphSnapshotArgs
): Promise<ChatbotGraphSnapshot> {
  const nodeLimit = requireLimit(
    args.nodeLimit ?? DEFAULT_NODE_LIMIT,
    'nodeLimit'
  )
  const edgeLimit = requireLimit(
    args.edgeLimit ?? DEFAULT_EDGE_LIMIT,
    'edgeLimit'
  )
  const nodeQuery = `MATCH (n) RETURN n LIMIT ${nodeLimit + 1}`
  const edgeQuery = `MATCH ()-[r]->() RETURN r LIMIT ${edgeLimit + 1}`

  return await withFalkorDBClient(args.client, async (client) => {
    try {
      const [rawNodes, rawEdges] = await Promise.all([
        readChatbotGraph({
          chatbotId: args.chatbotId,
          client,
          query: nodeQuery,
        }),
        readChatbotGraph({
          chatbotId: args.chatbotId,
          client,
          query: edgeQuery,
        }),
      ])
      const parsedNodes = parseNodeRows(rawNodes)
      const visibleNodes = parsedNodes.slice(0, nodeLimit)
      const visibleNodeIds = new Set(visibleNodes.map((node) => node.id))
      const allEdges = parseEdgeRows(rawEdges)
      const parsedEdges = allEdges.filter(
        (edge) =>
          visibleNodeIds.has(edge.source) && visibleNodeIds.has(edge.target)
      )
      const visibleEdges = parsedEdges.slice(0, edgeLimit)

      return {
        nodes: visibleNodes,
        edges: visibleEdges,
        truncated:
          parsedNodes.length > nodeLimit ||
          allEdges.length > edgeLimit ||
          parsedEdges.length > edgeLimit,
        limits: {
          nodeLimit,
          edgeLimit,
        },
      }
    } catch (error) {
      if (isMissingGraphError(error)) {
        return createEmptySnapshot(nodeLimit, edgeLimit)
      }

      throw error
    }
  })
}

export async function seedPrototypeFinanceGraph(
  args: PrototypeFinanceSeedArgs = { chatbotId: BENIBOT_CHATBOT_ID }
): Promise<PrototypeFinanceSeedResult> {
  const chatbotId = args.chatbotId || BENIBOT_CHATBOT_ID
  const graphName = getChatbotGraphName(chatbotId)
  const query = createPrototypeFinanceGraphQuery()

  await withFalkorDBClient(args.client, async (client) => {
    if (args.reset) {
      try {
        await deleteChatbotGraph({ chatbotId, client })
      } catch (error) {
        if (!isMissingGraphError(error)) {
          throw error
        }
      }
    }

    await writeChatbotGraph({ chatbotId, client, query })
  })

  return {
    chatbotId,
    graphName,
    nodeCount: PROTOTYPE_FINANCE_NODES.length,
    relationshipCount: PROTOTYPE_FINANCE_RELATIONSHIPS.length,
  }
}

export function createPrototypeFinanceGraphQuery(): string {
  const nodeVariables = new Map<string, string>()
  const nodeDepths = new Map(
    PROTOTYPE_FINANCE_NODES.map((node) => [node.id, node.depth])
  )
  const nodeStatements = PROTOTYPE_FINANCE_NODES.map((node, index) => {
    const variable = `n${index}`
    nodeVariables.set(node.id, variable)

    const properties = {
      depth: node.depth,
      id: node.id,
      kind: node.kind,
      label: node.label,
      prototype: true,
      summary: node.summary,
      ...(node.formula ? { formula: node.formula } : {}),
    }

    return [
      `MERGE (${variable}:PrototypeFinanceNode {id: ${toCypherValue(node.id)}})`,
      `SET ${toCypherAssignments(variable, properties)}`,
    ].join('\n')
  })

  const relationshipStatements = PROTOTYPE_FINANCE_RELATIONSHIPS.map(
    (relationship, index) => {
      const sourceVariable = requireNodeVariable(
        nodeVariables,
        relationship.source
      )
      const targetVariable = requireNodeVariable(
        nodeVariables,
        relationship.target
      )
      const sourceDepth = requireNodeDepth(nodeDepths, relationship.source)
      const targetDepth = requireNodeDepth(nodeDepths, relationship.target)
      const relationshipVariable = `r${index}`

      return [
        `MERGE (${sourceVariable})-[${relationshipVariable}:${relationship.type}]->(${targetVariable})`,
        `SET ${toCypherAssignments(relationshipVariable, {
          crossLevel: sourceDepth !== targetDepth,
          label: relationship.label,
          prototype: true,
          sourceDepth,
          targetDepth,
        })}`,
      ].join('\n')
    }
  )

  return [
    ...nodeStatements,
    ...relationshipStatements,
    'RETURN count(*) AS seeded',
  ].join('\n')
}

function createGraphMetadataQuery(chatbotId: string): string {
  // TODO: Upload course/chatbot source data into this graph once the ingestion
  // pipeline is available for chatbot-specific knowledge graphs.
  return (
    'MERGE (:GraphMetadata {' +
    'managedBy: "klickeruzh", ' +
    'resource: "chatbot", ' +
    `chatbotId: "${chatbotId}"` +
    '}) RETURN 1'
  )
}

function requireEnvValue(env: FalkorDBEnv, key: FalkorDBEnvKey): string {
  const value = env[key]?.trim()

  if (!value) {
    throw new Error(`${key} is required`)
  }

  return value
}

function requireQuery(query: string): string {
  if (!query.trim()) {
    throw new Error('query must not be empty')
  }

  return query
}

function requireLimit(limit: number, name: string): number {
  if (!Number.isInteger(limit) || limit < 1 || limit > MAX_SNAPSHOT_LIMIT) {
    throw new Error(
      `${name} must be an integer between 1 and ${MAX_SNAPSHOT_LIMIT}`
    )
  }

  return limit
}

function createEmptySnapshot(
  nodeLimit: number,
  edgeLimit: number
): ChatbotGraphSnapshot {
  return {
    nodes: [],
    edges: [],
    truncated: false,
    limits: {
      nodeLimit,
      edgeLimit,
    },
  }
}

function parseNodeRows(result: unknown): ChatbotGraphSnapshotNode[] {
  return getResultRows(result).flatMap((row) => {
    const entity = row[0]
    const id = readEntityString(entity, 'id')
    if (!id) return []

    const labels = readEntityStringList(entity, 'labels')
    const properties = readEntityProperties(entity)

    return [
      {
        id,
        label: getDisplayLabel(properties, labels, id),
        labels,
        properties,
        depth: getOptionalNumber(properties, 'depth'),
        formula: getOptionalString(properties, 'formula'),
        kind: getOptionalString(properties, 'kind'),
        summary: getOptionalString(properties, 'summary'),
      },
    ]
  })
}

function parseEdgeRows(result: unknown): ChatbotGraphSnapshotEdge[] {
  return getResultRows(result).flatMap((row) => {
    const entity = row[0]
    const id = readEntityString(entity, 'id')
    const source = readEntityString(entity, 'src_node')
    const target = readEntityString(entity, 'dest_node')
    const type = readEntityString(entity, 'type')
    if (!id || !source || !target || !type) return []

    const properties = readEntityProperties(entity)

    return [
      {
        id,
        label: getOptionalString(properties, 'label') ?? type,
        source,
        target,
        type,
        properties,
      },
    ]
  })
}

function getResultRows(result: unknown): unknown[][] {
  if (!Array.isArray(result)) return []

  const rows = result[1]
  if (!Array.isArray(rows)) return []

  return rows.filter((row): row is unknown[] => Array.isArray(row))
}

function readEntityString(entity: unknown, field: string): string | undefined {
  const value = readEntityField(entity, field)

  if (typeof value === 'number' || typeof value === 'string') {
    return String(value)
  }

  return undefined
}

function readEntityStringList(entity: unknown, field: string): string[] {
  const value = readEntityField(entity, field)
  if (!Array.isArray(value)) return []

  return value
    .filter((item): item is number | string => {
      return typeof item === 'number' || typeof item === 'string'
    })
    .map((item) => String(item))
}

function readEntityProperties(
  entity: unknown
): Record<string, ChatbotGraphPropertyValue> {
  const value = readEntityField(entity, 'properties')
  if (!Array.isArray(value)) return {}

  return value.reduce<Record<string, ChatbotGraphPropertyValue>>(
    (properties, pair) => {
      if (!Array.isArray(pair) || pair.length < 2) return properties

      const key = pair[0]
      if (typeof key !== 'number' && typeof key !== 'string') return properties

      properties[String(key)] = normalizePropertyValue(pair[1])
      return properties
    },
    {}
  )
}

function readEntityField(entity: unknown, field: string): unknown {
  if (!Array.isArray(entity)) return undefined

  const match = entity.find((entry) => {
    return Array.isArray(entry) && String(entry[0]) === field
  })

  return Array.isArray(match) ? match[1] : undefined
}

function normalizePropertyValue(value: unknown): ChatbotGraphPropertyValue {
  if (
    value === null ||
    typeof value === 'boolean' ||
    typeof value === 'number' ||
    typeof value === 'string'
  ) {
    if (value === 'true') return true
    if (value === 'false') return false

    return value
  }

  return String(value)
}

function getDisplayLabel(
  properties: Record<string, ChatbotGraphPropertyValue>,
  labels: string[],
  id: string
): string {
  return (
    getOptionalString(properties, 'label') ??
    getOptionalString(properties, 'name') ??
    getOptionalString(properties, 'title') ??
    labels[0] ??
    id
  )
}

function getOptionalNumber(
  properties: Record<string, ChatbotGraphPropertyValue>,
  key: string
): number | undefined {
  const value = properties[key]
  return typeof value === 'number' ? value : undefined
}

function getOptionalString(
  properties: Record<string, ChatbotGraphPropertyValue>,
  key: string
): string | undefined {
  const value = properties[key]
  return typeof value === 'string' && value.trim() ? value : undefined
}

function isMissingGraphError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error)

  return /does not exist|not found|unknown graph|empty key/i.test(message)
}

function toCypherAssignments(
  variable: string,
  properties: Record<string, boolean | number | string>
): string {
  return Object.entries(properties)
    .map(([key, value]) => `${variable}.${key} = ${toCypherValue(value)}`)
    .join(', ')
}

function toCypherValue(value: boolean | number | string): string {
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number') return String(value)

  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function requireNodeVariable(
  nodeVariables: Map<string, string>,
  nodeId: string
): string {
  const variable = nodeVariables.get(nodeId)
  if (!variable) {
    throw new Error(`Prototype finance graph is missing node ${nodeId}`)
  }

  return variable
}

function requireNodeDepth(nodeDepths: Map<string, number>, nodeId: string) {
  const depth = nodeDepths.get(nodeId)
  if (depth === undefined) {
    throw new Error(`Prototype finance graph is missing node ${nodeId}`)
  }

  return depth
}

async function withFalkorDBClient<T>(
  client: FalkorDBClient | undefined,
  operation: (client: FalkorDBClient) => Promise<T>
): Promise<T> {
  if (client) {
    return await operation(client)
  }

  const createdClient = createFalkorDBClient()

  try {
    return await operation(createdClient)
  } finally {
    await createdClient.quit?.()
  }
}
