name: Build and deploy frontend-manage to Vercel (Development)

on:
  push:
    branches:
      - v2
    paths:
      - "apps/frontend-manage/**"
      - ".github/workflows/v2_frontend-manage**"
  workflow_dispatch:

env:
  APP_PATH: 'apps/frontend-manage'
  NODE_VERSION: '16.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod --force' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_FRONTEND_MANAGE_ID}} #Required
          working-directory: ${{ env.APP_PATH }}
