{{- $fullName := include "chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-backend-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  API_DOMAIN: {{ .Values.assessment.backendGraphql.apiDomain | quote }}
  APP_MANAGE_DOMAIN: {{ .Values.assessment.backendGraphql.appManageDomain | quote }}
  APP_STUDENT_DOMAIN: {{ .Values.assessment.backendGraphql.appStudentDomain | quote }}
  APP_CONTROL_DOMAIN: {{ .Values.assessment.backendGraphql.appControlDomain | quote }}
  APP_MANAGE_SUBDOMAIN: {{ .Values.assessment.backendGraphql.appManageSubdomain | quote }}
  APP_STUDENT_SUBDOMAIN: {{ .Values.assessment.backendGraphql.appStudentSubdomain | quote }}
  APP_CONTROL_SUBDOMAIN: {{ .Values.assessment.backendGraphql.appControlSubdomain | quote }}
  NOTIFICATION_URL: {{ .Values.assessment.backendGraphql.notifications.url | quote }}
  NOTIFICATION_SUPPORT_MAIL: {{ .Values.assessment.backendGraphql.notifications.supportEmail | quote }}
  COOKIE_DOMAIN: {{ .Values.assessment.backendGraphql.cookieDomain | quote }}
  CRON_TOKEN: {{ .Values.cron.token | quote }}
  REDIS_CACHE_HOST: {{ .Values.assessment.backendGraphql.redisCache.host | quote }}
  REDIS_CACHE_PORT: {{ .Values.assessment.backendGraphql.redisCache.port | quote }}
  BLOB_STORAGE_ACCOUNT_NAME: {{ .Values.blobStorage.accountName | quote }}
  EMAIL_TYPE: {{ .Values.email.type | quote }}
  EMAIL_FROM: {{ .Values.email.from | quote }}
  EMAIL_HOST: {{ .Values.email.host | quote }}
  EMAIL_PORT: {{ .Values.email.port | quote }}
  EMAIL_USER: {{ .Values.email.username | quote }}
  EMAIL_SECURE: {{ .Values.email.secure | quote }}
  EMAIL_STARTTLS: {{ .Values.email.requireTLS | quote }}
  {{- if .Values.assessment.backendGraphql.redisCache.tls }}
  REDIS_CACHE_TLS: {{ .Values.assessment.backendGraphql.redisCache.tls | quote }}
  {{ end }}
  REDIS_HOST: {{ .Values.assessment.backendGraphql.redisExec.host | quote }}
  REDIS_PORT: {{ .Values.assessment.backendGraphql.redisExec.port | quote }}
  REDIS_TLS: {{ .Values.assessment.backendGraphql.redisExec.tls | quote }}
  {{- if .Values.assessment.backendGraphql.debug }}
  DEBUG: {{ .Values.assessment.backendGraphql.debug | quote }}
  {{ end }}
  {{- if .Values.heartbeats.dailyGroupScores }}
  HEARTBEAT_DAILY_GROUP_SCORES: {{ .Values.heartbeats.dailyGroupScores | quote }}
  {{ end }}
  {{- if .Values.assessment.backendGraphql.dualRedisMode }}
  ENABLE_DUAL_REDIS_MODE: {{ .Values.assessment.backendGraphql.dualRedisMode | quote }}
  {{ end }}
  {{- if .Values.assessment.backendGraphql.preserveRedisForComparison }}
  PRESERVE_REDIS_FOR_COMPARISON: {{ .Values.assessment.backendGraphql.preserveRedisForComparison | quote }}
  {{ end }}
  JWT_ISSUER_API: {{ .Values.jwtIssuers.assessmentApi | quote }}
