{{- $fullName := include "chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-frontend-manage
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  SOMETHING: anything
