{{- $fullName := include "chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-response-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  CORS_ALLOWED_ORIGINS: {{ .Values.responseApi.corsAllowedOrigins | quote }}
  HATCHET_TENANT_ID: {{ .Values.hatchet.client.tenantId | quote }}
  HATCHET_HOST_PORT: {{ .Values.hatchet.client.hostPort | quote }}
  HATCHET_API_URL: {{ .Values.hatchet.client.apiUrl | quote }}
  HATCHET_CLIENT_TLS_STRATEGY: {{ .Values.hatchet.client.tlsStrategy | quote }}
  REDIS_HOST: {{ .Values.backendGraphql.redisExec.host | quote }}
  REDIS_PORT: {{ .Values.backendGraphql.redisExec.port | quote }}
  REDIS_TLS: {{ .Values.backendGraphql.redisExec.tls | quote }}
