apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-cron-groups-final
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.finalRandomGroups | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.85.0
            imagePullPolicy: IfNotPresent
            args:
            - -X
            - POST
            - -H
            - "Content-Type: application/json"
            - -H
            - "x-token: {{ .Values.cron.token }}"
            - -H
            - "x-graphql-yoga-csrf: FinalRandomGroupAssignments"
            - -d
            - >
                {
                    "operationName": "FinalRandomGroupAssignments",
                    "variables": {},
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "eec2853f480a455126b4d00c0200b5f9a47a551d9d8b02b50806c31eb31cb8f7"
                        }
                    }
                }
            - 'http://{{ include "chart.fullname" . }}-backend-graphql:3000/api/graphql'
          restartPolicy: OnFailure
