apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-cron-timeline
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.updateWeeklyTimelineEntries | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.85.0
            imagePullPolicy: IfNotPresent
            args:
            - -X
            - POST
            - -H
            - "Content-Type: application/json"
            - -H
            - "x-token: {{ .Values.cron.token }}"
            - -H
            - "x-graphql-yoga-csrf: updateWeeklyTimelineEntries"
            - -d
            - >
                {
                    "operationName": "UpdateWeeklyTimelineEntries",
                    "variables": {},
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "b648bcfd7c9c0c382ca458b2126013852fc0b348b1445348e3107486bbaa9d06"
                        }
                    }
                }
            - "http://{{ include "chart.fullname" . }}-backend-graphql:3000/api/graphql"
          restartPolicy: OnFailure
