apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "chart.fullname" . }}-production-workload
  labels:
    {{- include "chart.labels" . | nindent 4 }}
value: 1000000
globalDefault: false
description: "Only for critical production workloads."
