apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-frontend-manage
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  SOMETHING: anything
