apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-chat
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_API_KEY: {{ .Values.chat.azure.apiKey | quote }}
  MCP_KEY: {{ .Values.chat.mcp.key | quote }}
