apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-response-api-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.assessment.backendGraphql.redisExec.pass | quote }}
