apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-hatchet-worker-general
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  CODEAPI_JWT_ISSUER: {{ .Values.codeApi.jwtIssuer | quote }}
  CODEAPI_JWT_AUDIENCE: {{ .Values.codeApi.jwtAudience | quote }}
  CODEAPI_TENANT_ID: {{ .Values.codeApi.tenantId | quote }}
  CODEAPI_JWT_PRIVATE_KEY: {{ .Values.codeApi.jwtPrivateKey | quote }}
  CODEAPI_JWT_KEY_ID: {{ .Values.codeApi.jwtKeyId | quote }}
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
  REDIS_ASSESSMENT_PASS: {{ .Values.assessment.backendGraphql.redisExec.pass | quote }}
  DATABASE_URL: {{ .Values.backendGraphql.databaseUrl | quote }}
  APP_SECRET: {{ .Values.appSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-hatchet-worker-response-processor
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
  REDIS_ASSESSMENT_PASS: {{ .Values.assessment.backendGraphql.redisExec.pass | quote }}
  APP_SECRET: {{ .Values.appSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-hatchet-worker-response-processor-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
  REDIS_ASSESSMENT_PASS: {{ .Values.assessment.backendGraphql.redisExec.pass | quote }}
  DATABASE_URL: {{ .Values.backendGraphql.databaseUrl | quote }}
  APP_SECRET: {{ .Values.appSecret | quote }}
