apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-audit
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.audit.azureStorage.connectionString | quote }}
  INTERNAL_TOKEN: {{ .Values.audit.internalToken | quote }}