apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-hatchet-worker-general
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-hatchet-worker-response-processor
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-hatchet-worker-response-processor-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
  REDIS_PASS: {{ .Values.assessment.backendGraphql.redisExec.pass | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
