apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.appSecret | quote }}
  DATABASE_URL: {{ .Values.backendGraphql.databaseUrl | quote }}
  EDUID_CLIENT_SECRET: {{ .Values.eduId.clientSecret | quote }}
