-- AlterTable
ALTER TABLE "public"."ChatUsageCredits" ALTER COLUMN "total" SET DEFAULT 0,
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,6),
ALTER COLUMN "current" SET DEFAULT 0,
ALTER COLUMN "current" SET DATA TYPE DECIMAL(18,6);
