import type { TailwindConfig } from '@react-email/components'

export default {
  theme: {
    extend: {
      colors: {
        'uzh-blue-100': '#0028a5',
        'uzh-blue-80': '#3353b7',
        'uzh-blue-60': '#667ec9',
        'uzh-blue-40': '#99a9db',
        'uzh-blue-20': '#ccd4ed',
        'uzh-grey-100': '#a3adb7',
        'uzh-grey-80': '#b5bdc5',
        'uzh-grey-60': '#c8ced4',
        'uzh-grey-40': '#dadee2',
        'uzh-grey-20': '#edeff1',
        'uzh-red-100': '#dc6027',
        'uzh-red-80': '#e38052',
        'uzh-red-60': '#eaa07d',
        'uzh-red-40': '#f1bfa9',
        'uzh-red-20': '#f8dfd4',
        'uzh-yellow-100': '#fede00',
        'uzh-yellow-80': '#fbe651',
        'uzh-yellow-60': '#fcec7c',
        'uzh-yellow-40': '#fdf3a8',
        'uzh-yellow-20': '#fef9d3',
        'uzh-lightgreen-100': '#91c34a',
        'uzh-lightgreen-80': '#aad470',
        'uzh-lightgreen-60': '#bfdfg4',
        'uzh-lightgreen-40': '#d5e9b7',
        'uzh-lightgreen-20': '#eaf4db',
        'uzh-darkgreen-100': '#2a7f62',
        'uzh-darkgreen-80': '#569d85',
        'uzh-darkgreen-60': '#80b6a4',
        'uzh-darkgreen-40': '#abcec2',
        'uzh-darkgreen-20': '#d5e7e1',
        'uzh-turqoise-100': '#0b82a0',
        'uzh-turqoise-80': '#3c9fb6',
        'uzh-turqoise-60': '#6bb7c7',
        'uzh-turqoise-40': '#9ed0d9',
        'uzh-turqoise-20': '#cfe8ec',
        'primary-100': 'var(--theme-color-primary)',
        'primary-80': 'var(--theme-color-primary-80)',
        'primary-60': 'var(--theme-color-primary-60)',
        'primary-40': 'var(--theme-color-primary-40)',
        'primary-20': 'var(--theme-color-primary-20)',
        'secondary-100': 'var(--theme-color-secondary)',
        'secondary-80': 'var(--theme-color-secondary-80)',
        'secondary-60': 'var(--theme-color-secondary-60)',
        'secondary-40': 'var(--theme-color-secondary-40)',
        'secondary-20': 'var(--theme-color-secondary-20)',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
    },
    fontSize: {
      xs: ['12px', { lineHeight: '16px' }],
      sm: ['14px', { lineHeight: '20px' }],
      base: ['16px', { lineHeight: '24px' }],
      lg: ['18px', { lineHeight: '28px' }],
      xl: ['20px', { lineHeight: '28px' }],
      '2xl': ['24px', { lineHeight: '32px' }],
      '3xl': ['30px', { lineHeight: '36px' }],
      '4xl': ['36px', { lineHeight: '36px' }],
      '5xl': ['48px', { lineHeight: '1' }],
      '6xl': ['60px', { lineHeight: '1' }],
      '7xl': ['72px', { lineHeight: '1' }],
      '8xl': ['96px', { lineHeight: '1' }],
      '9xl': ['144px', { lineHeight: '1' }],
    },
    spacing: {
      px: '1px',
      0: '0',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      14: '56px',
      16: '64px',
      20: '80px',
      24: '96px',
      28: '112px',
      32: '128px',
      36: '144px',
      40: '160px',
      44: '176px',
      48: '192px',
      52: '208px',
      56: '224px',
      60: '240px',
      64: '256px',
      72: '288px',
      80: '320px',
      96: '384px',
    },
  },
} satisfies TailwindConfig
