export { default as CommonLayout } from './CommonLayout'
export { default as EvaluationLayout } from './EvaluationLayout'
export { default as StaticLayout } from './StaticLayout'
export { default as StudentLayout } from './StudentLayout'
export { default as TeacherLayout } from './TeacherLayout'
