#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
	echo "Usage: $0 <command> [args...]" >&2
	exit 1
fi

export COOKIE_DOMAIN='127.0.0.1'
export API_DOMAIN="$COOKIE_DOMAIN"

export APP_ORIGIN_API='http://127.0.0.1:3000'
export APP_ORIGIN_PWA='http://127.0.0.1:3001'
export APP_ORIGIN_MANAGE='http://127.0.0.1:3002'
export APP_ORIGIN_CONTROL='http://127.0.0.1:3003'
export APP_ORIGIN_LTI='http://127.0.0.1:4000'
export APP_ORIGIN_AUTH='http://127.0.0.1:3010'
export APP_ORIGIN_CHAT='http://127.0.0.1:3004'
export APP_ORIGIN_ASSESSMENT_API="$APP_ORIGIN_API"
export APP_ORIGIN_ASSESSMENT_PWA="$APP_ORIGIN_PWA"

export NEXT_PUBLIC_API_URL="$APP_ORIGIN_API/api/graphql"
export NEXT_PUBLIC_API_URL_SSR="$NEXT_PUBLIC_API_URL"
export NEXT_PUBLIC_PWA_URL="$APP_ORIGIN_PWA"
export NEXT_PUBLIC_MANAGE_URL="$APP_ORIGIN_MANAGE"
export NEXT_PUBLIC_CONTROL_URL="$APP_ORIGIN_CONTROL"
export NEXT_PUBLIC_AUTH_URL="$APP_ORIGIN_AUTH"
export NEXT_PUBLIC_LTI_URL="$APP_ORIGIN_LTI"
export NEXT_PUBLIC_CHAT_URL="$APP_ORIGIN_CHAT"
export NEXT_PUBLIC_ASSESSMENT_URL="$APP_ORIGIN_ASSESSMENT_PWA"
export NEXT_PUBLIC_ASSESSMENT_API_URL="$APP_ORIGIN_ASSESSMENT_API"
export NEXT_PUBLIC_GROWTHBOOK_API_HOST='https://growthbook.test'
export NEXT_PUBLIC_GROWTHBOOK_CLIENT_KEY='sdk-test'

export NEXTAUTH_URL="$APP_ORIGIN_AUTH"
export AUTH_STUDENT_ALLOWED_HOSTS='127.0.0.1:3001'
export AUTH_LECTURER_ALLOWED_HOSTS='127.0.0.1:3002'
export AUTH_PWA_HOSTS='127.0.0.1:3000'

unset EDUID_CLIENT_SECRET

exec "$@"
