// flow-typed signature: 0a3ef3b73e5b3e946e097cd14ee31191
// flow-typed version: <<STUB>>/logrocket-react_v^0.0.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logrocket-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logrocket-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logrocket-react/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logrocket-react/dist/index.js' {
  declare module.exports: $Exports<'logrocket-react/dist/index'>;
}
