// flow-typed signature: b7a4bdeae3704dc1f95e1fbe2ad50b20
// flow-typed version: <<STUB>>/prosemirror-view_v0.22.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prosemirror-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prosemirror-view/dist/browser' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/capturekeys' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/clipboard' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/decoration' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/dom' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/domchange' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/domcoords' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/domobserver' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/index' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/input' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/selection' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/trackmappings' {
  declare module.exports: any;
}

declare module 'prosemirror-view/dist/viewdesc' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/browser' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/capturekeys' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/clipboard' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/decoration' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/dom' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/domchange' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/domcoords' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/domobserver' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/index' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/input' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/selection' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/trackmappings' {
  declare module.exports: any;
}

declare module 'prosemirror-view/src/viewdesc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prosemirror-view/dist/browser.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/browser'>;
}
declare module 'prosemirror-view/dist/capturekeys.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/capturekeys'>;
}
declare module 'prosemirror-view/dist/clipboard.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/clipboard'>;
}
declare module 'prosemirror-view/dist/decoration.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/decoration'>;
}
declare module 'prosemirror-view/dist/dom.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/dom'>;
}
declare module 'prosemirror-view/dist/domchange.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/domchange'>;
}
declare module 'prosemirror-view/dist/domcoords.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/domcoords'>;
}
declare module 'prosemirror-view/dist/domobserver.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/domobserver'>;
}
declare module 'prosemirror-view/dist/index.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/index'>;
}
declare module 'prosemirror-view/dist/input.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/input'>;
}
declare module 'prosemirror-view/dist/selection.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/selection'>;
}
declare module 'prosemirror-view/dist/trackmappings.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/trackmappings'>;
}
declare module 'prosemirror-view/dist/viewdesc.js' {
  declare module.exports: $Exports<'prosemirror-view/dist/viewdesc'>;
}
declare module 'prosemirror-view/src/browser.js' {
  declare module.exports: $Exports<'prosemirror-view/src/browser'>;
}
declare module 'prosemirror-view/src/capturekeys.js' {
  declare module.exports: $Exports<'prosemirror-view/src/capturekeys'>;
}
declare module 'prosemirror-view/src/clipboard.js' {
  declare module.exports: $Exports<'prosemirror-view/src/clipboard'>;
}
declare module 'prosemirror-view/src/decoration.js' {
  declare module.exports: $Exports<'prosemirror-view/src/decoration'>;
}
declare module 'prosemirror-view/src/dom.js' {
  declare module.exports: $Exports<'prosemirror-view/src/dom'>;
}
declare module 'prosemirror-view/src/domchange.js' {
  declare module.exports: $Exports<'prosemirror-view/src/domchange'>;
}
declare module 'prosemirror-view/src/domcoords.js' {
  declare module.exports: $Exports<'prosemirror-view/src/domcoords'>;
}
declare module 'prosemirror-view/src/domobserver.js' {
  declare module.exports: $Exports<'prosemirror-view/src/domobserver'>;
}
declare module 'prosemirror-view/src/index.js' {
  declare module.exports: $Exports<'prosemirror-view/src/index'>;
}
declare module 'prosemirror-view/src/input.js' {
  declare module.exports: $Exports<'prosemirror-view/src/input'>;
}
declare module 'prosemirror-view/src/selection.js' {
  declare module.exports: $Exports<'prosemirror-view/src/selection'>;
}
declare module 'prosemirror-view/src/trackmappings.js' {
  declare module.exports: $Exports<'prosemirror-view/src/trackmappings'>;
}
declare module 'prosemirror-view/src/viewdesc.js' {
  declare module.exports: $Exports<'prosemirror-view/src/viewdesc'>;
}
