[tool.poetry]
name = "export-v2-data"
version = "0.1.0"
description = ""
authors = ["Bulin Shaqiri <bulin.shaqiri@bf.uzh.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymongo = "^4.3.3"
pandas = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
