# Overlay to enable devrouter routing (https://*.klicker.localhost) and local trust of mkcert root CA.

services:
  postgres:
    ports: !reset []
    networks:
      devnet:
        aliases: [klicker-db]

  mailhog:
    ports: !reset []

  hatchet:
    ports: !reset []

  app:
    ports: !reset []
    extra_hosts:
      - 'api.klicker.localhost:host-gateway'
      - 'auth.klicker.localhost:host-gateway'
      - 'pwa.klicker.localhost:host-gateway'
      - 'manage.klicker.localhost:host-gateway'
      - 'control.klicker.localhost:host-gateway'
      - 'olat-api.klicker.localhost:host-gateway'
      - 'response-api.klicker.localhost:host-gateway'
      - 'lti.klicker.localhost:host-gateway'
      - 'chat.klicker.localhost:host-gateway'
    networks:
      devnet:
        aliases: [klicker-app]
    volumes:
      # Local mkcert root CA (created by `dev tls install`) for server-side TLS trust.
      - '${DEVROUTER_MKCERT_CAROOT:-${HOME}/Library/Application Support/mkcert}/rootCA.pem:/etc/devrouter/mkcert-rootCA.pem:ro'

  litellm:
    ports: !reset []

networks:
  devnet:
    external: true
