apiVersion: v2
name: klicker-uzh
description: A Helm chart for the KlickerUZH
type: application
version: 1.8.1
appVersion: v1.8.1
dependencies:
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami
