import type { Locator, Page } from '@playwright/test'
import { cleanupTest } from '../util/cleanup.js'
import { COURSE_ID_TEST, URL_MANAGE } from '../util/constants.js'
import { COURSE_QA_DATA, setCourseQAFlags } from '../util/courseQa.js'
import { expect, test } from '../util/fixtures.js'

const manageUrl = process.env.URL_MANAGE ?? URL_MANAGE
const courseName = COURSE_QA_DATA.course

let anonymousThreadEmbedUrl = ''
let anonymousReplyEmbedUrl = ''
let readOnlyEmbedUrl = ''

test.describe.configure({ mode: 'serial' })

function requireEmbedUrl(name: string, value: string): string {
  if (!value) {
    throw new Error(`${name} was not generated by the lecturer workflow`)
  }

  return value
}

function courseThread(page: Page, content: string): Locator {
  return page
    .getByTestId(/^course-qa-thread-\d+$/)
    .filter({ has: page.getByText(content, { exact: true }) })
    .first()
}

async function createThread(page: Page, content: string) {
  const input = page.getByTestId('course-qa-thread-input')
  await input.fill(content)
  await page.getByTestId('course-qa-create-thread').click()
  await expect(page.getByText(content, { exact: true })).toBeVisible()
  await expect(input).toHaveValue('')
}

function parseEmbedUrl(embedInfo: { embedUrl: string; scopeKey: string }): URL {
  const url = new URL(embedInfo.embedUrl)
  expect(url.searchParams.get('scopeKey')).toBe(embedInfo.scopeKey)
  expect(url.searchParams.has('embedToken')).toBe(false)
  expect(new URLSearchParams(url.hash.slice(1)).get('embedToken')).toBeTruthy()
  return url
}

async function generateEmbedUrl(page: Page) {
  const responsePromise = page.waitForResponse((response) => {
    const request = response.request()
    if (request.method() !== 'POST') return false

    try {
      const body = request.postDataJSON() as { operationName?: unknown }
      return body.operationName === 'GenerateCourseDiscussionEmbeddingInfo'
    } catch {
      return false
    }
  })

  await page.getByTestId('course-qa-generate-embed').click()
  const response = await responsePromise
  expect(response.ok()).toBe(true)

  const result = (await response.json()) as {
    data?: {
      generateCourseDiscussionEmbeddingInfo?: {
        allowAnonymous: boolean
        embedUrl: string
        scopeKey: string
      } | null
    }
    errors?: unknown[]
  }
  expect(result.errors).toBeUndefined()

  const embedInfo = result.data?.generateCourseDiscussionEmbeddingInfo
  expect(embedInfo).toBeTruthy()
  if (!embedInfo) {
    throw new Error('Embed generation returned no embedding information')
  }

  await expect(page.getByTestId('course-qa-embed-url')).toHaveText(
    embedInfo.embedUrl
  )
  return embedInfo
}

async function expectEmbedTokenScrubbed(page: Page) {
  await expect
    .poll(() => {
      const url = new URL(page.url())
      return {
        hasTokenQuery: url.searchParams.has('embedToken'),
        hash: url.hash,
      }
    })
    .toEqual({ hasTokenQuery: false, hash: '' })

  const historyState = await page.evaluate(() => JSON.stringify(history.state))
  expect(historyState).not.toContain('embedToken')
}

test('CLEANUP', async () => {
  await cleanupTest()
  await setCourseQAFlags(courseName, {
    isCourseQARolloutEnabled: true,
    isCourseQAEnabled: true,
    isCourseQAAnonymousEnabled: true,
  })
})

test.describe('Course Q&A embed workflow', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 900 })
  })

  test('Lecturer generates course and external-block embed links', async ({
    page,
    loginLecturer,
  }) => {
    await loginLecturer()
    await page.goto(`${manageUrl}/courses/${COURSE_ID_TEST}`)
    await page.getByTestId('tab-discussions').click()
    await page
      .locator('details')
      .filter({
        has: page.getByTestId('course-qa-generate-embed'),
      })
      .locator('summary')
      .click()

    await page.getByTestId('course-qa-embed-scope-course').click()
    await expect(page.getByTestId('course-qa-generate-embed')).toBeEnabled()
    const courseEmbed = await generateEmbedUrl(page)
    expect(courseEmbed.scopeKey).toBe(`course:${COURSE_ID_TEST}`)
    parseEmbedUrl(courseEmbed)

    await page.getByTestId('course-qa-embed-scope-external').click()
    const generateButton = page.getByTestId('course-qa-generate-embed')
    await expect(generateButton).toBeDisabled()

    const sourceInput = page.getByTestId('course-qa-external-source')
    const referenceInput = page.getByTestId('course-qa-external-ref')
    await expect(sourceInput).toHaveAttribute('maxlength', '100')
    await sourceInput.fill(COURSE_QA_DATA.embed.externalSource)
    await expect(referenceInput).toHaveAttribute('maxlength', '200')
    await referenceInput.fill(COURSE_QA_DATA.embed.externalRef)

    const anonymousToggle = page.getByTestId('course-qa-allow-anonymous-embed')
    await expect(anonymousToggle).toBeVisible()
    await expect(anonymousToggle).toBeEnabled()
    await anonymousToggle.check()
    await expect(generateButton).toBeEnabled()

    const anonymousThreadEmbed = await generateEmbedUrl(page)
    expect(anonymousThreadEmbed.allowAnonymous).toBe(true)
    parseEmbedUrl(anonymousThreadEmbed)
    anonymousThreadEmbedUrl = anonymousThreadEmbed.embedUrl

    await referenceInput.fill(`${COURSE_QA_DATA.embed.externalRef}-reply`)
    const anonymousReplyEmbed = await generateEmbedUrl(page)
    expect(anonymousReplyEmbed.allowAnonymous).toBe(true)
    parseEmbedUrl(anonymousReplyEmbed)
    anonymousReplyEmbedUrl = anonymousReplyEmbed.embedUrl

    await anonymousToggle.uncheck()
    await referenceInput.fill(`${COURSE_QA_DATA.embed.externalRef}-read-only`)
    const readOnlyEmbed = await generateEmbedUrl(page)
    expect(readOnlyEmbed.allowAnonymous).toBe(false)
    parseEmbedUrl(readOnlyEmbed)
    readOnlyEmbedUrl = readOnlyEmbed.embedUrl

    expect(
      new Set([
        anonymousThreadEmbed.scopeKey,
        anonymousReplyEmbed.scopeKey,
        readOnlyEmbed.scopeKey,
      ]).size
    ).toBe(3)
  })

  test('Anonymous embed renders without app chrome and accepts a thread', async ({
    page,
  }) => {
    await page.goto(
      requireEmbedUrl('Anonymous thread embed URL', anonymousThreadEmbedUrl)
    )

    await expectEmbedTokenScrubbed(page)
    await expect(page.getByAltText('KlickerUZH Logo')).toHaveCount(0)
    await expect(page.locator('footer')).toHaveCount(0)
    await expect(page.getByTestId('course-qa-thread-anonymous')).toBeVisible()
    await expect(page.getByTestId('course-qa-thread-anonymous')).toContainText(
      /anonym/i
    )

    await createThread(page, COURSE_QA_DATA.embed.anonymousThread)
    await expect(page.getByTestId('course-qa-thread-anonymous')).toBeVisible()
  })

  test('Authenticated student creates threads for anonymous and read-only coverage', async ({
    page,
    loginStudent,
  }) => {
    await loginStudent()
    await expect(page.getByTestId(`course-button-${courseName}`)).toBeVisible()
    await page.goto(
      requireEmbedUrl('Anonymous reply embed URL', anonymousReplyEmbedUrl)
    )

    await createThread(page, COURSE_QA_DATA.embed.identifiedThread)

    await page.goto(requireEmbedUrl('Read-only embed URL', readOnlyEmbedUrl))
    await createThread(page, COURSE_QA_DATA.embed.identifiedThread)
  })

  test('Anonymous visitor gets a read-only identified embed', async ({
    page,
  }) => {
    await page.goto(requireEmbedUrl('Read-only embed URL', readOnlyEmbedUrl))

    await expect(page.getByTestId('course-qa-read-only')).toBeVisible()
    await expect(
      page.getByText(COURSE_QA_DATA.embed.identifiedThread, { exact: true })
    ).toBeVisible()
    await expect(page.getByTestId('course-qa-thread-input')).toHaveCount(0)
    await expect(page.getByTestId('course-qa-create-thread')).toHaveCount(0)
    await expect(page.getByTestId(/^course-qa-reply-input-/)).toHaveCount(0)
    await expect(page.getByTestId(/^course-qa-create-reply-/)).toHaveCount(0)
    await expect(page.getByTestId(/^course-qa-open-reply-/)).toHaveCount(0)
    await expect(page.getByTestId(/^course-qa-thread-upvote-/)).toHaveCount(0)
    await expect(page.getByTestId(/^course-qa-reply-upvote-/)).toHaveCount(0)
  })

  test('Fresh anonymous visitor replies to the identified embed thread', async ({
    page,
  }) => {
    await page.goto(
      requireEmbedUrl('Anonymous reply embed URL', anonymousReplyEmbedUrl)
    )

    const thread = courseThread(page, COURSE_QA_DATA.embed.identifiedThread)
    const replyInput = thread.getByTestId(/^course-qa-reply-input-/)
    await expect(replyInput).toBeHidden()
    await thread.getByTestId(/^course-qa-open-reply-/).click()
    await replyInput.fill(COURSE_QA_DATA.embed.anonymousReply)
    const anonymousNotice = thread.getByTestId(/^course-qa-reply-anonymous-/)
    await expect(anonymousNotice).toBeVisible()
    await expect(anonymousNotice).toContainText(/anonym/i)
    await thread.getByTestId(/^course-qa-create-reply-/).click()
    await expect(
      thread.getByText(COURSE_QA_DATA.embed.anonymousReply, { exact: true })
    ).toBeVisible()
    await expect(replyInput).toHaveValue('')
    await expect(anonymousNotice).toBeVisible()
  })

  test('Tampered embed token is rejected', async ({ page }) => {
    const url = new URL(
      requireEmbedUrl('Anonymous thread embed URL', anonymousThreadEmbedUrl)
    )
    const fragmentParams = new URLSearchParams(url.hash.slice(1))
    const token = fragmentParams.get('embedToken') ?? ''
    const [header, payload, signature] = token.split('.')

    if (!header || !payload || !signature) {
      throw new Error('Generated embed token is not a JWT')
    }

    const signatureIndex = Math.floor(signature.length / 2)
    const replacement = signature[signatureIndex] === 'a' ? 'b' : 'a'
    const tamperedSignature =
      signature.slice(0, signatureIndex) +
      replacement +
      signature.slice(signatureIndex + 1)
    fragmentParams.set(
      'embedToken',
      `${header}.${payload}.${tamperedSignature}`
    )
    url.hash = fragmentParams.toString()

    await page.goto(url.toString())
    await expect(page.getByTestId('course-qa-access-denied')).toBeVisible()
  })
})
