export const IMPORT_EXPORT_MIGRATIONS = [
  '20260707120000_import_export_fingerprints',
  '20260712205147_import_export_durable_state',
  '20260712223000_import_export_media_fingerprint_state',
  '20260713003000_element_import_receipt_identity_immutable',
  '20260713013000_import_export_result_and_target_immutability',
  '20260713130636_import_export_duplicate_lookup_indexes',
  '20260716085603_import_export_fingerprint_repair_indexes',
  '20260722100000_import_export_null_fingerprint_repair_indexes',
] as const

export const REQUIRED_IMPORT_EXPORT_COLUMNS = [
  ['AnswerCollection', 'importFingerprint', 'text'],
  ['AnswerCollection', 'importFingerprintVersion', 'integer'],
  ['Element', 'importFingerprint', 'text'],
  ['Element', 'importFingerprintVersion', 'integer'],
  ['MediaFile', 'contentHash', 'text'],
  ['MediaFile', 'importFingerprintVersion', 'integer'],
] as const

export const REQUIRED_IMPORT_EXPORT_INDEXES = [
  [
    'AnswerCollection',
    'AnswerCollection_ownerId_importFingerprint_idx',
    false,
    ['ownerId', 'importFingerprint'],
  ],
  [
    'AnswerCollection',
    'AnswerCollection_owner_fpv_fp_idx',
    false,
    ['ownerId', 'importFingerprintVersion', 'importFingerprint'],
  ],
  [
    'AnswerCollection',
    'AnswerCollection_owner_fpv_fp_id_idx',
    false,
    [
      'ownerId',
      'importFingerprintVersion',
      'importFingerprint',
      'isDeleted',
      'id',
    ],
  ],
  [
    'AnswerCollection',
    'AnswerCollection_repair_fpv_deleted_id_idx',
    false,
    ['importFingerprintVersion', 'isDeleted', 'id'],
  ],
  [
    'AnswerCollection',
    'AnswerCollection_repair_null_fp_id_idx',
    false,
    ['id'],
    '(("isDeleted" = false) AND ("importFingerprint" IS NULL))',
  ],
  [
    'Element',
    'Element_ownerId_importFingerprint_idx',
    false,
    ['ownerId', 'importFingerprint'],
  ],
  [
    'Element',
    'Element_answer_collection_deleted_id_idx',
    false,
    ['answerCollectionId', 'isDeleted', 'id'],
  ],
  [
    'Element',
    'Element_owner_fpv_fp_idx',
    false,
    ['ownerId', 'importFingerprintVersion', 'importFingerprint'],
  ],
  [
    'Element',
    'Element_owner_fpv_fp_id_idx',
    false,
    [
      'ownerId',
      'importFingerprintVersion',
      'importFingerprint',
      'isDeleted',
      'id',
    ],
  ],
  [
    'Element',
    'Element_repair_fpv_deleted_id_idx',
    false,
    ['importFingerprintVersion', 'isDeleted', 'id'],
  ],
  [
    'Element',
    'Element_repair_null_fp_id_idx',
    false,
    ['id'],
    '(("isDeleted" = false) AND ("importFingerprint" IS NULL))',
  ],
  [
    'MediaFile',
    'MediaFile_import_fpv_id_idx',
    false,
    ['importFingerprintVersion', 'id'],
  ],
  [
    'ImportExportPackageArtifact',
    'PackageArtifact_storage_target_key',
    true,
    ['storageContainer', 'storageBlob'],
  ],
  [
    'ImportExportPackageArtifact',
    'PackageArtifact_owner_expiry_idx',
    false,
    ['ownerId', 'expiresAt'],
  ],
  [
    'ImportExportPackageArtifact',
    'PackageArtifact_expiry_idx',
    false,
    ['expiresAt'],
  ],
  [
    'ImportExportPackageArtifact',
    'PackageArtifact_state_expiry_idx',
    false,
    ['state', 'expiresAt'],
  ],
  ['ElementImportReceipt', 'ElementImportReceipt_jti_key', true, ['jti']],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_artifact_record_idx',
    false,
    ['artifactRecordId'],
  ],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_owner_idx',
    false,
    ['ownerId'],
  ],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_state_lease_idx',
    false,
    ['state', 'leaseExpiresAt'],
  ],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_state_retention_idx',
    false,
    ['state', 'retentionExpiresAt'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_receipt_ref_key',
    true,
    ['receiptId', 'packageMediaRef'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_storage_target_key',
    true,
    ['storageContainer', 'storageBlob'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_operation_idx',
    false,
    ['operationId'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_state_expiry_idx',
    false,
    ['state', 'expiresAt'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_owner_expiry_idx',
    false,
    ['ownerId', 'expiresAt'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_media_file_idx',
    false,
    ['mediaFileId'],
  ],
] as const

export const REQUIRED_IMPORT_EXPORT_CONSTRAINTS = [
  {
    tableName: 'ImportExportPackageArtifact',
    constraintName: 'PackageArtifact_storage_target_check',
    constraintType: 'c',
    keyColumns: ['storageContainer', 'storageBlob'],
  },
  {
    tableName: 'ImportExportPackageArtifact',
    constraintName: 'PackageArtifact_expiry_check',
    constraintType: 'c',
    keyColumns: ['expiresAt', 'createdAt'],
  },
  {
    tableName: 'ImportExportPackageArtifact',
    constraintName: 'PackageArtifact_state_fields_check',
    constraintType: 'c',
    keyColumns: ['state', 'reservedBytes', 'bytes', 'sha256', 'completedAt'],
  },
  {
    tableName: 'ElementImportReceipt',
    constraintName: 'ElementImportReceipt_artifact_match_check',
    constraintType: 'c',
    keyColumns: ['artifactRecordId', 'sourceArtifactId'],
  },
  {
    tableName: 'ElementImportReceipt',
    constraintName: 'ElementImportReceipt_hashes_check',
    constraintType: 'c',
    keyColumns: ['packageHash', 'selectionDigest'],
  },
  {
    tableName: 'ElementImportReceipt',
    constraintName: 'ElementImportReceipt_arrays_check',
    constraintType: 'c',
    keyColumns: [
      'selectedElementRefs',
      'createdElementIds',
      'createdAnswerCollectionIds',
    ],
  },
  {
    tableName: 'ElementImportReceipt',
    constraintName: 'ElementImportReceipt_state_fields_check',
    constraintType: 'c',
    keyColumns: [
      'state',
      'leaseId',
      'leaseExpiresAt',
      'createdElementIds',
      'createdAnswerCollectionIds',
      'completedAt',
      'retentionExpiresAt',
      'createdAt',
    ],
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_storage_target_check',
    constraintType: 'c',
    keyColumns: ['storageContainer', 'storageBlob'],
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_content_hash_check',
    constraintType: 'c',
    keyColumns: ['contentHash'],
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_expiry_check',
    constraintType: 'c',
    keyColumns: ['expiresAt', 'createdAt'],
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_state_fields_check',
    constraintType: 'c',
    keyColumns: ['state', 'createdBlob', 'mediaFileId'],
  },
  {
    tableName: 'MediaFile',
    constraintName: 'MediaFile_contentHash_check',
    constraintType: 'c',
    keyColumns: ['contentHash'],
  },
  {
    tableName: 'MediaFile',
    constraintName: 'MediaFile_importFingerprintVersion_check',
    constraintType: 'c',
    keyColumns: ['importFingerprintVersion'],
  },
  {
    tableName: 'Element',
    constraintName: 'Element_importFingerprintVersion_check',
    constraintType: 'c',
    keyColumns: ['importFingerprintVersion'],
  },
  {
    tableName: 'AnswerCollection',
    constraintName: 'AnswerCollection_importFingerprintVersion_check',
    constraintType: 'c',
    keyColumns: ['importFingerprintVersion'],
  },
  {
    tableName: 'ImportExportPackageArtifact',
    constraintName: 'ImportExportPackageArtifact_ownerId_fkey',
    constraintType: 'f',
    keyColumns: ['ownerId'],
    referencedTable: 'User',
    referencedColumns: ['id'],
    updateAction: 'c',
    deleteAction: 'r',
  },
  {
    tableName: 'ElementImportReceipt',
    constraintName: 'ElementImportReceipt_ownerId_fkey',
    constraintType: 'f',
    keyColumns: ['ownerId'],
    referencedTable: 'User',
    referencedColumns: ['id'],
    updateAction: 'c',
    deleteAction: 'r',
  },
  {
    tableName: 'ElementImportReceipt',
    constraintName: 'ElementImportReceipt_artifactRecordId_fkey',
    constraintType: 'f',
    keyColumns: ['artifactRecordId'],
    referencedTable: 'ImportExportPackageArtifact',
    referencedColumns: ['id'],
    updateAction: 'c',
    deleteAction: 'n',
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_receiptId_fkey',
    constraintType: 'f',
    keyColumns: ['receiptId'],
    referencedTable: 'ElementImportReceipt',
    referencedColumns: ['id'],
    updateAction: 'c',
    deleteAction: 'r',
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_ownerId_fkey',
    constraintType: 'f',
    keyColumns: ['ownerId'],
    referencedTable: 'User',
    referencedColumns: ['id'],
    updateAction: 'c',
    deleteAction: 'r',
  },
  {
    tableName: 'ImportMediaStaging',
    constraintName: 'ImportMediaStaging_mediaFileId_fkey',
    constraintType: 'f',
    keyColumns: ['mediaFileId'],
    referencedTable: 'MediaFile',
    referencedColumns: ['id'],
    updateAction: 'c',
    deleteAction: 'n',
  },
] as const

export const IMPORT_EXPORT_CHECK_CONSTRAINT_CONTRACT_PREFIX =
  'klicker-import-export-check-v1:'

export const REQUIRED_IMPORT_EXPORT_TRIGGERS = [
  [
    'ElementImportReceipt',
    'ElementImportReceipt_artifact_owner_trigger',
    'enforce_element_import_receipt_artifact_owner',
    23,
    [],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_owner_trigger',
    'enforce_import_media_staging_owners',
    23,
    [],
  ],
  [
    'ImportExportPackageArtifact',
    'PackageArtifact_owner_immutable_trigger',
    'prevent_import_export_owner_change',
    19,
    ['ownerId'],
  ],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_owner_immutable_trigger',
    'prevent_import_export_owner_change',
    19,
    ['ownerId'],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_owner_immutable_trigger',
    'prevent_import_export_owner_change',
    19,
    ['ownerId'],
  ],
  [
    'MediaFile',
    'MediaFile_detach_import_staging_owner_change_trigger',
    'detach_import_staging_on_media_owner_change',
    19,
    ['ownerId'],
  ],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_identity_immutable_trigger',
    'prevent_element_import_receipt_identity_change',
    19,
    [
      'jti',
      'sourceArtifactId',
      'packageHash',
      'selectionDigest',
      'selectedElementRefs',
    ],
  ],
  [
    'ElementImportReceipt',
    'ElementImportReceipt_result_immutable_trigger',
    'prevent_completed_import_receipt_change',
    19,
    [],
  ],
  [
    'ImportMediaStaging',
    'ImportMediaStaging_identity_immutable_trigger',
    'prevent_import_media_staging_identity_change',
    19,
    [],
  ],
  [
    'ImportExportPackageArtifact',
    'PackageArtifact_target_immutable_trigger',
    'prevent_package_artifact_target_change',
    19,
    [],
  ],
] as const
