import { ADAPTIVE_V2_EXPOSURE_CEILING } from '@klicker-uzh/adaptive-learning'

export const ADAPTIVE_V2_CANDIDATE_SET_POLICY_VERSION =
  'IRT_V2_TOP_INFORMATION_RANDOMIZED_1'
export const ADAPTIVE_V2_OVERLAP_POLICY_VERSION =
  'IRT_V2_FIRST_EXPOSURE_OVERLAP_1'
export const ADAPTIVE_V2_STOPPING_POLICY_VERSION =
  'IRT_V2_POSTERIOR_BAND_MASS_1'
export const ADAPTIVE_V2_RESEARCH_ALLOCATION_POLICY_VERSION =
  'IRT_V2_RESEARCH_ALLOCATION_2'
export const ADAPTIVE_V2_RESEARCH_COLLECTION_VERSION =
  'IRT_V2_RESEARCH_COLLECTION_1'
export const ADAPTIVE_V2_RESEARCH_ANCHOR_RESPONSES_PER_LEAF_LEVEL = 1
export const ADAPTIVE_V2_RESEARCH_FIELD_TEST_RESPONSES_PER_LEAF = 1
export const ADAPTIVE_V2_RESEARCH_SCORING_REDUNDANCY_PER_LEAF = 1
export const ADAPTIVE_V2_RESEARCH_MINIMUM_DISTINCT_ANCHORS_PER_LEAF_LEVEL =
  Math.ceil(
    ADAPTIVE_V2_RESEARCH_ANCHOR_RESPONSES_PER_LEAF_LEVEL /
      ADAPTIVE_V2_EXPOSURE_CEILING
  )
export const ADAPTIVE_V2_RESEARCH_MINIMUM_DISTINCT_FIELD_TESTS_PER_LEAF =
  Math.ceil(
    ADAPTIVE_V2_RESEARCH_FIELD_TEST_RESPONSES_PER_LEAF /
      ADAPTIVE_V2_EXPOSURE_CEILING
  )

export {
  ADAPTIVE_V2_DIAGNOSTIC_RELEASE,
  ADAPTIVE_V2_EXPOSURE_CEILING,
} from '@klicker-uzh/adaptive-learning'
