export const MAX_BUFFERED_QUESTION_GENERATION_ARTIFACT_BYTES = 10 * 1024 * 1024

export const QUESTION_LIBRARY_WARNING_CODES = {
  semanticOverlap: 'LIBRARY_SEMANTIC_OVERLAP',
  comparisonTruncated: 'LIBRARY_COMPARISON_TRUNCATED',
} as const
