// flow-typed signature: bd7395efed3da97d9f15668128b859e3
// flow-typed version: <<STUB>>/mongodb_v^2.2.30/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb/boot_auth' {
  declare module.exports: any;
}

declare module 'mongodb/insert_bench' {
  declare module.exports: any;
}

declare module 'mongodb/lib/admin' {
  declare module.exports: any;
}

declare module 'mongodb/lib/aggregation_cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/apm' {
  declare module.exports: any;
}

declare module 'mongodb/lib/authenticate' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/common' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/ordered' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/unordered' {
  declare module.exports: any;
}

declare module 'mongodb/lib/collection' {
  declare module.exports: any;
}

declare module 'mongodb/lib/command_cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/db' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/download' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/index' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/upload' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs/chunk' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs/grid_store' {
  declare module.exports: any;
}

declare module 'mongodb/lib/metadata' {
  declare module.exports: any;
}

declare module 'mongodb/lib/mongo_client' {
  declare module.exports: any;
}

declare module 'mongodb/lib/mongos' {
  declare module.exports: any;
}

declare module 'mongodb/lib/read_preference' {
  declare module.exports: any;
}

declare module 'mongodb/lib/replset' {
  declare module.exports: any;
}

declare module 'mongodb/lib/server' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topology_base' {
  declare module.exports: any;
}

declare module 'mongodb/lib/url_parser' {
  declare module.exports: any;
}

declare module 'mongodb/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb/boot_auth.js' {
  declare module.exports: $Exports<'mongodb/boot_auth'>;
}
declare module 'mongodb/index' {
  declare module.exports: $Exports<'mongodb'>;
}
declare module 'mongodb/index.js' {
  declare module.exports: $Exports<'mongodb'>;
}
declare module 'mongodb/insert_bench.js' {
  declare module.exports: $Exports<'mongodb/insert_bench'>;
}
declare module 'mongodb/lib/admin.js' {
  declare module.exports: $Exports<'mongodb/lib/admin'>;
}
declare module 'mongodb/lib/aggregation_cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/aggregation_cursor'>;
}
declare module 'mongodb/lib/apm.js' {
  declare module.exports: $Exports<'mongodb/lib/apm'>;
}
declare module 'mongodb/lib/authenticate.js' {
  declare module.exports: $Exports<'mongodb/lib/authenticate'>;
}
declare module 'mongodb/lib/bulk/common.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/common'>;
}
declare module 'mongodb/lib/bulk/ordered.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/ordered'>;
}
declare module 'mongodb/lib/bulk/unordered.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/unordered'>;
}
declare module 'mongodb/lib/collection.js' {
  declare module.exports: $Exports<'mongodb/lib/collection'>;
}
declare module 'mongodb/lib/command_cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/command_cursor'>;
}
declare module 'mongodb/lib/cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/cursor'>;
}
declare module 'mongodb/lib/db.js' {
  declare module.exports: $Exports<'mongodb/lib/db'>;
}
declare module 'mongodb/lib/gridfs-stream/download.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/download'>;
}
declare module 'mongodb/lib/gridfs-stream/index.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/index'>;
}
declare module 'mongodb/lib/gridfs-stream/upload.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/upload'>;
}
declare module 'mongodb/lib/gridfs/chunk.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs/chunk'>;
}
declare module 'mongodb/lib/gridfs/grid_store.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs/grid_store'>;
}
declare module 'mongodb/lib/metadata.js' {
  declare module.exports: $Exports<'mongodb/lib/metadata'>;
}
declare module 'mongodb/lib/mongo_client.js' {
  declare module.exports: $Exports<'mongodb/lib/mongo_client'>;
}
declare module 'mongodb/lib/mongos.js' {
  declare module.exports: $Exports<'mongodb/lib/mongos'>;
}
declare module 'mongodb/lib/read_preference.js' {
  declare module.exports: $Exports<'mongodb/lib/read_preference'>;
}
declare module 'mongodb/lib/replset.js' {
  declare module.exports: $Exports<'mongodb/lib/replset'>;
}
declare module 'mongodb/lib/server.js' {
  declare module.exports: $Exports<'mongodb/lib/server'>;
}
declare module 'mongodb/lib/topology_base.js' {
  declare module.exports: $Exports<'mongodb/lib/topology_base'>;
}
declare module 'mongodb/lib/url_parser.js' {
  declare module.exports: $Exports<'mongodb/lib/url_parser'>;
}
declare module 'mongodb/lib/utils.js' {
  declare module.exports: $Exports<'mongodb/lib/utils'>;
}
