apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-backend-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  TEAMS_WEBHOOK_URL: {{ .Values.teamsWebhookUrl | quote }}
  APP_SECRET: {{ .Values.appSecret | quote }}
  NOTIFICATION_SECRET: {{ .Values.assessment.backendGraphql.notifications.secret | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.assessment.backendGraphql.vapid.publicKey | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.assessment.backendGraphql.vapid.privateKey | quote }}
  DATABASE_URL: {{ .Values.assessment.backendGraphql.databaseUrl | quote }}
  REDIS_CACHE_PASS: {{ .Values.assessment.backendGraphql.redisCache.pass | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
  REDIS_ASSESSMENT_PASS: {{ .Values.assessment.backendGraphql.redisExec.pass | quote }}
  BLOB_STORAGE_ACCESS_KEY: {{ .Values.blobStorage.accessKey | quote }}
  EMAIL_PASS: {{ .Values.email.password | quote }}
  HATCHET_CLIENT_TOKEN: {{ .Values.hatchet.client.token | quote }}
