apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-olat-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  OLAT_API_KEY: {{ .Values.olatApi.key | quote }}
  DATABASE_URL: {{ .Values.backendGraphql.databaseUrl | quote }}
