frontendPWA:
  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: pwa.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: pwa.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-pwa-tls-uzh
        hosts:
          - pwa.klicker.uzh.ch
      - secretName: klicker-prod-frontend-pwa-tls
        hosts:
          - pwa.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate

frontendManage:
  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: manage.klicker.uzh.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: manage.klicker-prod.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-manage-tls-uzh
        hosts:
          - manage.klicker.uzh.ch
      - secretName: klicker-prod-frontend-manage-tls
        hosts:
          - manage.klicker-prod.bf-app.ch

  strategy:
    type: RollingUpdate
