import type {
  KnowledgeBaseSettingsData,
  KnowledgeBaseSummary,
  KnowledgeGraphData,
  KnowledgeMetadataFieldDefinition,
  KnowledgeResource,
  KnowledgeResourceTypeDefinition,
} from './types.js'

export const demoKnowledgeBaseMetadataSchema: KnowledgeMetadataFieldDefinition[] =
  [
    {
      id: 'owner',
      label: 'Owner',
      type: 'text',
      visibility: ['sidebar', 'header', 'popover', 'settings'],
      displayPriority: 1,
    },
    {
      id: 'audience',
      label: 'Audience',
      type: 'enum',
      visibility: ['header', 'popover', 'settings'],
      displayPriority: 2,
      options: [
        { id: 'lecture', label: 'Lecture' },
        { id: 'support', label: 'Support' },
        { id: 'ops', label: 'Operations' },
      ],
    },
    {
      id: 'semester',
      label: 'Semester',
      type: 'text',
      visibility: ['sidebar', 'header', 'popover', 'settings'],
      displayPriority: 3,
    },
  ]

export const demoResourceMetadataSchema: KnowledgeMetadataFieldDefinition[] = [
  {
    id: 'studyLevel',
    label: 'Study level',
    type: 'multiEnum',
    description: 'Used as a retrieval filter before ranking.',
    retrievalKey: true,
    filterable: true,
    visibility: ['table', 'popover', 'settings'],
    displayPriority: 1,
    options: [
      {
        id: 'bachelor',
        label: 'Bachelor',
        colorClassName: 'bg-blue-50 text-blue-700',
      },
      {
        id: 'master',
        label: 'Master',
        colorClassName: 'bg-violet-50 text-violet-700',
      },
      {
        id: 'both',
        label: 'Both',
        colorClassName: 'bg-slate-100 text-slate-700',
      },
    ],
  },
  {
    id: 'scope',
    label: 'Scope',
    type: 'enum',
    retrievalKey: true,
    filterable: true,
    visibility: ['table', 'popover', 'settings'],
    displayPriority: 2,
    options: [
      {
        id: 'course',
        label: 'Course',
        colorClassName: 'bg-green-50 text-green-700',
      },
      {
        id: 'department',
        label: 'Department',
        colorClassName: 'bg-amber-50 text-amber-800',
      },
      {
        id: 'uzh',
        label: 'UZH wide',
        colorClassName: 'bg-cyan-50 text-cyan-800',
      },
    ],
  },
  {
    id: 'usage',
    label: 'Usage',
    type: 'enum',
    retrievalKey: true,
    filterable: true,
    visibility: ['table', 'popover', 'settings'],
    displayPriority: 3,
    options: [
      { id: 'rag', label: 'RAG' },
      { id: 'generation', label: 'Generation' },
      { id: 'reference', label: 'Reference' },
    ],
  },
  {
    id: 'topic',
    label: 'Topic',
    type: 'text',
    visibility: ['popover', 'settings'],
    displayPriority: 4,
  },
]

export const demoResourceTypes: KnowledgeResourceTypeDefinition[] = [
  {
    id: 'document',
    label: 'Document',
    shortLabel: 'PDF',
    icon: 'document',
    colorClassName: 'bg-orange-50 text-orange-700',
  },
  {
    id: 'website',
    label: 'Website',
    shortLabel: 'URL',
    icon: 'website',
    colorClassName: 'bg-cyan-50 text-cyan-800',
  },
  {
    id: 'snippet',
    label: 'Snippet',
    shortLabel: 'Text',
    icon: 'snippet',
    colorClassName: 'bg-yellow-50 text-yellow-800',
  },
  {
    id: 'internal',
    label: 'Library item',
    shortLabel: 'Library',
    icon: 'internal',
    colorClassName: 'bg-blue-50 text-blue-800',
  },
]

export const demoKnowledgeBases: KnowledgeBaseSummary[] = [
  {
    id: 'wine-chemistry',
    name: 'Wine Chemistry',
    description: 'Lecture notes, lab safety, pH reference tables',
    resourceCount: 24,
    status: 'ready',
    statusLabel: 'Ready',
    updatedAtLabel: 'today',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: {
      owner: 'Food & Wine Chemistry',
      audience: 'lecture',
      semester: 'FS25',
    },
    resourceMetadataSchema: demoResourceMetadataSchema,
    resourceTypes: demoResourceTypes,
    refreshPolicy: {
      mode: 'interval',
      intervalLabel: 'Daily',
      scope: 'refreshable',
      changeMonitoring: true,
    },
    metrics: [
      { id: 'resources', label: 'Resources', value: 24 },
      { id: 'chunks', label: 'Chunks', value: '1,847' },
      { id: 'size', label: 'Size', value: '12.4 MB' },
      { id: 'entities', label: 'Entities', value: 48 },
      { id: 'cost', label: 'Cost - APR', value: '$10.84' },
      { id: 'freshness', label: 'Freshness', value: '96%' },
    ],
  },
  {
    id: 'finance-core',
    name: 'Finance Core Concepts',
    resourceCount: 42,
    status: 'indexing',
    statusLabel: 'Indexing',
    updatedAtLabel: '2h ago',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: {
      owner: 'Banking & Finance',
      audience: 'lecture',
      semester: 'HS25',
    },
    resourceMetadataSchema: demoResourceMetadataSchema,
    resourceTypes: demoResourceTypes,
    refreshPolicy: { mode: 'interval', intervalLabel: 'Weekly' },
    metrics: [
      { id: 'resources', label: 'Resources', value: 42 },
      { id: 'chunks', label: 'Chunks', value: '3,205' },
      { id: 'size', label: 'Size', value: '18.1 MB' },
      { id: 'freshness', label: 'Freshness', value: '82%' },
    ],
  },
  {
    id: 'bf-notes',
    name: 'BF Lecture Notes HS25',
    resourceCount: 58,
    status: 'ready',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: {
      owner: 'Banking & Finance',
      audience: 'lecture',
      semester: 'HS25',
    },
  },
  {
    id: 'thesis-handbook',
    name: 'Thesis Handbook',
    resourceCount: 6,
    status: 'ready',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: { owner: 'Faculty office', audience: 'support' },
  },
  {
    id: 'lab-safety',
    name: 'Lab Safety Guidelines',
    resourceCount: 11,
    status: 'stale',
    statusLabel: 'Stale',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: { owner: 'Lab operations', audience: 'support' },
  },
  {
    id: 'stats-101',
    name: 'Stats 101',
    resourceCount: 28,
    status: 'error',
    statusLabel: 'Error',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: { owner: 'Statistics', audience: 'lecture', semester: 'FS25' },
  },
]

const defaultChunks = [
  {
    id: 'chunk-1',
    label: 'chunk #1',
    pageLabel: 'p. 5',
    content:
      'Malolactic fermentation converts harsher malic acid to softer lactic acid, raising pH by about 0.1 to 0.3 units.',
  },
  {
    id: 'chunk-2',
    label: 'chunk #2',
    pageLabel: 'p. 6',
    content:
      'Potassium bitartrate precipitation removes one acidic proton of tartaric acid from solution during cold stabilisation.',
  },
  {
    id: 'chunk-3',
    label: 'chunk #3',
    pageLabel: 'p. 7',
    content:
      'Ethanol affects perceived acidity through dielectric constant changes to ionisation equilibria.',
  },
]

const defaultConsumers = [
  {
    id: 'wc-ta',
    name: 'Wine Chemistry TA',
    description: 'FS25 - Food & Wine Chemistry',
    avatarLabel: 'WC',
  },
]

const defaultSchedule = {
  id: 'daily',
  label: 'Daily - 03:00 CET',
  nextRunLabel: 'Next run in 9h 22m.',
  note: 'Only refreshable websites are re-fetched.',
}

const defaultRuns = [
  { id: 'mon', label: 'Mon', status: 'ready' as const, value: 42 },
  { id: 'tue', label: 'Tue', status: 'error' as const, value: 72 },
  { id: 'wed', label: 'Wed', status: 'ready' as const, value: 26 },
  { id: 'thu', label: 'Thu', status: 'ready' as const, value: 66 },
  { id: 'fri', label: 'Fri', status: 'error' as const, value: 68 },
  { id: 'sat', label: 'Sat', status: 'disabled' as const, value: 8 },
  { id: 'sun', label: 'Sun', status: 'ready' as const, value: 16 },
]

export const demoResources: KnowledgeResource[] = [
  {
    id: 'fermentation-acids',
    knowledgeBaseId: 'wine-chemistry',
    title: 'Lecture 07 - Fermentation Acids.pdf',
    type: 'document',
    originLabel: 'Upload',
    sizeLabel: '1.4 MB',
    chunkCount: 84,
    updatedAtLabel: '2025-11-18',
    status: 'ready',
    metadata: {
      studyLevel: ['bachelor'],
      scope: 'course',
      usage: 'rag',
      topic: 'Fermentation acids',
    },
    documentMetadata: {
      pageCount: 38,
      fileSizeLabel: '1.4 MB',
      mimeType: 'PDF',
      language: 'EN',
      author: 'Prof. Meier',
    },
    freshness: {
      lastIndexedAtLabel: '2025-11-18',
      lastCheckedAtLabel: '2025-11-18',
      nextCheckAtLabel: 'manual',
      changeStatus: 'unchanged',
      changeStatusLabel: 'Source unchanged',
      refreshPolicy: { mode: 'manual' },
    },
    chunkPreviews: defaultChunks,
    linkedConsumers: defaultConsumers,
    reindexSchedule: defaultSchedule,
    ingestionRuns: defaultRuns,
  },
  {
    id: 'malolactic',
    knowledgeBaseId: 'wine-chemistry',
    title: 'Lecture 08 - Malolactic Conversion.pdf',
    type: 'document',
    originLabel: 'Upload',
    sizeLabel: '2.1 MB',
    chunkCount: 112,
    updatedAtLabel: '2025-11-18',
    status: 'ready',
    metadata: {
      studyLevel: ['bachelor', 'master'],
      scope: 'course',
      usage: 'generation',
      topic: 'Malolactic conversion',
    },
    documentMetadata: {
      pageCount: 52,
      fileSizeLabel: '2.1 MB',
      mimeType: 'PDF',
      language: 'EN',
      extractedTitle: 'Malolactic Conversion',
    },
    freshness: {
      lastIndexedAtLabel: '2025-11-18',
      lastCheckedAtLabel: '2025-11-18',
      nextCheckAtLabel: 'manual',
      changeStatus: 'unchanged',
      refreshPolicy: { mode: 'manual' },
    },
    chunkPreviews: defaultChunks,
    linkedConsumers: defaultConsumers,
    reindexSchedule: defaultSchedule,
    ingestionRuns: defaultRuns,
  },
  {
    id: 'oiv-standards',
    knowledgeBaseId: 'wine-chemistry',
    title: 'www.oiv.int/standards/',
    type: 'website',
    originLabel: 'Crawl',
    originDetail: 'depth 2',
    chunkCount: undefined,
    updatedAtLabel: 'now',
    status: 'crawling',
    progress: 72,
    metadata: {
      studyLevel: ['master'],
      scope: 'department',
      usage: 'reference',
      topic: 'Wine standards',
    },
    websiteMetadata: {
      strategy: 'S',
      strategyLabel: 'S scrape subsites',
      sitemapFound: true,
      sitemapPageCount: 184,
      depthLabel: 'depth 2',
      subsites: [
        {
          id: 'oiv-methods',
          title: 'Compendium of International Methods',
          url: 'https://www.oiv.int/standards/compendium',
          status: 'ready',
          chunkCount: 18,
          lastCheckedAtLabel: 'now',
        },
        {
          id: 'oiv-oenological',
          title: 'Oenological practices',
          url: 'https://www.oiv.int/standards/oenological-practices',
          status: 'crawling',
          chunkCount: 9,
          lastCheckedAtLabel: 'now',
        },
        {
          id: 'oiv-definitions',
          title: 'Wine product definitions',
          url: 'https://www.oiv.int/standards/definitions',
          status: 'queued',
          lastCheckedAtLabel: 'queued',
        },
        {
          id: 'oiv-analysis',
          title: 'Analysis reference documents',
          url: 'https://www.oiv.int/standards/analysis',
          status: 'ready',
          chunkCount: 24,
          lastCheckedAtLabel: 'now',
        },
      ],
    },
    freshness: {
      lastCheckedAtLabel: 'now',
      lastIndexedAtLabel: '2025-11-19',
      lastRemoteModifiedAtLabel: 'today',
      nextCheckAtLabel: 'tomorrow 03:00',
      changeStatus: 'changed',
      changeStatusLabel: 'New pages detected',
      refreshPolicy: { mode: 'inherit' },
      inheritedFromKnowledgeBase: true,
    },
    chunkPreviews: [
      {
        id: 'crawl-1',
        label: 'crawl queue',
        content:
          'Crawler is expanding standard pages and collecting linked PDF resources for parsing.',
      },
    ],
    linkedConsumers: defaultConsumers,
    reindexSchedule: defaultSchedule,
    ingestionRuns: defaultRuns,
  },
  {
    id: 'tartaric-wikipedia',
    knowledgeBaseId: 'wine-chemistry',
    title: 'Tartaric Acid - Wikipedia',
    type: 'website',
    originLabel: 'URL',
    sizeLabel: '48 KB',
    chunkCount: 14,
    updatedAtLabel: '2025-11-15',
    status: 'ready',
    metadata: {
      studyLevel: ['bachelor'],
      scope: 'course',
      usage: 'rag',
      topic: 'Tartaric acid',
    },
    websiteMetadata: {
      strategy: 'I',
      strategyLabel: 'I index only',
      sitemapFound: false,
      scrapedPageCount: 1,
    },
    freshness: {
      lastCheckedAtLabel: '12h ago',
      lastIndexedAtLabel: '2025-11-15',
      lastRemoteModifiedAtLabel: '2d ago',
      nextCheckAtLabel: 'tomorrow 03:00',
      changeStatus: 'unchanged',
      changeStatusLabel: 'No content change',
      refreshPolicy: { mode: 'inherit' },
    },
    chunkPreviews: defaultChunks.slice(0, 2),
    linkedConsumers: defaultConsumers,
    reindexSchedule: defaultSchedule,
    ingestionRuns: defaultRuns,
  },
  {
    id: 'ph-reference',
    knowledgeBaseId: 'wine-chemistry',
    title: 'pH Reference Card',
    type: 'snippet',
    originLabel: 'Pasted',
    originDetail: 'snippet',
    sizeLabel: '1 KB',
    chunkCount: 2,
    updatedAtLabel: '2025-11-10',
    status: 'ready',
    metadata: {
      studyLevel: ['both'],
      scope: 'course',
      usage: 'generation',
      topic: 'pH formulas',
    },
    snippetMetadata: {
      characterCount: 948,
      language: 'EN',
      author: 'Course team',
    },
    freshness: {
      lastIndexedAtLabel: '2025-11-10',
      lastCheckedAtLabel: 'manual',
      changeStatus: 'unknown',
      refreshPolicy: { mode: 'manual' },
    },
    chunkPreviews: defaultChunks.slice(0, 1),
  },
  {
    id: 'student-ph-faq',
    knowledgeBaseId: 'wine-chemistry',
    title: 'FAQ - Student pH measurement',
    type: 'snippet',
    originLabel: 'Pasted',
    originDetail: 'snippet',
    chunkCount: 6,
    updatedAtLabel: '2025-11-05',
    status: 'ready',
    metadata: {
      studyLevel: ['bachelor'],
      scope: 'course',
      usage: 'rag',
      topic: 'Student FAQ',
    },
    snippetMetadata: { characterCount: 3180, language: 'EN' },
    freshness: {
      lastIndexedAtLabel: '2025-11-05',
      lastCheckedAtLabel: 'manual',
      refreshPolicy: { mode: 'manual' },
    },
  },
  {
    id: 'msds-so2',
    knowledgeBaseId: 'wine-chemistry',
    title: 'msds-so2.pdf',
    type: 'document',
    originLabel: 'Upload',
    sizeLabel: '340 KB',
    chunkCount: 18,
    updatedAtLabel: '2025-11-20',
    status: 'error',
    statusMessage: 'Encrypted PDF cannot extract',
    metadata: {
      studyLevel: ['both'],
      scope: 'department',
      usage: 'reference',
      topic: 'SO2 safety',
    },
    documentMetadata: {
      pageCount: 12,
      fileSizeLabel: '340 KB',
      mimeType: 'PDF',
      language: 'EN',
    },
    freshness: {
      lastCheckedAtLabel: '2025-11-20',
      lastIndexedAtLabel: 'failed',
      changeStatus: 'error',
      changeStatusLabel: 'Extraction failed',
      refreshPolicy: { mode: 'manual' },
    },
  },
  {
    id: 'quiz-wine-acids',
    knowledgeBaseId: 'wine-chemistry',
    title: 'Quiz: Wine Acids (Week 7)',
    type: 'internal',
    originLabel: 'From library',
    originDetail: 'Klicker quiz',
    chunkCount: 12,
    updatedAtLabel: '2025-11-20',
    status: 'ready',
    metadata: {
      studyLevel: ['bachelor'],
      scope: 'course',
      usage: 'generation',
      topic: 'Practice quiz',
    },
    internalMetadata: {
      provider: 'KlickerUZH',
      objectType: 'Quiz',
      courseLabel: 'Wine Chemistry',
      scopeLabel: 'Course',
      itemCount: 18,
    },
    freshness: {
      lastCheckedAtLabel: '2025-11-20',
      lastIndexedAtLabel: '2025-11-20',
      nextCheckAtLabel: 'on library change',
      changeStatus: 'unchanged',
      refreshPolicy: { mode: 'inherit' },
    },
  },
  {
    id: 'element-titratable-acidity',
    knowledgeBaseId: 'wine-chemistry',
    title: 'Element: Titratable Acidity (SC)',
    type: 'internal',
    originLabel: 'From library',
    originDetail: 'Klicker element',
    chunkCount: 2,
    updatedAtLabel: '2025-11-18',
    status: 'ready',
    metadata: {
      studyLevel: ['bachelor'],
      scope: 'course',
      usage: 'rag',
      topic: 'Single choice element',
    },
    internalMetadata: {
      provider: 'KlickerUZH',
      objectType: 'Element',
      courseLabel: 'Wine Chemistry',
      scopeLabel: 'Course',
      itemCount: 1,
    },
    freshness: {
      lastCheckedAtLabel: '2025-11-18',
      lastIndexedAtLabel: '2025-11-18',
      nextCheckAtLabel: 'on library change',
      refreshPolicy: { mode: 'inherit' },
    },
  },
  {
    id: 'finance-wacc',
    knowledgeBaseId: 'finance-core',
    title: 'Lecture 03 - Cost of Capital.pdf',
    type: 'document',
    originLabel: 'Upload',
    sizeLabel: '3.2 MB',
    chunkCount: 210,
    updatedAtLabel: '2025-10-21',
    status: 'indexing',
    progress: 38,
    metadata: {
      studyLevel: ['bachelor'],
      scope: 'course',
      usage: 'rag',
      topic: 'WACC',
    },
    documentMetadata: {
      pageCount: 74,
      fileSizeLabel: '3.2 MB',
      mimeType: 'PDF',
    },
    freshness: {
      lastCheckedAtLabel: '2025-10-21',
      lastIndexedAtLabel: 'running',
      refreshPolicy: { mode: 'manual' },
    },
  },
]

export const demoGraphData: KnowledgeGraphData = {
  extractedByLabel: 'extracted by Claude Haiku 4.5',
  nodes: [
    { id: 'ph', label: 'pH', type: 'concept', x: 385, y: 250, size: 19 },
    { id: 'wine', label: 'Wine', type: 'concept', x: 280, y: 320, size: 22 },
    {
      id: 'malic',
      label: 'Malic acid',
      type: 'compound',
      x: 540,
      y: 335,
      size: 13,
    },
    {
      id: 'tartaric',
      label: 'Tartaric acid',
      type: 'compound',
      x: 500,
      y: 270,
      size: 15,
    },
    {
      id: 'potassium',
      label: 'Potassium',
      type: 'compound',
      x: 340,
      y: 185,
      size: 13,
    },
    {
      id: 'ph-card',
      label: 'pH ref card',
      type: 'doc',
      x: 360,
      y: 145,
      size: 10,
    },
    {
      id: 'lecture-07',
      label: 'Lecture 07',
      type: 'doc',
      x: 180,
      y: 190,
      size: 11,
    },
    {
      id: 'ethanol',
      label: 'Ethanol',
      type: 'compound',
      x: 150,
      y: 265,
      size: 12,
    },
    {
      id: 'fermentation',
      label: 'Fermentation',
      type: 'process',
      x: 210,
      y: 350,
      size: 17,
    },
    {
      id: 'acidity',
      label: 'Acidity',
      type: 'concept',
      x: 440,
      y: 335,
      size: 16,
    },
    { id: 'so2', label: 'SO2', type: 'compound', x: 245, y: 420, size: 13 },
    {
      id: 'lactic',
      label: 'Lactic acid',
      type: 'compound',
      x: 455,
      y: 410,
      size: 12,
    },
    {
      id: 'titration',
      label: 'Titration',
      type: 'process',
      x: 105,
      y: 405,
      size: 12,
    },
  ],
  edges: [
    { id: 'e1', source: 'ph', target: 'wine', label: 'has property' },
    { id: 'e2', source: 'ph', target: 'tartaric' },
    { id: 'e3', source: 'ph', target: 'malic' },
    { id: 'e4', source: 'ph', target: 'potassium' },
    { id: 'e5', source: 'ph-card', target: 'ph' },
    { id: 'e6', source: 'fermentation', target: 'wine' },
    { id: 'e7', source: 'fermentation', target: 'ethanol' },
    { id: 'e8', source: 'acidity', target: 'ph' },
    { id: 'e9', source: 'lactic', target: 'malic' },
    { id: 'e10', source: 'so2', target: 'fermentation' },
    { id: 'e11', source: 'titration', target: 'acidity' },
    { id: 'e12', source: 'lecture-07', target: 'fermentation' },
  ],
}

export const demoSettingsData: KnowledgeBaseSettingsData = {
  generationModels: [
    {
      id: 'haiku',
      name: 'Claude Haiku 4.5',
      description: 'Fast - 200k context',
      costLabel: '$0.80 / $4.00 per Mtok',
      active: true,
    },
    {
      id: 'sonnet',
      name: 'Claude Sonnet 4.5',
      description: 'Balanced - 200k context',
      costLabel: '$3.00 / $15.00 per Mtok',
    },
    {
      id: 'gpt-4o-mini',
      name: 'GPT-4o mini',
      description: 'OpenAI fallback',
      costLabel: '$0.15 / $0.60 per Mtok',
    },
  ],
  embeddingModels: [
    {
      id: 'text-embedding-3-large',
      name: 'text-embedding-3-large',
      description: '3072 dimensions',
      costLabel: '$0.13 per Mtok',
      active: true,
    },
    {
      id: 'text-embedding-3-small',
      name: 'text-embedding-3-small',
      description: '1536 dimensions',
      costLabel: '$0.02 per Mtok',
    },
  ],
  retrievalSettings: [
    { id: 'chunks', label: 'Chunks per query', value: '6' },
    { id: 'threshold', label: 'Similarity threshold', value: '0.78' },
    { id: 'window', label: 'Context window', value: '12,000 tok' },
    { id: 'strategy', label: 'Strategy', value: 'Hybrid (BM25 + vec)' },
    { id: 'citations', label: 'Citations', value: 'Required' },
    { id: 'fallback', label: 'Off-KB fallback', value: 'Refuse + suggest' },
  ],
  costSummary: {
    currentSpendLabel: '$10.84',
    budgetLabel: '$24 / mo budget - 45% used',
    categories: [
      {
        id: 'embeddings',
        label: 'Embeddings',
        valueLabel: '$1.42',
        colorClassName: 'bg-primary-100',
      },
      {
        id: 'retrieval',
        label: 'Retrieval',
        valueLabel: '$8.30',
        colorClassName: 'bg-cyan-700',
      },
      {
        id: 'reranking',
        label: 'Reranking',
        valueLabel: '$0.94',
        colorClassName: 'bg-amber-700',
      },
      {
        id: 'crawls',
        label: 'Crawls',
        valueLabel: '$0.18',
        colorClassName: 'bg-green-700',
      },
    ],
  },
  indexingSchedule: {
    id: 'daily',
    label: 'Daily - 03:00 CET',
    nextRunLabel: 'Next run in 9h 22m. Only refreshable resources are checked.',
  },
}

export const demoAiBuddyKnowledgeBases: KnowledgeBaseSummary[] = [
  {
    id: 'ai-buddy-support',
    name: 'AI Buddy Student Support',
    description: 'Guidance pages, regulations, support snippets',
    resourceCount: 19,
    status: 'ready',
    statusLabel: 'Ready',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: {
      owner: 'Teaching Center',
      audience: 'support',
      semester: '2026',
    },
    resourceMetadataSchema: demoResourceMetadataSchema,
    resourceTypes: demoResourceTypes,
    refreshPolicy: {
      mode: 'interval',
      intervalLabel: 'Weekly',
      scope: 'websites',
      changeMonitoring: true,
    },
    metrics: [
      { id: 'resources', label: 'Resources', value: 19 },
      { id: 'chunks', label: 'Chunks', value: '988' },
      { id: 'freshness', label: 'Freshness', value: '94%' },
    ],
  },
]

export const demoAiBuddyResources: KnowledgeResource[] = [
  {
    id: 'uzh-exams',
    knowledgeBaseId: 'ai-buddy-support',
    title: 'Student exam regulations',
    type: 'website',
    originLabel: 'Crawl',
    originDetail: 'UZH website',
    chunkCount: 42,
    updatedAtLabel: '1d ago',
    status: 'ready',
    metadata: {
      studyLevel: ['both'],
      scope: 'uzh',
      usage: 'rag',
      topic: 'Regulations',
    },
    websiteMetadata: {
      strategy: 'S',
      strategyLabel: 'S scrape subsites',
      sitemapFound: true,
      sitemapPageCount: 67,
      subsites: [
        {
          id: 'uzh-exams-bachelor',
          title: 'Bachelor exam regulations',
          url: 'https://www.uzh.ch/studies/exams/bachelor',
          status: 'ready',
          chunkCount: 16,
          lastCheckedAtLabel: '1d ago',
        },
        {
          id: 'uzh-exams-master',
          title: 'Master exam regulations',
          url: 'https://www.uzh.ch/studies/exams/master',
          status: 'ready',
          chunkCount: 18,
          lastCheckedAtLabel: '1d ago',
        },
      ],
    },
    freshness: {
      lastCheckedAtLabel: '1d ago',
      lastIndexedAtLabel: '1d ago',
      lastRemoteModifiedAtLabel: '3d ago',
      nextCheckAtLabel: 'next Monday',
      changeStatus: 'unchanged',
      refreshPolicy: { mode: 'inherit' },
    },
  },
  {
    id: 'department-faq',
    knowledgeBaseId: 'ai-buddy-support',
    title: 'Department FAQ for master applications',
    type: 'snippet',
    originLabel: 'Pasted',
    originDetail: 'advisor notes',
    chunkCount: 9,
    updatedAtLabel: '3d ago',
    status: 'ready',
    metadata: {
      studyLevel: ['master'],
      scope: 'department',
      usage: 'generation',
      topic: 'Applications',
    },
    snippetMetadata: {
      characterCount: 4870,
      language: 'EN',
      author: 'Student office',
    },
    freshness: {
      lastIndexedAtLabel: '3d ago',
      lastCheckedAtLabel: 'manual',
      refreshPolicy: { mode: 'manual' },
    },
  },
]

export const demoAiInfraKnowledgeBases: KnowledgeBaseSummary[] = [
  {
    id: 'ai-infra',
    name: 'AI Infra Operations',
    description: 'Runbooks, incident reports, deployment notes',
    resourceCount: 31,
    status: 'ready',
    statusLabel: 'Ready',
    metadataSchema: demoKnowledgeBaseMetadataSchema,
    metadata: { owner: 'AI Infra', audience: 'ops' },
    resourceMetadataSchema: demoResourceMetadataSchema,
    resourceTypes: demoResourceTypes,
    refreshPolicy: {
      mode: 'interval',
      intervalLabel: 'Daily',
      scope: 'refreshable',
      changeMonitoring: true,
    },
    metrics: [
      { id: 'resources', label: 'Resources', value: 31 },
      { id: 'chunks', label: 'Chunks', value: '2,904' },
      { id: 'services', label: 'Services', value: 12 },
      { id: 'freshness', label: 'Freshness', value: '91%' },
    ],
  },
]

export const demoAiInfraResources: KnowledgeResource[] = [
  {
    id: 'aks-runbook',
    knowledgeBaseId: 'ai-infra',
    title: 'AKS incident response runbook',
    type: 'internal',
    originLabel: 'Git',
    originDetail: 'infra/runbooks',
    chunkCount: 54,
    updatedAtLabel: '2026-04-24',
    status: 'ready',
    metadata: {
      studyLevel: ['both'],
      scope: 'department',
      usage: 'rag',
      topic: 'AKS',
    },
    internalMetadata: {
      provider: 'Git',
      objectType: 'Runbook',
      scopeLabel: 'AI Infra',
      itemCount: 8,
    },
    freshness: {
      lastCheckedAtLabel: '2h ago',
      lastIndexedAtLabel: '2h ago',
      nextCheckAtLabel: 'tomorrow 03:00',
      refreshPolicy: { mode: 'inherit' },
    },
    chunkPreviews: [
      {
        id: 'aks-1',
        label: 'section #4',
        content:
          'During node pressure incidents, cordon affected pools before restarting GPU workloads to preserve queue throughput.',
      },
    ],
  },
  {
    id: 'gpu-costs',
    knowledgeBaseId: 'ai-infra',
    title: 'GPU Cost Review Q1.xlsx',
    type: 'document',
    originLabel: 'Upload',
    sizeLabel: '812 KB',
    chunkCount: 33,
    updatedAtLabel: '2026-04-20',
    status: 'ready',
    metadata: {
      studyLevel: ['both'],
      scope: 'department',
      usage: 'reference',
      topic: 'GPU costs',
    },
    documentMetadata: {
      pageCount: 6,
      fileSizeLabel: '812 KB',
      mimeType: 'XLSX',
      author: 'AI Infra',
    },
    freshness: {
      lastCheckedAtLabel: '2026-04-20',
      lastIndexedAtLabel: '2026-04-20',
      refreshPolicy: { mode: 'manual' },
    },
  },
  {
    id: 'status-page',
    knowledgeBaseId: 'ai-infra',
    title: 'status.ai.uzh.ch',
    type: 'website',
    originLabel: 'Crawl',
    originDetail: 'depth 1',
    chunkCount: 18,
    updatedAtLabel: '2h ago',
    status: 'ready',
    metadata: {
      studyLevel: ['both'],
      scope: 'uzh',
      usage: 'rag',
      topic: 'Service health',
    },
    websiteMetadata: {
      strategy: 'S',
      strategyLabel: 'S scrape subsites',
      sitemapFound: false,
      scrapedPageCount: 9,
      subsites: [
        {
          id: 'status-overview',
          title: 'Current service status',
          url: 'https://status.ai.uzh.ch/',
          status: 'ready',
          chunkCount: 8,
          lastCheckedAtLabel: '2h ago',
        },
        {
          id: 'status-incidents',
          title: 'Incident history',
          url: 'https://status.ai.uzh.ch/incidents',
          status: 'ready',
          chunkCount: 10,
          lastCheckedAtLabel: '2h ago',
        },
      ],
    },
    freshness: {
      lastCheckedAtLabel: '2h ago',
      lastIndexedAtLabel: '2h ago',
      nextCheckAtLabel: 'tomorrow 03:00',
      refreshPolicy: { mode: 'inherit' },
    },
  },
]
