{{- if .Values.shibboleth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-shibboleth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (.Files.Glob "shibboleth/**.pem").AsSecrets | nindent 2 }}
{{- end }}
