{{- if .Values.shibboleth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-shibboleth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.shibboleth.service.type }}
  ports:
    - port: {{ .Values.shibboleth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: shibboleth
{{- end }}
