{{- if .Values.frontend.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}-frontend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "chart.fullname" . }}-frontend
  updatePolicy:
    updateMode: "Off"
{{- end }}
---
{{- if .Values.backend.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}-backend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "chart.fullname" . }}-backend
  updatePolicy:
    updateMode: "Off"
{{- end }}
