apiVersion: v2
name: klicker-uzh-v2
description: A Helm chart for the KlickerUZH
type: application
version: 3.3.0-alpha.82
appVersion: 3.3.0-alpha.82
dependencies:
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami
