language: node_js

node_js:
  - '10'

branches:
  only:
    - dev

cache:
  yarn: true

script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd docs/website && npm ci && GIT_USER="${GH_NAME}" npm run publish-gh-pages
