const QUESTION_TYPES = {
  SC: 'SC',
  MC: 'MC',
  FREE: 'FREE',
  FREE_RANGE: 'FREE_RANGE',
}

const QUESTION_GROUPS = {
  CHOICES: [QUESTION_TYPES.SC, QUESTION_TYPES.MC],
  FREE: [QUESTION_TYPES.FREE, QUESTION_TYPES.FREE_RANGE],
  WITH_OPTIONS: [QUESTION_TYPES.SC, QUESTION_TYPES.MC, QUESTION_TYPES.FREE_RANGE],
}

const QUESTION_BLOCK_STATUS = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  EXECUTED: 'EXECUTED',
}

const SESSION_STATUS = {
  CREATED: 'CREATED',
  RUNNING: 'RUNNING',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
}

const SESSION_ACTIONS = {
  START: 'START',
  PAUSE: 'PAUSE',
  STOP: 'STOP',
  CANCEL: 'CANCEL',
  RESET: 'RESET',
}

const SESSION_STORAGE_MODE = {
  SECRET: 'SECRET',
  COMPLETE: 'COMPLETE',
}

const Errors = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_SHORTNAME: 'INVALID_SHORTNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_USER: 'INVALID_USER',
  INVALID_INPUT: 'INVALID_INPUT',
  SESSION_ALREADY_STARTED: 'SESSION_ALREADY_STARTED',
  EMAIL_NOT_AVAILABLE: 'EMAIL_NOT_AVAILABLE',
  SHORTNAME_NOT_AVAILABLE: 'SHORTNAME_NOT_AVAILABLE',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  INVALID_LOGIN: 'INVALID_LOGIN',
}

module.exports = {
  QUESTION_TYPES,
  QUESTION_GROUPS,
  QUESTION_BLOCK_STATUS,
  SESSION_STATUS,
  SESSION_ACTIONS,
  SESSION_STORAGE_MODE,
  Errors,
}
