{{- $fullName := include "chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-hatchet-worker-general
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  HATCHET_CLIENT_TLS_STRATEGY: {{ .Values.hatchet.client.tlsStrategy | quote }}
  HATCHET_API_URL: {{ .Values.hatchet.client.apiUrl | quote }}
  {{- if .Values.hatchet.kbIngestion }}
  {{- if .Values.hatchet.kbIngestion.workerDisabled }}
  KB_INGESTION_WORKER_DISABLED: {{ .Values.hatchet.kbIngestion.workerDisabled | quote }}
  {{- end }}
  KB_INGESTION_API_URL: {{ .Values.hatchet.kbIngestion.apiUrl | quote }}
  KB_INGESTION_PROJECT_ID: {{ .Values.hatchet.kbIngestion.projectId | quote }}
  KB_SOURCE_GATEWAY_URL: {{ .Values.hatchet.kbIngestion.sourceGatewayUrl | quote }}
  {{- end }}
  {{- if .Values.hatchet.kbGraph }}
  {{- if .Values.hatchet.kbGraph.disabled }}
  KB_GRAPH_DISABLED: {{ .Values.hatchet.kbGraph.disabled | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-hatchet-worker-response-processor
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  HATCHET_CLIENT_TLS_STRATEGY: {{ .Values.hatchet.client.tlsStrategy | quote }}
  HATCHET_API_URL: {{ .Values.hatchet.client.apiUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-hatchet-worker-response-processor-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  HATCHET_CLIENT_TLS_STRATEGY: {{ .Values.hatchet.client.tlsStrategy | quote }}
  HATCHET_API_URL: {{ .Values.hatchet.client.apiUrl | quote }}
  ASSESSMENT_MODE: 'true'
