{{- $fullName := include "chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-response-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  CORS_ALLOWED_ORIGINS: {{ .Values.responseApi.corsAllowedOrigins | quote }}
  HATCHET_CLIENT_TLS_STRATEGY: {{ .Values.hatchet.client.tlsStrategy | quote }}
  HATCHET_API_URL: {{ .Values.hatchet.client.apiUrl | quote }}
