apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-chat
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: chat
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 5
  {{- with .Values.chat.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.chat.autoscaling.enabled }}
  replicas: {{ .Values.chat.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chat
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-chat.yaml") . | sha256sum }}
        release: {{ .Chart.AppVersion }}
      {{- with .Values.chat.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chat
    spec:
      priorityClassName: {{ include "chart.fullname" . }}-{{ .Values.chat.priorityClassName }}
      {{- with .Values.chat.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.chat.podSecurityContext | nindent 8 }}
      containers:
        - name: chat
          securityContext:
            {{- toYaml .Values.chat.securityContext | nindent 12 }}
          image: "{{ .Values.chat.image.repository }}:{{ .Values.chat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.chat.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config-global
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config-chat
            - secretRef:
                name: {{ include "chart.fullname" . }}-secret-chat
            - secretRef:
                name: {{ include "chart.fullname" . }}-secret-growthbook
                optional: true
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.chat.resources | nindent 12 }}
      {{- with .Values.chat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
