apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-frontend-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-assessment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 5
  {{- with .Values.assessment.frontendPWA.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.assessment.frontendPWA.autoscaling.enabled }}
  replicas: {{ .Values.assessment.frontendPWA.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend-assessment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-frontend-assessment.yaml") . | sha256sum }}
        release: {{ .Chart.AppVersion }}
      {{- with .Values.assessment.frontendPWA.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend-assessment
    spec:
      priorityClassName: {{ include "chart.fullname" . }}-{{ .Values.assessment.frontendPWA.priorityClassName }}
      {{- with .Values.assessment.frontendPWA.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.assessment.frontendPWA.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend-assessment
          securityContext:
            {{- toYaml .Values.assessment.frontendPWA.securityContext | nindent 12 }}
          image: "{{ .Values.assessment.frontendPWA.image.repository }}:{{ .Values.assessment.frontendPWA.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.assessment.frontendPWA.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config-global
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config-frontend-assessment
            - secretRef:
                name: {{ include "chart.fullname" . }}-secret-frontend-assessment
          livenessProbe:
            httpGet:
              path: /login
              port: http
          readinessProbe:
            httpGet:
              path: /login
              port: http
          resources:
            {{- toYaml .Values.assessment.frontendPWA.resources | nindent 12 }}
      {{- with .Values.assessment.frontendPWA.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.assessment.frontendPWA.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.assessment.frontendPWA.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-backend-assessment
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-assessment
spec:
  revisionHistoryLimit: 5
  {{- with .Values.assessment.backendGraphql.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.assessment.backendGraphql.autoscaling.enabled }}
  replicas: {{ .Values.assessment.backendGraphql.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend-assessment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-backend-assessment.yaml") . | sha256sum }}
        release: {{ .Chart.AppVersion }}
      {{- with .Values.assessment.backendGraphql.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend-assessment
    spec:
      priorityClassName: {{ include "chart.fullname" . }}-{{ .Values.assessment.backendGraphql.priorityClassName }}
      {{- with .Values.assessment.backendGraphql.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.assessment.backendGraphql.podSecurityContext | nindent 8 }}
      containers:
        - name: backend-assessment
          securityContext:
            {{- toYaml .Values.assessment.backendGraphql.securityContext | nindent 12 }}
          image: "{{ .Values.assessment.backendGraphql.image.repository }}:{{ .Values.assessment.backendGraphql.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.assessment.backendGraphql.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config-global
            - configMapRef:
                name: {{ include "chart.fullname" . }}-config-backend-assessment
            - secretRef:
                name: {{ include "chart.fullname" . }}-secret-backend-assessment
            - secretRef:
                name: {{ include "chart.fullname" . }}-secret-growthbook
                optional: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 600
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.assessment.backendGraphql.resources | nindent 12 }}
      {{- with .Values.assessment.backendGraphql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.assessment.backendGraphql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.assessment.backendGraphql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
