apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}-chat
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: chat
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chat
