{{- if .Values.mcpStudent.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}-mcp-student
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-student
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-student
{{- end }}
