apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "chart.fullname" . }}-staging-workload
  labels:
    {{- include "chart.labels" . | nindent 4 }}
value: 100000
globalDefault: false
description: "Only for non-critical staging workloads."
