describe('Tests the avilability of certain functionalities to catalyst users only', () => {
  it('Test login for catalyst users and non-catalyst users', () => {
    cy.loginLecturer()
    cy.wait(1000)
    cy.loginFreeUser()
    cy.wait(1000)
    cy.loginIndividualCatalyst()
    cy.wait(1000)
    cy.loginInstitutionalCatalyst()
  })

  it('Test that the creation buttons for practice quizzes and micro learnings are only available to catalyst users', () => {
    cy.loginLecturer()
    cy.wait(1000)
    cy.get('[data-cy="create-practice-quiz"]').should('not.be.disabled')
    cy.get('[data-cy="create-microlearning"]').should('not.be.disabled')
    cy.loginFreeUser()
    cy.wait(1000)
    cy.get('[data-cy="create-practice-quiz"]').should('be.disabled')
    cy.get('[data-cy="create-microlearning"]').should('be.disabled')
    cy.loginIndividualCatalyst()
    cy.wait(1000)
    cy.get('[data-cy="create-practice-quiz"]').should('not.be.disabled')
    cy.get('[data-cy="create-microlearning"]').should('not.be.disabled')
    cy.loginInstitutionalCatalyst()
    cy.wait(1000)
    cy.get('[data-cy="create-practice-quiz"]').should('not.be.disabled')
    cy.get('[data-cy="create-microlearning"]').should('not.be.disabled')
  })
})
