describe('Tests the avilability of certain functionalities to catalyst users only', () => {
  it('Test login for catalyst users and non-catalyst users', () => {
    cy.loginLecturer()
    cy.wait(1000)
    cy.loginFreeUser()
    cy.wait(1000)
    cy.loginIndividualCatalyst()
    cy.wait(1000)
    cy.loginInstitutionalCatalyst()
  })

  it('Test that the creation buttons for learning elements and micro learnings are only available to catalyst users', () => {
    cy.loginLecturer()
    cy.wait(1000)
    cy.get('[data-cy="create-learning-element"]').should('not.be.disabled')
    cy.get('[data-cy="create-micro-session"]').should('not.be.disabled')
    cy.loginFreeUser()
    cy.wait(1000)
    cy.get('[data-cy="create-learning-element"]').should('be.disabled')
    cy.get('[data-cy="create-micro-session"]').should('be.disabled')
    cy.loginIndividualCatalyst()
    cy.wait(1000)
    cy.get('[data-cy="create-learning-element"]').should('not.be.disabled')
    cy.get('[data-cy="create-micro-session"]').should('not.be.disabled')
    cy.loginInstitutionalCatalyst()
    cy.wait(1000)
    cy.get('[data-cy="create-learning-element"]').should('not.be.disabled')
    cy.get('[data-cy="create-micro-session"]').should('not.be.disabled')
  })
})
