sharedConfig:
  # you can disable shared config by setting this to false
  enabled: true

  # these are the most commonly configured values
  # serverUrl: "http://localhost:8080"
  # serverAuthCookieDomain: "localhost:8080" # the domain for the auth cookie
  # serverAuthCookieInsecure: "t" # allows cookies to be set over http
  # serverAuthSetEmailVerified: "t" # automatically sets email_verified to true for all users
  # serverAuthBasicAuthEnabled: "t" # allows login via basic auth (email/password)
  grpcBroadcastAddress: 'hatchet-grpc:7070' # the endpoint for the gRPC server, exposed via the `grpc` service
  grpcInsecure: 'true' # allows gRPC to be served over http

  # you can set additional environment variables here, which will override any defaults
  # env:

api:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: staging-workload

frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: staging-workload

postgres:
  enabled: false

grpc:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: staging-workload

controllers:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: staging-workload

scheduler:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: staging-workload

caddy:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  priorityClassName: staging-workload
