dfDomain: <path:keyvaultp19gA04dNy#EMAIL_TYPE>

teamsWebhookUrl: <path:keyvaultp19gA04dNy#TEAMS_WEBHOOK_URL>

appSecret: <path:keyvaultp19gA04dNy#APP_SECRET>

email:
  type: <path:keyvaultp19gA04dNy#EMAIL_TYPE>
  from: <path:keyvaultp19gA04dNy#EMAIL_FROM>
  host: <path:keyvaultp19gA04dNy#EMAIL_HOST>
  port: <path:keyvaultp19gA04dNy#EMAIL_PORT>
  username: <path:keyvaultp19gA04dNy#EMAIL_USER>
  password: <path:keyvaultp19gA04dNy#EMAIL_PASS>
  secure: <path:keyvaultp19gA04dNy#EMAIL_SECURE>
  requireTLS: <path:keyvaultp19gA04dNy#EMAIL_STARTTLS>

eduId:
  clientSecret: <path:keyvaultp19gA04dNy#EDUID_CLIENT_SECRET>

auth:
  replicaCount: <path:keyvaultp19gA04dNy#APP_REPLICAS>
  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

frontendPWA:
  replicaCount: <path:keyvaultp19gA04dNy#APP_REPLICAS>
  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

frontendManage:
  replicaCount: <path:keyvaultp19gA04dNy#APP_REPLICAS>
  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

frontendControl:
  replicaCount: <path:keyvaultp19gA04dNy#APP_REPLICAS>
  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

backendGraphql:
  replicaCount: <path:keyvaultp19gA04dNy#APP_REPLICAS>

  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

  apiDomain: <path:keyvaultp19gA04dNy#API_DOMAIN>
  cookieDomain: <path:keyvaultp19gA04dNy#COOKIE_DOMAIN>
  databaseUrl: <path:keyvaultp19gA04dNy#DATABASE_URL>
  debug: true

  appManageSubdomain: <path:keyvaultp19gA04dNy#APP_MANAGE_SUBDOMAIN>
  appManageDomain: <path:keyvaultp19gA04dNy#APP_MANAGE_DOMAIN>
  appStudentSubdomain: <path:keyvaultp19gA04dNy#APP_STUDENT_SUBDOMAIN>
  appStudentDomain: <path:keyvaultp19gA04dNy#APP_STUDENT_DOMAIN>
  appControlSubdomain: <path:keyvaultp19gA04dNy#APP_CONTROL_SUBDOMAIN>
  appControlDomain: <path:keyvaultp19gA04dNy#APP_CONTROL_DOMAIN>

  notifications:
    url: <path:keyvaultp19gA04dNy#NOTIFICATION_URL>
    secret: <path:keyvaultp19gA04dNy#NOTIFICATION_SECRET>
    supportEmail: <path:keyvaultp19gA04dNy#NOTIFICATION_SUPPORT_EMAIL>

  vapid:
    publicKey: <path:keyvaultp19gA04dNy#VAPID_PUBLIC_KEY>
    privateKey: <path:keyvaultp19gA04dNy#VAPID_PRIVATE_KEY>

  redisCache:
    host: <path:keyvaultp19gA04dNy#REDIS_CACHE_HOST>
    port: <path:keyvaultp19gA04dNy#REDIS_CACHE_PORT>
    pass: <path:keyvaultp19gA04dNy#REDIS_CACHE_PASS>

  redisExec:
    host: <path:keyvaultp19gA04dNy#REDIS_HOST>
    port: <path:keyvaultp19gA04dNy#REDIS_PORT>
    tls: <path:keyvaultp19gA04dNy#REDIS_TLS>
    pass: <path:keyvaultp19gA04dNy#REDIS_PASS>

  sentryEnv: qa
  sentryDSN: <path:keyvaultp19gA04dNy#SENTRY_DSN>

olatApi:
  key: <path:keyvaultp19gA04dNy#OLAT_API_KEY>

  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

lti:
  replicaCount: <path:keyvaultp19gA04dNy#APP_REPLICAS>

  image:
    tag: <path:keyvaultp19gA04dNy#APP_VERSION>

  appSecret: <path:keyvaultp19gA04dNy#APP_SECRET>
  clientId: <path:keyvaultp19gA04dNy#LTI_CLIENT_ID>
  redirectURL: <path:keyvaultp19gA04dNy#LTI_REDIRECT_URL>
  cookieDomain: <path:keyvaultp19gA04dNy#COOKIE_DOMAIN>
  encryptionKey: <path:keyvaultp19gA04dNy#APP_SECRET>
  name: <path:keyvaultp19gA04dNy#LTI_NAME>
  url: <path:keyvaultp19gA04dNy#LTI_URL>
  authEndpoint: <path:keyvaultp19gA04dNy#LTI_AUTH_ENDPOINT>
  tokenEndpoint: <path:keyvaultp19gA04dNy#LTI_TOKEN_ENDPOINT>
  keysEndpoint: <path:keyvaultp19gA04dNy#LTI_KEYS_ENDPOINT>

  db:
    type: <path:keyvaultp19gA04dNy#LTI_DB_TYPE>
    host: <path:keyvaultp19gA04dNy#LTI_DB_HOST>
    port: <path:keyvaultp19gA04dNy#LTI_DB_PORT>
    name: <path:keyvaultp19gA04dNy#LTI_DB_NAME>
    username: <path:keyvaultp19gA04dNy#LTI_DB_USER>
    password: <path:keyvaultp19gA04dNy#LTI_DB_PASS>
