heartbeats:
  dailyGroupScores: https://betteruptime.com/api/v1/heartbeat/xN8ytcTixyVXsWnNjk9ndimD

auth:
  priorityClassName: staging-workload

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: auth.klicker-qa.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-prod-frontend-auth-tls
        hosts:
          - auth.klicker-qa.bf-app.ch

  strategy:
    type: RollingUpdate
    # type: Recreate

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi

frontendPWA:
  priorityClassName: staging-workload

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: pwa.klicker-qa.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-qa-frontend-pwa-tls
        hosts:
          - pwa.klicker-qa.bf-app.ch

  strategy:
    type: Recreate

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi

frontendManage:
  priorityClassName: staging-workload

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: manage.klicker-qa.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-qa-frontend-manage-tls
        hosts:
          - manage.klicker-qa.bf-app.ch

  strategy:
    type: Recreate

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi

frontendControl:
  priorityClassName: staging-workload

  autoscaling:
    enabled: false

  ingress:
    hosts:
      - host: control.klicker-qa.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-qa-frontend-control-tls
        hosts:
          - control.klicker-qa.bf-app.ch

  strategy:
    type: Recreate

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi

backendGraphql:
  priorityClassName: staging-workload

  autoscaling:
    enabled: false

  appManageSubdomain: manage
  appStudentSubdomain: pwa
  appControlSubdomain: control

  ingress:
    hosts:
      - host: backend-sls.klicker-qa.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-qa-backend-graphql-tls
        hosts:
          - backend-sls.klicker-qa.bf-app.ch

  strategy:
    type: Recreate

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi

lti:
  priorityClassName: staging-workload

  ingress:
    hosts:
      - host: lti.klicker-qa.bf-app.ch
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: klicker-qa-lti-tls
        hosts:
          - lti.klicker-qa.bf-app.ch

redis:
  priorityClassName: staging-workload
  architecture: standalone
  auth:
    enabled: false
