name: Check syncpack conformity

on:
  push:
    branches: ['v3', 'v3*']
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  check-syncpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: ./.github/actions/changed-paths
        with:
          pattern: '^(package\.json|pnpm-workspace\.yaml|pnpm-lock\.yaml|\.github/workflows/check-syncpack\.yml|\.github/actions/changed-paths/|.*/package\.json)'

      - name: Define node version
        if: steps.filter.outputs.should_run == 'true'
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        if: steps.filter.outputs.should_run == 'true'
        with:
          version: 11.5.0
          run_install: true

      - name: Check the syncpack conformity of all packages and apps
        if: steps.filter.outputs.should_run == 'true'
        shell: bash
        run: |
          pnpm run check:syncpack
