name: Check linting

on:
  push:
    branches: ['v3', 'v3*']
    paths:
      - apps/**
      - packages/**
  pull_request:
    branches: ['v3', 'v3*']
    types: [opened, synchronize, reopened]
    paths:
      - apps/**
      - packages/**

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.10.0
          run_install: true
      - name: Check linting
        shell: bash
        run: |
          pnpm run lint
