name: Klicker automated testing with cypress
on:
  push:
    branches: ['v3']
  pull_request:
    branches: ["v3"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  # build-backend:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log into registry ${{ env.REGISTRY }}
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v4
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ github.repository }}/backend-docker

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: apps/backend-docker
  #         file: apps/backend-docker/Dockerfile
  #         tags: ${{ env.REGISTRY }}/${{ github.repository }}/backend-docker:cypress
  #         labels: ${{ steps.meta.outputs.labels }}

  # build-frontend-manage:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Replace .env.production with .env.cypress
  #       shell: bash
  #       run: |
  #         rm apps/frontend-manage/.env.production
  #         mv apps/frontend-manage/.env.cypress apps/frontend-manage/.env.production
  #         cp -R packages/shared-components apps/frontend-manage/shared-components

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log into registry ${{ env.REGISTRY }}
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v4
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ github.repository }}/frontend-manage

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: apps/frontend-manage
  #         file: apps/frontend-manage/Dockerfile
  #         tags: ${{ env.REGISTRY }}/${{ github.repository }}/frontend-manage:cypress
  #         labels: ${{ steps.meta.outputs.labels }}

  # build-frontend-pwa:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Replace .env.production with .env.cypress
  #       shell: bash
  #       run: |
  #         rm apps/frontend-pwa/.env.production
  #         mv apps/frontend-pwa/.env.cypress apps/frontend-pwa/.env.production
  #         cp -R packages/shared-components apps/frontend-pwa/shared-components

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log into registry ${{ env.REGISTRY }}
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v4
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ github.repository }}/frontend-pwa

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: apps/frontend-pwa
  #         file: apps/frontend-pwa/Dockerfile
  #         tags: ${{ env.REGISTRY }}/${{ github.repository }}/frontend-pwa:cypress
  #         labels: ${{ steps.meta.outputs.labels }}

  # TODO:
  # build-frontend-control

  # fill-database:

  cypress-run:
    # needs:
    #   - build-backend
    #   - build-frontend-manage
    #   - build-frontend-pwa
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_USER: klicker
          POSTGRES_PASSWORD: klicker
          POSTGRES_DB: main
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis_cache:
        image: redis:6
        ports:
          - 6380:6380
      redis_exec:
        image: redis:6
        ports:
          - 6379:6379
      frontend-manage:
        image: ${{ github.repository }}/frontend-manage:3.0.0-alpha.70
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 3002:3000
      frontend-pwa:
        image: ${{ github.repository }}/frontend-pwa:3.0.0-alpha.70
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 3001:3000
        

    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    #   matrix:
    #     containers: [1, 2] # Uses 2 parallel instances
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Define node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Install azure-functions-core-tools
        # TODO: caching
        run: npm i -g azure-functions-core-tools@4 --unsafe-perm true
      - name: Prepare .env and local.settings.json files
        # TODO: does it work like this?
        env:
          SERVICE_BUS_CONNECTION: ${{ secrets.SERVICE_BUS_CONNECTION_STRING }}
          SERVICE_BUS_QUEUE: "q-gh-actions"
        run: |
          # mv packages/prisma/.env.cypress packages/prisma/.env
          mv apps/backend-docker/.env.template apps/backend-docker/.env
          mv apps/backend-response-processor/local.settings.json.template apps/backend-response-processor/local.settings.json
          mv apps/backend-responses/local.settings.json.template apps/backend-responses/local.settings.json
      - name: Apply migrations and seed the database
        # TODO: caching with turbo? why does it run twice?
        run: |
          npm run build:test
          cd packages/prisma
          npm run prisma:reset:seed -- -f
          # npm run seed:cypress
      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 20
        with:
          install: false
          start: npm run start:test
          wait-on: 'http://localhost:3000' # Waits for above
          record: true
          # parallel: true # Runs test in parallel using settings above
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
