name: Klicker automated testing with cypress
on: 
  push:
    branches:
      - 'Klicker-Testing'
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          browser: firefox