name: Klicker automated testing with cypress
on:
  push:
    branches: ['v3', 'v3*']
  pull_request:
    branches: ['v3', 'v3*']
    types: [opened, synchronize, reopened]
  # workflow_dispatch:

env:
  REGISTRY: ghcr.io
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  cypress-run:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: klicker
          POSTGRES_PASSWORD: klicker
          POSTGRES_DB: klicker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis_cache:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6380:6379
      redis_exec:
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        image: redis:7
        ports:
          - 6379:6379
    # strategy:
    #   fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    #   matrix:
    #     containers: [1, 2, 3, 4] # Run parallel instances
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Define node version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm
            ${{ github.workspace }}/apps/auth/.next/cache
            ${{ github.workspace }}/apps/frontend-pwa/.next/cache
            ${{ github.workspace }}/apps/frontend-manage/.next/cache
            ${{ github.workspace }}/apps/frontend-control/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.0
          run_install: true

      - name: Install bun
        run: pnpm add -g bun@1.0.7

      # - name: Install azure-functions-core-tools
      #   run: npm i -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Prepare .env and local.settings.json files
        run: |
          mv apps/backend-docker/.env.cypress apps/backend-docker/.env
          echo "$FUNC_RESPONSES_SETTINGS" > apps/func-incoming-responses/local.settings.json
          echo "$FUNC_RESPONSE_PROCESSOR_SETTINGS" > apps/func-response-processor/local.settings.json
        env:
          FUNC_RESPONSES_SETTINGS: ${{ secrets.FUNC_RESPONSES_SETTINGS }}
          FUNC_RESPONSE_PROCESSOR_SETTINGS: ${{ secrets.FUNC_RESPONSE_PROCESSOR_SETTINGS }}

      - name: Build all packages and apps
        run: pnpm run build

      - name: Apply migrations and seed the database
        run: |
          cd packages/prisma
          pnpm run prisma:reset:raw -f
          pnpm run seed:test
        env:
          DATABASE_URL: postgres://klicker:klicker@localhost:5432/klicker

      - name: Start services in the background
        run: pnpm run start:test &
        env:
          DATABASE_URL: postgres://klicker:klicker@localhost:5432/klicker
        # run: pnpm run start:test

      - name: Cypress run
        uses: cypress-io/github-action@v6
        timeout-minutes: 20
        with:
          install: false
          wait-on: 'http://127.0.0.1:3000/api/graphql, http://127.0.0.1:3001, http://127.0.0.1:3002, http://127.0.0.1:3003, http://127.0.0.1:3010'
          wait-on-timeout: 1000
          record: true
          browser: electron
          working-directory: cypress
          # parallel: true
        env:
          APP_SECRET: abcd
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          DATABASE_URL: postgres://klicker:klicker@localhost:5432/klicker
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
