name: Test OLAT-API functionalities

on:
  push:
    branches: ['v3', 'v3*']
    paths:
      - 'apps/olat-api/**'
      - 'packages/prisma/**'
      - 'packages/grading/**'
      - 'packages/util/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - '.github/workflows/test-olat-api.yml'
  pull_request:
    branches: ['v3', 'v3*']
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'apps/olat-api/**'
      - 'packages/prisma/**'
      - 'packages/grading/**'
      - 'packages/util/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - '.github/workflows/test-olat-api.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  test-olat-api:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define node version
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.0
          run_install: true

      - name: Run tests using Docker
        run: |
          cd packages/prisma
          pnpm run build
          cd ../grading
          pnpm run build
          cd ../util
          pnpm run build
          cd ../../apps/olat-api
          pnpm run test
