name: Test grading package functionalities

on:
  push:
    branches: ['v3', 'v3*']
    paths:
      - 'packages/grading/**'
      - '.github/workflows/test-grading.yml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'packages/grading/**'
      - '.github/workflows/test-grading.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.0
          run_install: true
      - name: Build types package
        shell: bash
        run: |
          cd packages/prisma
          pnpm run build
          cd ../types
          pnpm run build
      - name: Test functions
        shell: bash
        run: |
          cd packages/grading
          pnpm run test
