name: Test audit package functionalities

on:
  push:
    branches: ['v3', 'v3*']
    paths:
      - 'packages/audit/**'
      - '.github/workflows/test-audit.yml'
  pull_request:
    branches: ['v3', 'v3*']
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite:latest
        ports:
          - 10000:10000 # Blob service
          - 10001:10001 # Queue service
          - 10002:10002 # Table service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
          run_install: true
      - name: Build dependencies
        shell: bash
        run: |
          cd packages/util
          pnpm run build
      - name: Test audit package
        shell: bash
        run: |
          cd apps/audit
          pnpm run test
