name: Build and deploy frontend-pwa to Vercel

on:
  push:
    branches:
      - v2
  workflow_dispatch:

env:
  APP_PATH: 'apps/frontend-pwa'
  NODE_VERSION: '16.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          rm package.json package-lock.json
          pushd './${{ env.APP_PATH }}'
          npm install --package-lock=false
          npm run build --if-present
          npm prune --omit=dev
          popd

      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_FRONTEND_PWA_ID}} #Required
          working-directory: ./apps/frontend-pwa
