name: Build Docker image for frontend-manage (QA)

on:
  push:
    branches:
      - "v2"
    paths:
      - "apps/frontend-manage/**"
      - ".github/workflows/v2_frontend-manage**"
  pull_request:
    branches: [ "v2" ]
    paths:
      - "apps/frontend-manage/**"
      - ".github/workflows/v2_frontend-manage**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend-manage

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace .env.production with .env.qa
        shell: bash
        run: |
          rm apps/frontend-manage/.env.production
          mv apps/frontend-manage/.env.qa apps/frontend-manage/.env.production
          cp -R packages/shared-components apps/frontend-manage/shared-components

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: apps/frontend-manage
          file: apps/frontend-manage/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
