name: Build and deploy func-migration-v2-export to Function App (QA)

on:
  push:
    branches:
      - 'v3'
    paths:
      - 'apps/func-migration-v2-export/**'
      - '.github/workflows/v3_klickeruzhprod-migration-export**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'apps/func-migration-v2-export'
  NODE_VERSION: '18.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pnpm run build --scope @klicker-uzh/func-migration-v2-export
          pnpm prune --prod --config.ignore-scripts=true
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          cp -LR node_modules tmp && rm -rf node_modules && mv tmp node_modules
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'klickeruzhprod-migration-export'
          slot-name: 'qa'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_57EE7CD105254F868DC38AFDB15C7195 }}
