name: Build Docker image for lti (QA)

on:
  push:
    branches:
      - 'v3'
      - 'v3*'
      - 'CI'
    paths:
      - 'apps/lti/**'
      - '.github/workflows/v3_lti**'
  pull_request:
    # branches: [ "v3" ]
    paths:
      - 'apps/lti/**'
      - '.github/workflows/v3_lti**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/lti

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/lti/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
