http:
  routers:
    api:
      rule: 'Host(`api.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'api'

    assessment-api:
      rule: 'Host(`assessment-api.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'api'

    pwa:
      rule: 'Host(`pwa.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'pwa'
      middlewares:
        - 'csp-frame-ancestors'

    assessment:
      rule: 'Host(`assessment.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'pwa'
      middlewares:
        - 'csp-frame-ancestors'

    manage:
      rule: 'Host(`manage.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'manage'

    control:
      rule: 'Host(`control.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'control'
      middlewares:
        - 'csp-frame-ancestors'

    chat:
      rule: 'Host(`chat.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'chat'
      middlewares:
        - 'csp-frame-ancestors'

    auth:
      rule: 'Host(`auth.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'auth'

    response-api:
      rule: 'Host(`response-api.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'response-api'

    response-api-assessment:
      rule: 'Host(`response-api-assessment.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'response-api'

  middlewares:
    csp-frame-ancestors:
      headers:
        customResponseHeaders:
          Content-Security-Policy: "frame-ancestors 'self' https://*.klicker.com *.uzh.ch"

  services:
    api:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3000'

    pwa:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3001'

    manage:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3002'

    control:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3003'

    chat:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3004'

    auth:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3010'

    response-api:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:7078'

tls:
  certificates:
    - certFile: /etc/certs/klicker.com+1.pem
      keyFile: /etc/certs/klicker.com+1-key.pem
