http:
  routers:
    api:
      rule: 'Host(`api.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'api'

    pwa:
      rule: 'Host(`pwa.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'pwa'

    manage:
      rule: 'Host(`manage.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'manage'

    control:
      rule: 'Host(`control.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'control'

    chat:
      rule: 'Host(`chat.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'chat'

    auth:
      rule: 'Host(`auth.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'auth'

    func-responses:
      rule: 'Host(`func-responses.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'func-responses'

    func-response-processor:
      rule: 'Host(`func-response-processor.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'func-response-processor'

    response-api:
      rule: 'Host(`response-api.klicker.com`)'
      entrypoints:
        - 'web'
        - 'websecure'
      service: 'response-api'

  services:
    api:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3000'

    pwa:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3001'

    manage:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3002'

    control:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3003'

    chat:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3004'

    auth:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:3010'

    func-responses:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:7072'

    func-response-processor:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:7073'

    response-api:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:7078'

tls:
  certificates:
    - certFile: /etc/certs/klicker.com+1.pem
      keyFile: /etc/certs/klicker.com+1-key.pem
