// Deterministic keyword search over the checked-in KlickerUZH docs manifest
// (apps/docs/src/generated/docs-manifest.json, generated by Stack B layer B0).
//
// The service is pure: it takes the manifest as input, scores every page with
// the same fixed field weights, breaks ties by route, and classifies the
// outcome (exact / closest / ambiguous / no-result) so the assistant can be
// honest about how well a query matched. It never executes or follows text
// from the docs — returned excerpts are data and are fenced by the caller
// (toolOutputFencing.ts) before they reach the model.

export const KLICKER_DOCS_BASE_URL = 'https://www.klicker.uzh.ch'

export const MAX_DOCS_QUERY_LENGTH = 200
export const MAX_DOCS_RESULTS = 5
export const MAX_DOCS_RESULT_HEADINGS = 3
export const MAX_DOCS_OUTPUT_CHARS = 4000

export type KlickerDocsMedia = { type: string; url: string }

export type KlickerDocsPage = {
  route: string
  title: string
  headings: string[]
  summary: string
  tags: string[]
  media: KlickerDocsMedia[]
  sourcePath: string
  sourceCategory: string
}

export type KlickerDocsUseCase = {
  id: string
  route: string
  title: string
  summary: string
  tags: string[]
  goals: string[]
  media: KlickerDocsMedia[]
  sourceCategory: string
}

export type KlickerDocsManifest = {
  schemaVersion: number
  docsVersion: string
  pages: KlickerDocsPage[]
  useCases: KlickerDocsUseCase[]
  contentDigest: string
}

export type KlickerDocsSearchKind =
  | 'no-result'
  | 'exact'
  | 'closest'
  | 'ambiguous'

export type KlickerDocsSearchResult = {
  route: string
  url: string
  title: string
  sourceCategory: string
  summary: string
  headings: string[]
  media: KlickerDocsMedia[]
}

export type KlickerDocsSearchOutcome = {
  kind: KlickerDocsSearchKind
  results: KlickerDocsSearchResult[]
  truncated: boolean
}

export type KlickerDocsSearchOptions = {
  maxResults?: number
  maxHeadings?: number
  maxOutputChars?: number
}

// Common English and German question words carry no topical signal; dropping
// them keeps AND-matching usable for natural help queries (how do I create a
// live quiz). The list is fixed and short: any word not on it must still be
// found in the docs for a page to match.
const QUERY_STOPWORDS = new Set([
  'a',
  'an',
  'are',
  'can',
  'do',
  'does',
  'for',
  'how',
  'i',
  'is',
  'it',
  'me',
  'of',
  'on',
  'the',
  'to',
  'was',
  'what',
  'where',
  'which',
  'with',
  'das',
  'der',
  'die',
  'ein',
  'eine',
  'fur',
  'ich',
  'ist',
  'kann',
  'man',
  'mit',
  'und',
  'wie',
  'wo',
])

// Fold case and diacritics (NFD plus strip combining marks) so Fragebogen and
// lowercase variants tokenize identically without German-specific rules.
function normalizeText(text: string): string {
  return text.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase()
}

export function tokenizeDocsQuery(query: string): string[] {
  return [
    ...new Set(
      normalizeText(query)
        .split(/[^a-z0-9]+/)
        .filter((token) => token.length > 1 && !QUERY_STOPWORDS.has(token))
    ),
  ]
}

type ScoredDoc = KlickerDocsSearchResult & { tags: string[]; score: number }

// Field weights: a term found in the title signals a stronger match than the
// same term in body prose. Per token only the best field counts, so a term
// repeated across fields does not inflate one page over another.
const FIELD_WEIGHTS = { title: 4, tags: 3, headings: 2, summary: 1 } as const

function tokenizeFieldValue(value: string): Set<string> {
  return new Set(
    normalizeText(value)
      .split(/[^a-z0-9]+/)
      .filter(Boolean)
  )
}

function scoreDoc(
  tokens: string[],
  doc: {
    title: string
    tags: string[]
    headings: string[]
    summary: string
  }
): number | null {
  const title = tokenizeFieldValue(doc.title)
  const tags = new Set(doc.tags.flatMap((tag) => [...tokenizeFieldValue(tag)]))
  const headings = new Set(
    doc.headings.flatMap((heading) => [...tokenizeFieldValue(heading)])
  )
  const summary = tokenizeFieldValue(doc.summary)

  let score = 0
  for (const token of tokens) {
    if (title.has(token)) score += FIELD_WEIGHTS.title
    else if (tags.has(token)) score += FIELD_WEIGHTS.tags
    else if (headings.has(token)) score += FIELD_WEIGHTS.headings
    else if (summary.has(token)) score += FIELD_WEIGHTS.summary
    else return null // AND semantics: every query token must match somewhere.
  }
  return score
}

function toSearchableDocs(manifest: KlickerDocsManifest): ScoredDoc[] {
  const pages = manifest.pages.map((page) => ({
    route: page.route,
    url: `${KLICKER_DOCS_BASE_URL}${page.route}`,
    title: page.title,
    tags: page.tags,
    sourceCategory: page.sourceCategory,
    summary: page.summary,
    headings: page.headings,
    media: page.media,
    score: 0,
  }))
  const useCases = manifest.useCases.map((useCase) => ({
    route: useCase.route,
    url: `${KLICKER_DOCS_BASE_URL}${useCase.route}`,
    title: useCase.title,
    tags: useCase.tags,
    sourceCategory: useCase.sourceCategory,
    summary: useCase.summary,
    headings: useCase.goals,
    media: useCase.media,
    score: 0,
  }))
  return [...pages, ...useCases]
}

export function searchKlickerDocs(
  manifest: KlickerDocsManifest,
  query: string,
  options: KlickerDocsSearchOptions = {}
): KlickerDocsSearchOutcome {
  const maxResults = options.maxResults ?? MAX_DOCS_RESULTS
  const maxHeadings = options.maxHeadings ?? MAX_DOCS_RESULT_HEADINGS

  const tokens = tokenizeDocsQuery(query.slice(0, MAX_DOCS_QUERY_LENGTH))
  if (tokens.length === 0) {
    return { kind: 'no-result', results: [], truncated: false }
  }

  const scored: ScoredDoc[] = []
  for (const doc of toSearchableDocs(manifest)) {
    const score = scoreDoc(tokens, doc)
    if (score !== null) {
      scored.push({ ...doc, score })
    }
  }

  // Deterministic order: score descending, route ascending breaks ties so the
  // same query always returns the same pages in the same order.
  scored.sort((a, b) => b.score - a.score || a.route.localeCompare(b.route))

  if (scored.length === 0) {
    return { kind: 'no-result', results: [], truncated: false }
  }

  const tiedWithTop = scored.filter((doc) => doc.score === scored[0].score)
  let kind: KlickerDocsSearchKind
  if (scored.length === 1) {
    kind = 'exact'
  } else if (tiedWithTop.length > 1) {
    kind = 'ambiguous'
  } else {
    kind = 'closest'
  }

  // Ambiguous answers list the tied pages first; closest leads with the best
  // page followed by weaker matches. Either way the list is capped.
  const capped = scored.slice(0, Math.max(1, maxResults))
  const results: KlickerDocsSearchResult[] = capped.map((doc) => ({
    route: doc.route,
    url: doc.url,
    title: doc.title,
    sourceCategory: doc.sourceCategory,
    summary: doc.summary,
    headings: doc.headings.slice(0, maxHeadings),
    media: doc.media,
  }))

  return { kind, results, truncated: scored.length > capped.length }
}

function formatResult(
  result: KlickerDocsSearchResult,
  maxHeadings: number
): string[] {
  const lines = [
    `- ${result.title} — ${result.url}`,
    `  category: ${result.sourceCategory}`,
  ]
  if (result.summary) {
    lines.push(`  summary: ${result.summary}`)
  }
  if (result.headings.length > 0) {
    lines.push(
      `  sections: ${result.headings.slice(0, maxHeadings).join('; ')}`
    )
  }
  const mediaUrls = result.media.map((item) => item.url)
  if (mediaUrls.length > 0) {
    lines.push(`  media: ${mediaUrls.join('; ')}`)
  }
  return lines
}

const KIND_LEAD_LINES: Record<KlickerDocsSearchKind, string> = {
  'no-result':
    'No documentation page matched all search terms. The bundled docs snapshot may not cover this topic.',
  exact: 'One documentation page matched:',
  closest: 'Closest matching documentation page:',
  ambiguous: 'Several documentation pages match equally well:',
}

// Renders the outcome as bounded plain text. The caller fences this with the
// request's sentinel before it reaches the model, so any instruction-like
// text stored in the docs stays data.
export function formatKlickerDocsSearchOutcome(
  outcome: KlickerDocsSearchOutcome,
  options: KlickerDocsSearchOptions = {}
): string {
  const maxHeadings = options.maxHeadings ?? MAX_DOCS_RESULT_HEADINGS
  const maxOutputChars = options.maxOutputChars ?? MAX_DOCS_OUTPUT_CHARS
  const lines: string[] = [KIND_LEAD_LINES[outcome.kind]]
  for (const result of outcome.results) {
    const resultLines = formatResult(result, maxHeadings)
    if ([...lines, ...resultLines].join('\n').length > maxOutputChars) {
      lines.push('[truncated: further matching pages omitted]')
      break
    }
    lines.push(...resultLines)
  }
  if (
    outcome.truncated &&
    !lines.some((line) => line.startsWith('[truncated'))
  ) {
    lines.push(`[${outcome.results.length} shown; more matching pages omitted]`)
  }
  return lines.join('\n')
}
